// start id with 1000000000001
let completedPlays = [
  {
    id: 1000000000001,
    name: "La Trágica Historia del Doctor Fausto",
    author: "Christopher Marlowe / Rubén Szuchmacher",
    plot: `Estrenada en 1592, La Trágica Historia del Doctor Fausto es la obra fundamental de Christopher Marlowe, el gran autor del teatro isabelino predecesor de Shakespeare. Fausto es el primer gran personaje de la historia del teatro inglés que, descontento en su lucha incansable e insatisfecha por el Conocimiento, pacta con el Diablo la entrega de su alma a cambio de contar con 24 años de los servicios ilimitados de Mefistófeles.`,
    review: ``,
    genres: ["Comedia Nacional", "Teatro Solis", "2023"],
    favourite: false,
    score: 7,
  },
  {
    id: 1000000000002,
    name: "Esperando la Carroza",
    author: "Jacobo Langsner / Jimena Márquez",
    plot: `Mama Cora se acerca a los 80 años y vive con el más pobre de sus hijos. La familia decide reunirse para hablar sobre quien será el próximo en cuidar la madre y todo el mundo intenta esquivar la responsabilidad. Las discusiones se terminan cuando reciben la noticia que Mama Cora ha desaparecido. Ahora todo serán lamentaciones.`,
    review: `Un clásico. Tal vez a esta altura sea más famosa la película que la obra, pero uno no puede perderse de verla. Excelentes actuaciones y muy vigente aún. `,
    genres: ["Comedia Nacional", "Sala Verdi", "2022", "2023"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000000003,
    name: "Constante",
    author: "Pedro Calderón de la Barca / Gabriel Calderón",
    plot: `Constante es una obra escrita por el chileno Guillermo Calderón y el uruguayo Gabriel Calderón, en base a El Príncipe Constante, de Pedro Calderón de la Barca. Es un clásico reversionado en el cual, los autores han decidido "quemar la biblioteca –parafraseando a Borges-" y “trabajar con el texto como si estuviese perdido, como si ya no se pudiera acceder a él, como si lo soñáramos mal, tradujéramos peor, tal vez traicionando a Calderón, pero siendo fieles al Teatro”, explica su director.
    Esta obra que toma como base un clásico de Calderón de la Barca atraviesa la guerra, los sueños, el arte y el teatro del tiempo, para llegar hasta aquí, donde los espectadores del hoy y mañana seguirán juzgándolo con su comprometida mirada.`,
    review: `Es una versión que se separa bastante del original y eso lo hace interesante e entretenido.`,
    genres: ["Comedia Nacional", "Sala Verdi", "2023"],
    favourite: true,
    score: 7,
  },
  {
    id: 1000000000004,
    name: "Edipo Rey",
    author: "Sófocles / Andrés Lima",
    plot: `Para Aristóteles, Edipo era el ejemplo ideal de tragedia. Esta obra clásica del teatro griego sigue representándose hasta hoy en los teatros del mundo, porque sus temas conmueven, más allá de las épocas. Edipo Rey representa varios de los conflictos humanos y arquetipos psicológicos y sociológicos: poder, violencia, superstición, fe, amor, incesto, crimen, castigo y compasión. Todo es cuestionado en esta obra.
    “Edipo se parece demasiado a cada uno de nosotros y refleja lo mejor y lo peor de lo que hacemos o somos capaces de hacer. ¿Cuánto es el dolor por la verdad que hace que te arranques los ojos para no verla?”, cuestiona Andrés Lima, uno de los directores españoles más importante de la escena actual, quien dirigirá este espectáculo en la sala principal del Teatro Solís.`,
    review: `Muy buena actuación y producción en esta nueva interpretación de la obra. ¡Se disfruta un montón!`,
    genres: ["Comedia Nacional", "Teatro Solis", "2023"],
    favourite: false,
    score: 8,
  },
  {
    id: 1000000000005,
    name: "Frankenstein",
    author: "Mary Shelly / Andrea Arobba",
    plot: `¿Qué ocurre cuando se traspasan los límites de lo humano? ¿Podemos generar sin desaparecer una inteligencia que nos supere? Esas preguntas premonitorias, hoy más contemporáneas que nunca, estaban presentes en “Frankenstein o el moderno Prometeo”, una novela escrita al inicio del siglo XIX por una mujer de dieciocho años, Mary Shelley.
    Esa obra visionaria inauguró la ciencia ficción como género y enfrentó al colectivo a las posibles consecuencias de la revolución científica y tecnológica. Su texto nace del dolor del duelo y del deseo subyacente de cruzar la barrera que separa lo inanimado de lo vivo, pero trasciende lo metafísico, abriendo preguntas en torno al derecho de una entidad artificial a considerarse un ser viviente y a aspirar a la felicidad.     
    Para la realización de Frankenstein, la Comedia Nacional invitó a la bailarina y coreógrafa Andrea Arobba para dirigir al elenco y versionar la obra junto a Pablo Casacuberta y a Gabriela Escobar de GEN. Este Frankenstein es un Nuevo Clásico que, en palabras de Arobba, se encuentra “en las fronteras entre el teatro y la danza contemporánea, explora esa tensión y reivindica el ámbito que nunca dejará de ser el centro de la experiencia y la interacción humana: el cuerpo y la vivencia sensorial de estar vivos, compartiendo un tiempo y un espacio”.`,
    review: `Una serie de escenas sin mucha conexión. Tiene una inspiración en el texto original en el mensaje, pero si esperabas ver Frankenstein te vas a ir insatisfecho`,
    genres: ["Comedia Nacional", "2023"],
    favourite: false,
    score: 4,
  },
  {
    id: 1000000000006,
    name: "Macondo",
    author: "Gabriel Garcia Marquez / Varios",
    plot: `Macondo es un acontecimiento cultural de Montevideo; una plataforma para homenajear al escritor colombiano Gabriel García Márquez y para mostrar la potencia y riqueza expresiva del arte latinoamericano contemporáneo.
    Compuesto por un espectáculo central y varias actividades artísticas, el acontecimiento se desarrollará de martes a domingos de octubre en salas y espacios del Teatro Solís. 
    El Teatro Solís y la Comedia Nacional, junto a la Banda Sinfónica y la Orquesta Filarmónica de Montevideo, con dirección de Marianella Morena y Paula Villalba llevarán adelante el espectáculo Macondo, a realizarse en la sala principal del teatro.  
    En paralelo, y a lo largo de cada día, se realizarán talleres, conciertos, exposiciones, conferencias, slams de poesía y freestyle, periodismo performático, entre otras propuestas.`,
    review: `La producción fue espectacular, no solo de la obra, sino también de todas las actividades relacionadas y el acondicionamiento que se realizó en el Teatro Solis. Lastima que es una destrucción total del material original y no se llega a algo bueno como con otras reinterpretaciones de la temporada. Por suerte la obra es consciente y, como nos dice esta misma en una parte, ¡Que vuelvan las obras con sentido ya!`,
    genres: ["Comedia Nacional", "Teatro Solis", "2023"],
    favourite: false,
    score: 6,
  },
  {
    id: 1000000000007,
    name: "Díptico",
    author: "Carla Zúñiga",
    plot: `La dramaturga chilena Carla Zúñiga propone un díptico con dos obras reflexivas, pero con tonos distintos. Por un lado, “Un montón de brujas volando por el cielo", una comedia negra que reflexiona sobre el dolor y sobre cómo nos podemos hacer cargo de él, a la vez que nos interpela sobre la posibilidad de resignificar la emocionalidad y la posibilidad de desarticular el concepto de “bruja”. Por otro lado, "La violación de una actriz de teatro”, que habla de la importancia de nombrar, de hablar de las experiencias de abuso, de que como sociedad seamos capaces de hablar del dolor; de la importancia de creer en los testimonios de las víctimas y de reflexionar sobre la complejidad del abuso.`,
    review: `Buena obra en general que nos ayuda a reflexionar sobre como lidiamos con las emociones, principalmente el dolor. La segunda parte nos hace cuestionarnos como muchas veces como sociedad cuestionamos los relatos de las víctimas y hacemos más difícil una situación que ya de por si es difícil.`,
    genres: ["Comedia Nacional", "Sala Verdi", "2024"],
    favourite: false,
    score: 8,
  },
  {
    id: 1000000000008,
    name: "La Gayina",
    author: "Horacio Quiroga / Israel Adrián Caetano",
    plot: `La Gallina Degollada de Horacio Quiroga es el cuento que da origen a esta obra y se encuentra en el libro Cuentos de amor de locura y de muerte (1917) que cuenta la historia de una familia con cuatro hijos con discapacidad, una hija neurotípica y el horror de la discriminación y el maltrato.
    Entre silencios, violencia y culpas transcurre el misterio de este clásico de Quiroga que será llevado a escena en versión del cineasta Israel Adrián Caetano.`,
    review: `Interesante y fiel adaptación del cuento original.`,
    genres: ["Comedia Nacional", "Teatro Solis", "2024"],
    favourite: false,
    score: 8,
  },
  {
    id: 1000000000009,
    name: "Finlandia",
    author: "Pascal Rambert",
    plot: `Una pareja que se amó apasionadamente, ahora se destroza con el fin de lograr la custodia de su hija. Sobre el resentimiento y dolor escondido en cada humano, va este drama escrito por el francés Pascal Rambert, una de las figuras más destacadas de la escena internacional en la actualidad. Pascal es director, autor y realizador, y se encuentra en Montevideo especialmente para dirigir al elenco.`,
    review: `Buena obra en la que el conflicto se siente real. Más allá del daño que se hacen los protagonistas entre ellos uno al final se pregunta por todo el daño que indirectamente le están haciendo a su hija.`,
    genres: ["Comedia Nacional", "Sala Verdi", "2024"],
    favourite: false,
    score: 8,
  },
  {
    id: 1000000000010,
    name: "Tiempo Slavaje",
    author: "Josep Maria Miró",
    plot: `La obra transcurre en una tranquila urbanización fronteriza donde se organizará una celebración, cerca de una zona donde transitan personas extranjeras de manera irregular. Con la aparición de provocativas pintadas, la paz del pueblo se altera y tras el miedo aparecen las suposiciones y la violencia para trastocar la rutina y la vida interior de esos habitantes.
    Josep Maria Miró es el autor catalán de mayor proyección internacional. En nuestro país se han estrenado con éxito varias de sus obras entre las que figura La Travesía con la Comedia Nacional en 2017, con dirección de Jorge Denevi.  En esta oportunidad, la Comedia decide festejar su 75 aniversario invitando al propio Miró a dirigir al elenco en Tiempo Salvaje.`,
    review: `Excelente obra. Si algo destacó principalmente es la escenografía que, hasta donde recuerdo, nunca vía una mejor. Un block de apartamentos completo que puede trasladarse para adelante y para atrás para ingresar por los costados las gradas y elementos típicos de una cancha de basquetbol o traer desde arriba los elementos necesarios para simular un bosque. Tres escenas que se van intercambiando a lo largo de la obra de forma fluida y crea una ambientación perfecta. Además, tenemos unas buenas actuaciones que hacen que la historia cobre vida y estemos expectantes por lo que sucederá a continuación. Excelente trabajo por todos los implicados en esta producción.`,
    genres: ["Comedia Nacional", "Teatro Solis", "2022"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000000011,
    name: "Las Actas",
    author: "Margarita Musto",
    plot: `En octubre de 2005 la justicia argentina pide la extradición de militares uruguayos para juzgarlos por el secuestro en Buenos Aires y el traslado ilegal a Montevideo de María Claudia García de Gelman. La muchacha estaba embarazada y dio a luz en el Hospital Militar. La bebé fue entregada a un comisario de Policía. La madre hasta hoy sigue desaparecida.
    \n\
    El coronel Gilberto Vázquez está entre los militares que serán extraditados.
    \n\  
    En mayo de 2006 huye al norte del país para evitar su detención mientras la justicia uruguaya resuelve el pedido. A fin de mayo se presenta en la División de Ejército I, ante la promesa de que él y sus compañeros pasarían unos días retenidos y luego serían puestos en libertad mientras se espera la resolución de la justicia.
    \n\  
    El 3 de julio finge un problema de salud y lo llevan al Hospital Militar de donde se fuga. Tres días más tarde lo captura Interpol. El 26 de julio de 2006 en una sala de la Jefatura de Policía de Montevideo donde Vázquez está preso, tienen lugar las sesiones del Tribunal de Honor ordenado por el Comandante en Jefe del Ejército para juzgar su conducta según los principios y el reglamento que rige el honor militar.
    \n\    
    Sus declaraciones dieron lugar a una serie de impactantes actas que circularon públicamente y son la base de esta obra de dramaturgia y dirección de la directora uruguaya Margarita Musto.`,
    review: `Buena obra que representa una parte muy importante de nustra historia reciente`,
    genres: ["Comedia Nacional", "Teatro Circular", "2022"],
    favourite: false,
    score: 8,
  },
  {
    id: 1000000000012,
    name: "El Salto de Darwin",
    author: "Sergio Blanco / Roxana Blanco",
    plot: `El segundo fin de semana de junio del año 1982 se libra la última batalla de la Guerra de las Malvinas que culmina con la rendición del 14 de junio. Toda la acción se desarrolla en la Ruta Nacional N°40, que desciende la Argentina desde el Norte hacia el Sur, en torno a un Ford Falcon del año 1971 en el cual una familia atraviesa el país para esparcir las cenizas del hijo asesinado recientemente en la batalla que ha tenido lugar en la localidad de Puerto Darwin.`,
    review: `Buena obra pero tampoco me pareció que tuviera algo a destacar.`,
    genres: ["Comedia Nacional", "Teatro Solis", "2022"],
    favourite: false,
    score: 7,
  },
  {
    id: 1000000000013,
    name: "Todo su asco del mundo",
    author: "Thomas Bernhard",
    plot: `En los años 80 Thomas Bernhard escribe una serie de piezas cortas: sus emblemáticos dramolette. Teatro y política, asuntos omnipresentes en la obra completa del autor austríaco aparecen también aquí condensados en un conjunto de entremeses feroces que se nutren de la realidad.
    TODO SU ASCO DEL MUNDO  reúne siete piezas de esa serie de teatro breve. Cuatro de ellas versan sobre asuntos políticos y ponen el acento en algunas de las obsesiones del autor: el resurgimiento del nazismo, de la extrema derecha radical, del odio. Las otras tres tienen como tema otra de sus obsesiones: el teatro. Así ,y tomando como eje el derrotero del célebre director alemán Claus Peymann cuando asume la dirección artística del Teatro Nacional de Viena, ironiza sobre el mundillo de la gente de teatro. Conversaciones banales en la vida de gente común con sustrato mordaz, el teatro como metáfora de la vida y su ausencia de respuestas, la alerta del fascismo enraizado, sinuoso, entre nosotros, dentro de nosotros.`,
    review: `Una temática interesante, pero sin mucho más que decir. De todas formas, sirve para reflexionar sobre diversas temáticas como puede ser el autoritarismo y las secuelas del nazismo, aplicable a cualquier régimen autoritario`,
    genres: ["Comedia Nacional", "Sala Verdi", "2022"],
    favourite: false,
    score: 7,
  },
  {
    id: 1000000000014,
    name: "Cuando deje de llover",
    author: "Andrew Bovell / Fernando Toja",
    plot: `La obra nos cuenta la historia de cuatro generaciones de una misma familia donde se repiten una serie de patrones sin que ellos sean conscientes de ello. A través de mostrarnos el presente y el pasado vamos conociendo la historia de una forma no lineal. Una historia contada como un puzzle en el que al final todo encaja
    “Cuando deje de llover”  es un potente drama que viaja al corazón de los lazos familiares y a la esencia misma de su naturaleza, contado desde la empatía hacia el ser humano y su complejidad, con sorprendentes toques de humor, poesía y esperanza.`,
    review: `Muy buena obra en la que uno va uniendo las escenas como un rompecabezas para armar un panorama global de los acontecimientos. 4 generaciones de una familia que repiten los mismo errores o comportamientos. Estos comportamientos repetidos se encuentran representados por la constante lluvia que acompaña la vida de estas cuatro generaciones. Finalmente, este ciclo de comportamientos repetidos logra romperse y vislumbramos la posibilidad de un cambio, el cual viene acompañado con el fin de la lluvia.`,
    genres: ["Comedia Nacional", "Teatro Solis", "2021"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000000002,
    name: "",
    author: "",
    plot: ``,
    review: ``,
    genres: ["Comedia Nacional", "Sala Verdi", "2022 y 2023"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000000002,
    name: "",
    author: "",
    plot: ``,
    review: ``,
    genres: ["Comedia Nacional", "Sala Verdi", "2022 y 2023"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000000002,
    name: "",
    author: "",
    plot: ``,
    review: ``,
    genres: ["Comedia Nacional", "Sala Verdi", "2022 y 2023"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000000002,
    name: "",
    author: "",
    plot: ``,
    review: ``,
    genres: ["Comedia Nacional", "Sala Verdi", "2022 y 2023"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000000002,
    name: "",
    author: "",
    plot: ``,
    review: ``,
    genres: ["Comedia Nacional", "Sala Verdi", "2022 y 2023"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000000002,
    name: "",
    author: "",
    plot: ``,
    review: ``,
    genres: ["Comedia Nacional", "Sala Verdi", "2022 y 2023"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000000002,
    name: "",
    author: "",
    plot: ``,
    review: ``,
    genres: ["Comedia Nacional", "Sala Verdi", "2022 y 2023"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000000002,
    name: "",
    author: "",
    plot: ``,
    review: ``,
    genres: ["Comedia Nacional", "Sala Verdi", "2022 y 2023"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000000002,
    name: "",
    author: "",
    plot: ``,
    review: ``,
    genres: ["Comedia Nacional", "Sala Verdi", "2022 y 2023"],
    favourite: true,
    score: 9,
  },
];

export default completedPlays;
