// All Ids start at 10000000001
let completedBooks = [
  {
    id: 10000000001,
    name: "El fantasma de Stalin",
    author: "Martin Cruz Smith",
    plot: `Arkady Renko vuelve a trabajar como detective de la policía de Moscú. Mientras investiga unos asesinatos que podrían implicar a dos de los detectives más prestigiosos de Moscú: Isakov y Urman, Arkadi es enviado a investigar la supuesta aparición del fantasma de Stalin en el metro, caso en el que al parecer también estarían implicados Isakov y Urman. En el escenario de estas apariciones Arkady encuentra a un hombre, asesinado por una mujer, que en el momento de los hechos está borracha y que repite sin cesar «me han quitado el dragón». Tras estas apariciones misteriosas Arkadi descubre que están conectadas con un partido político (del que Isakov es militante) y que esconden datos de lo que realmente pasó en Chechenia. Renko descubre secretos que se remontan a la segunda guerra mundial.`,
    review: ``,
    genres: ["Fantasía", "Novela"],
    favourite: true,
    score: 6,
  },
  {
    id: 10000000002,
    name: "Filosofía en once frases",
    author: "Darío Sztajnszrajber",
    plot: `Sólo sé que no sé nada. Pienso, luego existo. Todo lo sólido se desvanece en el aire. Dios ha muerto. Por medio de frases como esas, disparadores que estimulan el pensamiento, Darío Sztajnszrajber se propone sacar a la filosofía de los formatos que la hacen excluyente. Al hacerlo nos lleva a una conversación alucinada y alucinante con once ideas clásicas, tan pequeñas como para caber en un tuit y a la vez tan interminables como las búsquedas existenciales.`,
    review: ``,
    genres: ["Ensayo", "Filosofía"],
    favourite: false,
    score: 8,
  },
  {
    id: 10000000003,
    name: "Al final mueren los dos",
    author: "Adam Silvera",
    plot: `Una historia sobre la vida, la amistad y el amor. ¿Puede un solo día albergar toda una vida?En un presente alternativo, en el que es posible predecir la muerte con un plazo de veinticuatro horas, Mateo Torrez y Rufus Emeterio acaban de recibir la llamada más temida: la misma que te avisa de que ha llegado tu hora final. En circunstancias normales, es poco probable que Mateo y Rufus se hubieran conocido. Pero sus circunstancias no son normales en absoluto. Porque les quedan, a lo sumo, veinticuatro horas de vida. Y han decidido recurrir a Último Amigo, la aplicación de citas que te permite contactar con alguien dispuesto a compartir tu carga. Mateo y Rufus tienen un día, puede que menos, para disfrutar de su recién nacida amistad. Para descubrir cuán frágiles y preciosos son los hilos que nos unen. Para mostrar al mundo su verdadero yo.La nueva novela de Adam Silvera, un superventas del New York Times que ha cosechado un éxito arrollador por parte de la crítica y los lectores. Un libro emotivo, original y extremo, que aborda la cercanía de la muerte para plasmar magistralmente la fuerza arrolladora de la vida, la amistad y el amor.`,
    review: ``,
    genres: ["Juvenil", "Drama", "Romance", "Novela"],
    favourite: true,
    score: 9,
  },
  {
    id: 10000000004,
    name: "Los mitos de Cthulhu",
    author: "H.P. Lovecraft",
    plot: `Howard Phillips Lovecraft ha ejercido una influencia inconmensurable sobre el género de terror del siglo XX, convirtiéndose en un autor de culto. ¿Quién no ha oído hablar de Cthulhu, Nyarlathotep o el infame Necronomicón? Los Mitos de Cthulhu, ciclo de narraciones de horror cósmico, a medio camino entre lo mítico, lo literario y lo religioso, la imaginería desatada y desasosegante de Lovecraft son pródigos en criaturas primigenias que aguardan el momento propicio para darse a conocer. Ellas nos traerán el terror en estado puro.`,
    review: ``,
    genres: ["Terror", "Fantasía"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000005,
    name: "Hijos de hombres",
    author: "James P.D.",
    plot: `Theo Faron es uno de los habitantes de la Inglaterra post-Omega (posterior a 1995, año Omega), un período en que los seres humanos han dejado de ser fértiles. No hay futuro para la humanidad y, resignado, Faron empieza a escribir su diario, donde relata la sordidez de una sociedad en decadencia y el orden que pretende imponer su primo, el temible dictador de Inglaterra conocido como el Guardián. Sin embargo, todo cambia el día en que un grupo de cinco jóvenes revolucionarios se propone desafiar al gobierno totalitario del Guardián.`,
    review: ``,
    genres: ["Distópico", "Novela"],
    favourite: false,
    score: 8,
  },
  {
    id: 10000000006,
    name: "La riqueza de las naciones",
    author: "Adam Smith",
    plot: `Considerado fundador de la ciencia económica por "La riqueza de las naciones", el escocés Adam Smith (1723-1790) no sólo puso con esta obra los cimientos de una ciencia, sino también de una doctrina: el liberalismo económico. La idea de que la riqueza proviene del trabajo (y no del oro ni de la plata), siendo susceptible de aumentar con una adecuada regulación del funcionamiento del mercado; la noción de la competencia como mecanismo limitador de la sed de beneficios y fomentador del bien común, y el deseo de un Estado fuerte, aunque no grande, que garantice la libertad, la propiedad y el funcionamiento de la "mano invisible" que armoniza los intereses de la persona y de la comunidad, son, en efecto, su perdurable aportación al mundo que se había de desarrollar en los siglos siguientes.`,
    review: ``,
    genres: ["Ciencia", "Ensayo"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000007,
    name: "Manifiesto del partido Comunista",
    author: "Karl Marx y Friedrich Engels",
    plot: `1848 se conoce como el Año de las Revoluciones por las revueltas que surgieron en distintos países en favor de formas de gobierno más liberales. Todas estallaron coincidiendo con la aparición de este Manifiesto del Partido Comunista, un texto que se convertiría en uno de los más influyentes de la historia contemporánea: apenas un siglo despues de su publicación, casi la mitad de la población mundial vivía bajo un regimen marxista. Hoy la obra está sujeta, claro está, a su posicionamiento ideológico pero sigue representando un momento clave del pensamiento político y Karl Marx, el principal responsable de su redacción, continúa siendo uno de los pensadores más influyentes de su tiempo. Muchos de los problemas que se abordan en estas páginas aún no han sido resueltos y, en cambio, algunas de las soluciones planteadas forman parte de cualquier sociedad actual que se tenga por civilizada.`,
    review: ``,
    genres: ["Ensayo"],
    favourite: true,
    score: 9,
  },
  {
    id: 10000000008,
    name: "El lobo estepario",
    author: "Hermann Hesse",
    plot: `Hermann Hesse traza en esta novela, más allá de la trama misma, un cuadro apasionante del proceso que vive su protagonista -"Harry, llamado el Lobo Estepario"- en pugna con su propia personalidad y su conciencia. "El lobo estepario era en parte un grito de angustia y advertencia contra la guerra", dijo Hesse. Pero es además, un grito de angustia y advertencia a todos los seres que, desconociendo el origen de sus más intimas motivaciones, se ven inmersos en sus propias atrocidades.`,
    review: ``,
    genres: ["Fantasía", "Novela"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000009,
    name: "Explicar el mundo",
    author: "Steven Weinberg",
    plot: `En esta historia de la ciencia, tan irreverente como ambiciosa, Steven  Weinberg nos conduce a través de los siglos desde la antigua Mileto  hasta el Bagdad medieval y Oxford, desde la Academia de Platón y el  Museo de Alejandría hasta la escuela de la Catedral de Chartres y la  Sociedad Real de Londres. El autor nos traslada a la mente de los  científicos de la Antigüedad y la Edad Media para mostrarnos cómo ellos  no solo no entendían lo que nosotros ya entendemos del mundo; en realidad, tampoco sabían qué era lo que había que entender, ni por supuesto cómo entenderlo.
    Sin embargo, a raíz de la lucha por resolver misterios tales como el  curioso movimiento de los planetas y la subida y bajada de las  mareas,  finalmente emergió la disciplina de la ciencia moderna, con sus  objetivos y sus métodos. Weinberg examina los enfrentamientos y las  colaboraciones que, a lo largo de ese tortuoso pero fascinante camino se  dieron entre la ciencia histórica y esferas competencia de la religión, la tecnología, las matemáticas, la filosofía y la poesía.`,
    review: ``,
    genres: ["Ensayo", "Ciencia"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000010,
    name: "El Bosque Oscuro",
    author: "Liu Cixin",
    plot: `Ahora la Tierra tiene cuatro siglos para defenderse de lo inevitable: la llegada de los Trisolaris. Los colaboracionistas humanos pueden haber sido derrotados, pero los sofones permiten a los extraterrestres acceder a la información de la humanidad, dejando al descubierto toda estrategia de defensa.
    Solo la mente humana sigue siendo un secreto, y ahora también la clave del acuciante plan que urdirán tres estadistas, un científico y un sociólogo.`,
    review: ``,
    genres: ["Ciencia Ficción", "Novela"],
    favourite: true,
    score: 10,
  },
  {
    id: 10000000011,
    name: "El problema de los tres cuerpos",
    author: "Liu Cixin",
    plot: `El problema de los Tres Cuerpos, empieza en el contexto de la Revolución Cultural china, cuando un proyecto militar secreto envía señales al espacio para contactar con extraterrestres. Pronto, una civilización alienígena al borde de la destrucción capta la señal y comienza a planear su desembarco en la Tierra. Durante las décadas siguientes, se comunica a través de un insólito método: un extraño videojuego virtual impregnado de historia y filosofía. Pero a medida que los alienígenas empiezan a ganar a los jugadores terrícolas, se forman distintos bandos, unos dispuestos a dar la bienvenida a esos seres superiores y ayudarlos a hacerse cargo de un mundo tan corrupto, y otros preparados para luchar contra la invasión. El resultado es una experiencia tan auténtica como reveladora sobre nuestro tiempo.`,
    review: ``,
    genres: ["Ciencia Ficción", "Novela"],
    favourite: true,
    score: 10,
  },
  {
    id: 10000000012,
    name: "El Fin de la muerte",
    author: "Liu Cixin",
    plot: `Ha pasado medio siglo de la batalla del Día del Juicio Final y la Tierra goza de una prosperidad sin precedentes gracias al conocimiento transferido por Trisolaris. Mientras la ciencia humana avance y los trisolarianos adopten la cultura terrícola, ambas civilizaciones podrán convivir sin temor a ser destruidas. Pero con la paz la humanidad se ha vuelto autocomplaciente. Después de una larga hibernación, Cheng Xin, una ingeniera aeroespacial de comienzos del siglo XX, despierta en esta nueva era. Su mera presencia, sumada a cierta información sobre un proyecto olvidado desde el principio de la Crisis Trisolariana, podría alterar el frágil equilibrio entre ambos mundos... ¿Alcanzará el ser humano las estrellas, o morirá en su cuna?`,
    review: ``,
    genres: ["Ciencia Ficción", "Novela"],
    favourite: true,
    score: 10,
  },
  {
    id: 10000000013,
    name: "Kafka en la orilla",
    author: "Haruki Murakami",
    plot: `Kafka Tamura se va de casa el día en que cumple quince años. Los motivos, si es que los hay, son las malas relaciones con su padre –un famoso escultor convencido de que su hijo repetirá el aciago sino del Edipo de la tragedia clásica– y la sensación de vacío producida por la ausencia de su madre y su hermana, que se marcharon también cuando él era muy pequeño. Sus pasos le llevarán al sur del país, a Takamatsu, donde encontrará refugio en una peculiar biblioteca y conocerá a la misteriosa señora Saeki. Si sobre la vida de Kafka se cierne la tragedia (en el sentido clásico), sobre la de Satoru Nakata ya se ha abatido: de niño, durante la segunda guerra mundial, sufrió un extraño accidente del que salió con secuelas, sumido en una especie de olvido de sí, con dificultades para comunicarse... salvo con los gatos. A los sesenta años abandona Tokio y emprende un viaje que le conducirá también a la biblioteca de Takamatsu. Así, las vidas y destinos de los personajes se van entretejiendo en un curso inexorable que no atiende a razones ni voluntades. Pero, a veces, hasta los oráculos se equivocan.`,
    review: ``,
    genres: ["Fantasía", "Novela"],
    favourite: false,
    score: 5,
  },
  {
    id: 10000000014,
    name: "La caída de los gigantes",
    author: "Kenn Follett",
    plot: `La historia empieza en 1911, el día de la coronación del rey Jorge V en la abadía de Westminster. El destino de los Williams, una familia minera de Gales, está unido por el amor y la enemistad al de los Fitzherbert, aristócratas y propietarios de las minas. Lady Maud Fitzherbert se enamorará de Walter von Ulrich, un joven espía en la embajada alemana en Londres. Sus vidas se entrelazarán con la de un asesor progresista del presidente de los Estados Unidos, Woodrow Wilson, y la de dos hermanos rusos a los que la guerra y la revolución les han arrebatado el sueño de buscar fortuna en América. Desde Washington hasta San Petersburgo, desde la inmundicia y los peligros de las minas de carbón hasta los candelabros lujosos de los palacios de la aristocracia, pasando por los pasillos de la Casa Blanca y el parlamento de Westminster, Ken Follett nos ofrece aquí, en su novela más ambiciosa, un esmerado retrato de una época y de las pasiones que atravesaron la vida de sus personajes`,
    review: ``,
    genres: ["Novela Histórica", "Novela", "Ficción"],
    favourite: true,
    score: 8,
  },
  {
    id: 10000000015,
    name: "Dune",
    author: "Frank Herbert",
    plot: `Crónicas de Dune 1 Una obra maestra unánimemente reconocida como la mejor saga de ciencia ficción de todos los tiempos Arrakis: un planeta desértico donde el agua es el bien más preciado, donde llorar a los muertos es el símbolo de máxima prodigalidad. Paul Atreides: un adolescente marcado por un destino singular, dotado de extraños poderes, abocado a convertirse en dictador, mesías y mártir. Los Harkonnen: personificación de las intrigas que rodean el Imperio Galáctico, buscan obtener el control sobre Arrakis para disponer de la melange, preciosa especia y uno de los bienes más codiciados del universo. Los Fremen: seres libres que han convertido el inhóspito paraje de Dune en su hogar, y que se sienten orgullosos de su pasado y temerosos de su futuro. Dune: una obra maestra unánimemente reconocida como la mejor saga de ciencia ficción de todos los tiempos.`,
    review: ``,
    genres: ["Ciencia ficción", "Novela"],
    favourite: true,
    score: 9,
  },
  {
    id: 10000000016,
    name: "El mesías de Dune",
    author: "Frank Herbert",
    plot: `Arrakis, también llamado Dune: un mundo desierto en pos del sueño de convertirse en un paraíso, cuna de mil guerras que se han extendido por todo el universo y de un anhelo mesiánico que intenta alcanzar el sueño más antiguo de la humanidad...
    Paul Atreides: un personaje mítico, perturbado por la cercana presencia de una sombra dominante: su hermana Alia. Y frente a ellos, los grandes intereses económicos, políticos y religiosos que sacuden los espacios interestelares: la CHOAM, la Cofradía espacial, el Landsraad, la Bene Gesserit...`,
    review: ``,
    genres: ["Ciencia ficción", "Novela"],
    favourite: false,
    score: 8,
  },
  {
    id: 10000000017,
    name: "Fahrenheit 451",
    author: "Ray Bradbury",
    plot: `Fahrenheit 451 cuenta la historia de un sombrío y horroroso futuro. Montag, el protagonista, pertenece a una extraña brigada de bomberos cuya misión, paradójicamente, no es la de sofocar incendios, sino la de provocarlos para quemar libros. Porque en el país de Montag está terminantemente prohibido leer. Porque leer obliga a pensar, y en el país de Montag está prohibido pensar. Porque leer impide ser ingenuamente feliz, y en el país de Montag hay que ser feliz a la fuerza...`,
    review: ``,
    genres: ["Ciencia ficción", "Distópico", "Novela"],
    favourite: true,
    score: 8,
  },
  {
    id: 10000000018,
    name: "Un mundo feliz",
    author: "Aldous Huxley",
    plot: `La novela describe un mundo en el que finalmente se han cumplido los peores vaticinios: triunfan los dioses del consumo y la comodidad, y el orbe se organiza en diez zonas en apariencia seguras y estables. Sin embargo, este mundo ha sacrificado valores humanos esenciales, y sus habitantes son procreados in vitro a imagen y semejanza de una cadena de montaje. Muchas de las previsiones de Huxley se han materializado acelerada e inquietantemente en los últimos años.`,
    review: ``,
    genres: ["Ciencia ficción", "Distópico", "Novela"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000019,
    name: "1984",
    author: "George Orwell",
    plot: `Londres, 1984: Winston Smith decide rebelarse ante un gobierno totalitario que controla cada uno de los movimientos de sus ciudadanos y castiga incluso a aquellos que delinquen con el pensamiento. Consciente de las terribles consecuencias que puede acarrear la disidencia, Winston se une a la ambigua Hermandad por mediación del líder O’'Brien. Paulatinamente, sin embargo, nuestro protagonista va comprendiendo que ni la Hermandad ni O'’Brien son lo que aparentan, y que la rebelión, al cabo, quizá sea un objetivo inalcanzable. Por su magnífico análisis del poder y de las relaciones y dependencias que crea en los individuos, 1984 es una de las novelas más inquietantes y atractivas`,
    review: ``,
    genres: ["Ciencia ficción", "Distópico", "Novela"],
    favourite: true,
    score: 10,
  },
  {
    id: 10000000020,
    name: "El hombre ilustrado",
    author: "Ray Bradbury",
    plot: `En esta colección de historias entrelazadas, el narrador anónimo conoce a El Hombre Ilustrado, un curioso personaje con el cuerpo completamente cubierto de tatuajes. Sin embargo, lo más remarcable e inquietante es que las ilustraciones están mágicamente vivas y cada una de ellas empieza a desarrollar su propia historia, como en La pradera donde unos niños llegan un juego de realidad virtual más allá de sus límites. O en «Calidoscopio», el sobrecogedor relato de un astronauta que se dispone a reentrar en la atmósfera terrestre sin la protección de una nave espacial. O en La hora cero, en el que los invasores extraterrestres han encontrado unos aliados lógicos y sorprendentes: los niños humanos.`,
    review: ``,
    genres: ["Ciencia ficción"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000021,
    name: "Rojo y Negro",
    author: "Stendhal",
    plot: `Rojo y negro es una de las novelas clave de Stendhal, el seudónimo con el que el francés Henri Beyle pasó a la historia de la literatura como una de las grandes plumas del realismo psicológico. Julien Sorel, el protagonista, encarna como ningún otro las contradicciones de la Francia de la Restauración, un período convulso y fascinante del que Stendhal nos ofrece un retrato casi fotográfico`,
    review: ``,
    genres: ["Novela Realista", "Novela"],
    favourite: false,
    score: 8,
  },
  {
    id: 10000000022,
    name: "La Cartuja de Parma",
    author: "Stendhal",
    plot: `La Cartuja de Parma es una novela excepcional, una novela avanzada a su tiempo, en la que muchos han visto lo que podría ser el testamento espiritual de un autor único, adorado por Calvino y Lampedusa, y en la que aparecen íntimamente imbricados sus anhelos, sus ensueños, la cristalización amorosa, los bellos paisajes, Napoleón, Italia.
    Hijo menor de una familia aristocrática italiana, Fabricio del Dongo, fascinado por Napoleón, sueña con reunirse con él en Waterloo, justo en el momento en que da comienzo la batalla. Sin embargo, concluida la gesta napoleónica, nuestro joven héroe no seguirá la carrera de las armas a la que aspiraba, sino que consentirá en ser prelado, con bastante desenfado, puesto que su objetivo esencial continuará siendo la caza de la felicidad, o sea, el amor.`,
    review: ``,
    genres: ["Novela Realista", "Novela"],
    favourite: false,
    score: 8,
  },
  {
    id: 10000000023,
    name: "Anna Karenina",
    author: "Lev Tolstoi",
    plot: `Anna Karenina es, junto con la monumental Guerra y paz, una de las obras clave Lev Tolstoi, en la que vemos todas las señas de identidad del gran realismo ruso: fina crítica social y multitud de personajes con una profundidad psicológica asombrosa. Las desventuras de Anna Karenina y su afán por integrarse en una sociedad hipócrita que la margina por adúltera, pero perdona los desmanes de su amante, nos hacen reflexionar sobre la invisibilización de la mujer a la par que nos ofrecen un fresco monumental de la Rusia decimonónica y todas sus contradicciones.`,
    review: ``,
    genres: ["Novela Realista", "Novela"],
    favourite: false,
    score: 6,
  },
  {
    id: 10000000024,
    name: "Papá Goriot",
    author: "Honoré de Balzac",
    plot: `Papá Goriot es una novela del escritor francés Honoré de Balzac escrita en 1834 para la Revue de Paris y publicada en 1835 en forma de libro. Considerada una de las obras más importantes del autor, forma parte de las Escenas de la vida privada de la Comedia humana. En ella se analiza la naturaleza de la familia, el matrimonio, la estratificación y la corrupción en la sociedad parisina durante la Restauración francesa a partir del drama vivido por personajes como papá Goriot -el hombre que muere en la miseria y rechazado por sus hijas luego de haber sacrificado todo por ellas-, Eugène Rastignac -el joven cándido y ambicioso que aspira a formar parte de la alta sociedad-, los otros pensionistas en la Casa Vauquer y damas de la alta sociedad como la señora de Bauseánt o las hijas de Goriot.`,
    review: ``,
    genres: ["Novela Realista", "Novela"],
    favourite: true,
    score: 10,
  },
  {
    id: 10000000025,
    name: "Eugenia Grandet",
    author: "Honoré de Balzac",
    plot: `Dentro de esa catedral narrativa que es la Comedia humana, la novela Eugenia Grandet ocupa un lugar especial por los dos grandes caracteres que en ella crea Balzac: el de una joven que descubre por primera vez el amor y entrega como arras cuanto tiene para ayudar a su enamorado, y el de su padre, el tío Grandet, la más acabada de las encarnaciones de avaro desde la obra de ese título de Moliere. El amor paternal será abolido por la avaricia de un Grandet que, en el último momento de su vida, amenaza a su hija con pedirle cuentas de la herencia cuando Eugenia llegue al otro mundo. Al lado de estos dos potentes retratos, Charles, el joven parisino criado entre el lujo y la ociosidad, sólo sirve para poner de relieve la realidad de la vida cotidiana, la potencia del amor de Eugenia y los extremos a que puede llegar la avaricia. Eugenia Grandet, aunque forma parte de la Comedia humana, es una capilla aislada de esa catedral narrativa: cerrada sobre sí misma, el acierto en el análisis de esos dos caracteres y la descripción del medio social en que se desenvuelven la han convertido en al novela más conocida de Balzac.`,
    review: ``,
    genres: ["Novela Realista", "Novela"],
    favourite: true,
    score: 9,
  },
  {
    id: 10000000026,
    name: "A sangre fría",
    author: "Truman Capote",
    plot: `El 15 de noviembre de 1959, en un pueblecito de Kansas, los cuatro miembros de la familia Clutter fueron salvajemente asesinados en su casa. Los crímenes eran aparentemente inmotivados, y no se encontraron claves que permitieran identificar a los asesinos. Cinco años, cuatro meses y veintinueve días más tarde, el 14 de abril de 1965, Dick Hickcock y Perry Smith fueron ahorcados como culpables de las muertes en la penitenciaría del estado de Kansas.`,
    review: ``,
    genres: ["Ficción", "Novela"],
    favourite: false,
    score: 5,
  },
  {
    id: 10000000027,
    name: "2001: Una odisea espacial",
    author: "Arthur C. Clark",
    plot: `Los doctores David Bowman y Frank Poole se encuentran a bordo del Discovery One con el objetivo de realizar una expedición a los confines del universo en busca de evidencias que confirmen que el ser humano no está solo. Les acompañan tres científicos en animación suspendida y HAL 9000, un ordenador excepcionalmente inteligente. Pero la misión se vuelve muy peligrosa cuando HAL empieza a fallar. ¿Se trata de un problema técnico? ¿O quizá Hal tiene voluntad propia? ¿Qué influencia ejerce el monolito? Con estas preguntas, surgen otras: ¿Cuál es nuestra esencia? ¿Qué lugar ocupamos en el cosmos?`,
    review: ``,
    genres: ["Ciencia Ficción", "Novela"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000028,
    name: "2010: Odisea dos",
    author: "Arthur C. Clark",
    plot: `Nueve años despues de la desastrosa misión Discovery a Júpiter en 2001,  una nueva expedición formada por estadounidenses y rusos parte para  encontrar la nave perdida y buscar en el banco de datos del rebelde  ordenador HAL 9000 algo que explique que ocurrió y dónde está el  comandante Bowman. Mientras tanto, el ser que fue una vez Dave Bowman  -el único humano que podía dar la clave sobre el misterio del monolito- se dirige hacia la Tierra en una misión vital...`,
    review: ``,
    genres: ["Ciencia Ficción", "Novela"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000029,
    name: "Anochecer",
    author: "Isaac Asimov",
    plot: `El planeta Kalgash está al borde del caos, pero solo unas pocas personas se han dado cuenta de ello. Kalgash conoce únicamente la luz diurna perpetua, pues durante más de dos milenios la combinación de sus seis soles ha iluminado el cielo. Sin embargo, ahora empieza a reinar la oscuridad.
    Pronto se pondrán todos los soles, y el terrible esplendor del anochecer desencadenará una locura que marcará el final de la civilización.`,
    review: ``,
    genres: ["Ciencia Ficción", "Novela"],
    favourite: false,
    score: 8,
  },
  {
    id: 10000000030,
    name: "El viejo y el mar",
    author: "Ernest Hemingway",
    plot: `En un pequeño pueblo costero, un viejo pescador hace ya mucho tiempo que intenta, en vano, capturar un enorme pez. Un día se hace a la mar y, tras mucho esfuerzo, consigue que éste pique su cebo. Pero una colosal lucha contra los hambrientos tiburones que pretenden devorarlo descubre al anciano la admiración que siente por ese pez que ha sido su mayor desafío.`,
    review: `Una muestra del espíritu humano`,
    genres: ["Novela"],
    favourite: false,
    score: 8,
  },
  {
    id: 10000000031,
    name: "Bajo las ruedas",
    author: "Hermann Hesse",
    plot: `Publicada en 1906, "Bajo las ruedas" es una prodigiosa recreación del mundo de la adolescencia, pero en ella Hermann Hesse (1877-1962) formula también una severa acusación contra los sistemas educativos que se imponen a costa de la imaginación y del cultivo armónico de las facultades espirituales, emocionales y físicas. Separado del medio de su infancia y obligado por padres y profesores a una agotadora preparación para el ingreso en un seminario, su protagonista, Hans Giebenrath, logra finalmente su objetivo, pero al elevado precio de perder primero su sensibilidad y, más tarde, su equilibrio emocional.`,
    review: `Vigente hasta el día de hoy. Un sistema educativo que a la vez nos abre puertas y nos destruye como individuos, un reflejo del mundo en el que vivimos. Es un libro excelente y muy recomendado para todo el mundo. `,
    genres: ["Novela", "Ficción"],
    favourite: true,
    score: 10,
  },
  {
    id: 10000000032,
    name: "Demian",
    author: "Hermann Hesse",
    plot: `El que quiere nacer tiene que destruir un mundo, responde Demian a dolorosa llamada de Emil Sinclair, el protagonista de esta obra de formación que crece ante los ojos del lector descubriendo su auténtico yo a través del rechazo de lo preestablecido. Tal es la significación de este libro: destrucción de un mundo, superación de una moral en favor de una poderosa vida interior reprimida, liberación definitiva de una herencia, una educación y un pasado.`,
    review: ``,
    genres: ["Ficción", "Novela"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000033,
    name: "Peter Camenzind",
    author: "Hermann Hesse",
    plot: `Publicada en 1904, Peter Camenzind fue la primera novela de Hermann Hesse (1877-1962) y conoció de inmediato un gran éxito. En ella encontramos ya en germen las principales señas de identidad del autor y de su obra posterior: el descontento íntimo o la turbación interior, el ansia de trascendencia y de plenitud (que toma aquí como vía a San Francisco de Asís y que más tarde habría de plasmarse en obras como Siddhartha), la comunión con la naturaleza enfrentada a la artificialidad de las relaciones sociales, la persecución por veces desesperada de una respuesta al sentido de la vida... Genuino representante del malestar que acompañó al alumbramiento del siglo XX, lo que hace de Hesse un escritor plenamente actual es su conciencia de ese malestar y su constante afán de búsqueda de la faceta espiritual del hombre en un mundo cada vez más alejado de ella.`,
    review: ``,
    genres: ["Ficción", "Novela"],
    favourite: false,
    score: 8,
  },
  {
    id: 10000000034,
    name: "La tregua",
    author: "Mario Benedetti",
    plot: `Publicada en 1960, La tregua es la obra de Mario Benedetti que ha alcanzado mayor éxito de público. La cotidianidad gris y rutinaria, marcada por la frustración y la ausencia de perspectivas de la clase media urbana, impregna las páginas de esta novela, que, adoptando la forma de un diario personal, relata un breve período de la vida de un empleado viudo, próximo a la jubilación, cuya existencia se divide entre la o?cina, la casa, el café y una precaria vida familiar dominada por una difícil relación con unos hijos ya adultos. Una inesperada relación amorosa, que parece ofrecer al protagonista un horizonte de liberación y felicidad personal, queda trágicamente interrumpida y será tan sólo un inciso -una tregua- en su lucha cotidiana contra el tedio, la soledad y el paso implacable del tiempo.`,
    review: ``,
    genres: ["Ficción", "Novela"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000035,
    name: "La borra de café",
    author: "Mario Benedetti",
    plot: `Novela inolvidable, donde el humor y el amor a los seres humanos se convierte en reflejo de nosotros mismos. La borra del café consta de cuarenta y ocho fragmentos y un enigma desarrollado en la imagen misteriosa de una mujer, la presencia de una higuera y la reiteración a lo largo de los años de una hora, las tres y diez. Benedetti rescata, en un espacio de ensueño, las anécdotas que acompañaron a Claudio, el protagonista, durante su niñez en Montevideo. Los juegos infantiles, la ceguera de su amigo Mateo, la inesperada muerte de su madre, el traslado a otro barrio, la nueva boda de su padre, su propio descubrimiento del amor y del sexo. Las diferentes ceremonias de las despedidas son retratadas aquí, con maestría inigualable, por el escritor uruguayo.`,
    review: ``,
    genres: ["Ficción", "Novela"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000036,
    name: "El invierno del mundo",
    author: "Ken Follet",
    plot: `Los hijos de las cinco familias protagonistas de La caída de los gigantes forjarán su destino en los años turbulentos de la Segunda Guerra Mundial, la guerra civil española, el bombardeo de Pearl Harbor y la era de la bomba atómica.`,
    review: `Está bueno, pero no me pareció tan interesante como la caída de los gigantes`,
    genres: ["Novela Histórica", "Novela", "Ficción"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000037,
    name: "Los pilares de la Tierra",
    author: "Ken Follet",
    plot: `El gran maestro de la narrativa de acción y suspense nos transporta a la Edad Media, a un fascinante mundo de reyes, damas, caballeros, pugnas feudales, castillos y ciudades amuralladas. El amor y la muerte se entrecruzan vibrantemente en este magistral tapiz cuyo centro es la construcción de una catedral gótica. La historia se inicia con el ahorcamiento público de un inocente y finaliza con la humillación de un rey.`,
    review: ``,
    genres: ["Novela Histórica", "Novela", "Ficción"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000038,
    name: "En nombre de todos los mios",
    author: "Martin Gray",
    plot: `En el libro el autor narra su experiencia siendo un joven judío en el gueto de Varsovia durante la ocupación nazi, sus vivencias en un campo de exterminio y también su vida después de la guerra, cuando emigró a Estados Unidos, donde vivía su abuela, y cambió su nombre original de Mieczyslaw Grajewski por Martin Gray. En EE.UU. se convirtió en vendedor de antigüedades y estableció una empresa de comercialización de reliquias con presencia en Estados Unidos, Cuba, Canadá y Europa. Antes de hacer las Américas, el escritor llegó a ser capitán del ejército soviético y participó en la batalla de Berlín, la última gran batalla en Europa de la Segunda Guerra Mundial. En 1960 se instaló en Tanneron, a las afueras de Cannes, y comenzó a escribir sus memorias, que no terminó hasta después de 1970, cuando su mujer y sus cuatro hijos fallecieron en un incendio forestal.`,
    review: ``,
    genres: ["Biografía"],
    favourite: false,
    score: 8,
  },
  {
    id: 10000000039,
    name: "Diario de Ana Frank",
    author: "Anna Frank",
    plot: `Ana Frank fue una niña judía que vivió escondida de los alemanes junto con su familia durante casi dos años y medio. En ese tiempo, se dedicó a escribir un diario en el que relató sus vivencias y sentimientos. Ana murió en un campo de concentración, pero su padre publicó el diario años más tarde y cumplió su sueño de convertirse en escritora. A día de hoy, es uno de los libros más leídos en todo el mundo`,
    review: ``,
    genres: ["Fantasía"],
    favourite: false,
    score: 10,
  },
  {
    id: 10000000040,
    name: "Diez Negritos",
    author: "Agatha Christie",
    plot: `Diez personas que no se han visto nunca son invitadas por un huésped desconocido a pasar unos días de vacaciones en una lujosa mansión situada en una isla de la costa inglesa. Cada uno de los invitados tiene algo que esconder, y un crimen por el que debe pagar. Empieza la pesadilla.`,
    review: `De los primeros libros con los que me fui introduciendo a la lectura, sin duda alguna te atrapa enseguida.`,
    genres: ["Policiaco", "Drama", "Misterio"],
    favourite: false,
    score: 7,
  },
  {
    id: 10000000041,
    name: "Asesinato en el Orient Express",
    author: "Agatha Christie",
    plot: `La novela más popular del mítico detective Hércules Poirot.
    En un lugar aislado de la antigua Yugoslavia, en plena madrugada, una fuerte tormenta de nieve obstaculiza la línea férrea por donde circula el Orient Express. Procedente de la exótica Estambul, en él viaja el detective Hércules Poirot, que repentinamente se topa con uno de los casos más desconcertantes de su carrera: en el compartimiento vecino ha sido asesinado Samuel E. Ratchett mientras dormía, pese a que ningún indicio trasluce un móvil concreto. Poirot aprovechará la situación para indagar entre los ocupantes del vagón, que a todas luces deberían ser los únicos posibles autores del crimen.
    Una víctima, doce sospechosos y una mente privilegiada en busca de la verdad.`,
    review: `Excelente novela, uno queda atrapado por la intriga de averiguar realmente qué pasó`,
    genres: ["Policiaco", "Misterio"],
    favourite: false,
    score: 8,
  },
  {
    id: 10000000042,
    name: "Los propios dioses",
    author: "Isaac Asimov",
    plot: `Esta novela se divide en tres secciones ubicadas en diferentes tiempos y lugares, incluso en dos universos diferentes. La trama principal es una conspiración de alienígenas que habitan un universo paralelo moribundo, con el propósito de convertir el Sol en una supernova y poder colectar la energía resultante para su propio uso y continuidad de su forma de vida.

    Asimov declaró que la novela, sobre todo la segunda parte, fue su mejor obra jamás producida.`,
    review: ``,
    genres: ["Ciencia Ficción", "Novela"],
    favourite: true,
    score: 8,
  },
  {
    id: 10000000043,
    name: "Huesped",
    author: "Isaac Asimov",
    plot: `La historia trata de un médico alienígena quién visita la Tierra para investigar el hecho que únicamente los seres humanos dejan de crecer para luego morir a una edad avanzada. Su idea del porqué esto sucede es probada de una manera inesperada.`,
    review: `Un cuento excelente de Asimov. La historia da un giro que uno no se ve venir y cambia totalmente lo que uno se imaginaba`,
    genres: ["Cuento", "Ciencia Ficción"],
    favourite: true,
    score: 9,
  },
  {
    id: 10000000044,
    name: "La última pregunta",
    author: "Isaac Asimov",
    plot: `La historia narra cómo, a partir de un día común, dos individuos en una situación ordinaria formulan una pregunta singular a la poderosa computadora conocida como Multivac, el ordenador central que controla y dirige la actividad humana. Luego, a partir del evento, somos testigos de diversas etapas en la evolución de la especie humana, separadas por intervalos de tiempo que abarcan billones y trillones de años. En diferentes momentos históricos, la humanidad repite la misma pregunta a la computadora más potente de cada época. De esta manera, se nos relata la transformación del universo y de la humanidad, quienes intentan resolver la última pregunta: ¿es posible revertir el inevitable final del Universo, o el mundo debe acabar de todas formas?`,
    review: ``,
    genres: ["Cuento", "Ciencia Ficción"],
    favourite: true,
    score: 7,
  },
];

export default completedBooks;
