// Id start at 10000001
let pendingBooks = [
  {
    id: 10000001,
    name: "A hombros de gigantes",
    author: "Stephen Hawking",
    plot: "El gran científico Sephen Hawking ha sintetizado en este libro, espléndidamente ilustrado, las cinco obras que representan el canon de la cultura universal en el campo de la Física y la Astronomía: · Sobre las revoluciones de los orbes celestes, de Nicolás Copérnico · Diálogo sobre dos nuevas ciencias, de Galileo Galilei · Las armonías del mundo, de Johannes Kepler · Principios matemáticos de la filosofía natural, de Isaac Newton · El principio de la relatividad, de Albert Einstein. Hawking ha escrito una introducción a cada una de estas obras explicando lo que han significado para la ciencia, vinculándolas entre sí y ofreciéndonos cinco soberbios retratos de los genios que las escribieron.",
    genres: ["Ciencia", "Ensayo"],
  },
  {
    id: 10000002,
    name: "Quiérete mucho, maricón: Manual de éxito psicoemocional para hombres homosexuales",
    author: "Gabriel J. Martín",
    plot: "En Quiérete mucho, maricón el autor nos explica de manera rigurosamente científica cómo la homosexualidad es una más de todas las posibles manifestaciones de la diversidad sexoafectiva del ser humano y cómo, si superamos las secuelas que nos ha dejado la homofobia, puede vivirse de forma plena, asertiva y feliz.",
    genres: ["Ensayo"],
  },
  {
    id: 10000003,
    name: "Paradox 13",
    author: "Keigo Higashino",
    plot: "Debido al influjo sobre la Tierra de un agujero negro, el 13 de marzo, a las 13 horas 13 minutos y 13 segundos se producirá un fenómeno denominado P-13. Las medidas del gobierno para afrontarlo se estudian en el más absoluto secreto. Ni siquiera los científicos saben exactamente en qué consistirá dicho fenómeno y sus consecuencias: los departamentos que se ocupan del asunto se han limitado a señalar que es importante suspender por unos instantes toda actividad peligrosa, así como mantenerse alejado de los lugares de riesgo. Sin embargo, esta información se ha mantenido oculta con la idea de no alterar a la población, prohibiéndose su divulgación hasta que pase el fenómeno. Fuyuki Kuga, detective de la Jefatura de Policía de Tokio, y su hermano mayor, Seiya, inspector de policía adscrito a la misma Jefatura, se ocupan en esos momentos de un asunto de atraco a mano armada, pero, debido a un error de Fuyuki, Seiya resulta herido de bala por un miembro del grupo criminal al que persiguen. Por su parte, Fuyuki recibe también un balazo de los delincuentes y se desmaya. Cuando recobra el conocimiento, constata que no queda nadie en las calles de Tokio. Deambulando por la ciudad, sin comprender qué está pasando, encontrará a otras diez personas que han sufrido el mismo fenómeno. Entre ellas se halla también, inexplicablemente, su hermano Seiya, quien en buena lógica debería estar muerto. Incapaces de asimilar la situación, el grupo intenta sobrevivir vagando por un Tokio en ruinas, devastado por las catástrofes naturales y las enfermedades.",
    genres: ["Ciencia Ficción"],
  },
  {
    id: 10000004,
    name: "Yo, adolescente",
    author: "Zabo",
    plot: "Corre el año 2005 y tras el incendio de un local bailable llamado Cromañón, la vida nocturna y cultural de la ciudad de Buenos Aires cambia radicalmente, en especial para los menores de edad, que dejaron de ser bienvenidos hasta en los recitales de sus bandas favoritas. En este contexto y tras el suicidio de uno de sus mejores amigos, Zabo, un adolescente de dieciséis años, comienza a registrar durante un año todo lo que ocurre a su alrededor en los borradores de un blog. Sin poder entender la muerte de Pol, Zabo se sumerge en una depresión que niega y tapa con conflictos que él mismo genera.",
    genres: ["Juvenil", "Drama"],
  },
  {
    id: 10000005,
    name: "Los Chicos que juegan con fuego",
    author: "Iñigo Aguas",
    plot: `¿Estás preparado para jugar con fuego? La novela más explosiva de Íñigo Aguas 
    Nate tiene dos problemas. 
    Uno de ellos se llama Marc. Su compañero de teatro y del que depende su futuro como actor. Se llevan fatal, pero no pueden dejar de mirarse. El otro se llama Liam. Su mejor amigo desde la infancia, el chico más popular del instituto. Pero lo que antes parecía amistad, comienza a convertirse en algo más peligroso.`,
    genres: ["Juvenil", "Romance"],
  },
  {
    id: 10000006,
    name: "Yo, Robot",
    author: "Isaac Asimov",
    plot: "La vida de la robotpsicóloga Susan Calvin acompaña los avances de la industria robótica desde sus primeros intentos -los rudimentarios robots áfonos y los autómatas obreros- hasta sus logros más sofisticados: las máquinas que auxilian al hombre en el gobierno planetario. Desfila, a lo largo de estas páginas, un elenco singular de robots sorprendentemente humanos, quienes ajustan su conducta a las tres leyes de la robótica concebidas por Asimov. Estas normas, sin embargo, desencadenan múltiples conflictos. Así, encontramos a Cutie, el robot que desconoce la autoridad humana y venera al transformador de energía; o a Dave, guiando a sus subsidiarios en una siniestra marcha; o a Herbie, el robot telépata, más aficionado a las novelas sentimentales que a las matemáticas.",
    genres: ["Ciencia Ficción"],
  },
  {
    id: 10000007,
    name: "Lance",
    author: "Ronald L. Donaghe",
    plot: "Cuando Lance y Will se conocen en un risco azotado por el viento, al borde de una montaña del desierto, ninguno de los dos jóvenes imagina las dificultades a las que ambos tendrán que enfrentarse. Lance, sentirá el apoyo que jamás halló en su familia y descubrirá algo incluso más importante aún: el amor puro de un hombre... para siempre. Pero entonces deberá tomar una decisión terriblemente dolorosa: o se dedica a ese amor o aprovecha la oportunidad de su vida, lo que puede implicar, sin duda, la pérdida de ese amor.",
    genres: ["Juvenil", "Romance", "Drama"],
  },
  {
    id: 10000008,
    name: "Ciclos del tiempo",
    author: "Roger Penrose",
    plot: "La revolucionaria y exitosa obra de Roger Penrose El camino a la realidad presentaba una guía completa y comprensible de las leyes que rigen el universo desde nuestro conocimiento actual. En Ciclos del tiempo, su libro más ambicioso, Penrose va mucho más allá: desarrolla una visión inédita de la cosmología y propone una respuesta inesperada a la pregunta ¿Qué pasó antes del Big Bang?",
    genres: ["Ensayo", "Ciencia"],
  },
  {
    id: 10000009,
    name: "Fundación (Trilogía)",
    author: "Isaac Asimov",
    plot: "Una de las características más interesantes de la novela es que se trata de un futuro muy lejano, decenas de miles de años en el futuro pero con condiciones netamente humanas. En este futuro la humanidad se ha extendido por toda la Galaxia adoptando una forma de gobierno imperial llamado el Imperio Galáctico el cual por extensión, tanto en tiempo como en espacio, comienza a corromperse y estancarse en cuanto a nuevos conocimientos científicos asumiendo que todo lo que el hombre puede o debe descubrir ya está hecho. Básicamente la primera trilogía (Fundación - Fundación e Imperio - Segunda Fundación) trata sobre los resultados prácticos de la nueva ciencia llamada Psicohistoria desarrollada por Hari Seldon, el cual predice de manera matemática el fin del Imperio por su propia corrupción e inacción para seguir existiendo como tal y cómo ésta influye en curso de las acciones de determinados personajes que habrán de formar parte en el damero histórico cuya finalidad es la de llevar a un nuevo imperio después de la destrucción del primero. También muestra el origen del nuevo estado galáctico conocido como 'Fundación' destinado por sus avances tecnológicos a dominar toda la galaxia.",
    genres: ["Ciencia Ficción"],
  },
  {
    id: 10000010,
    name: "La sociedad del cansacio",
    author: "Byung Chul Han",
    plot: "Byung-Chul Han, una de las voces filosóficas más innovadoras que ha surgido en Alemania recientemente, afirma en este inesperado best seller que la sociedad occidental está sufriendo un silencioso cambio de paradigma: el exceso de positividad está conduciendo a una sociedad del cansancio. Según el autor, toda época tiene sus enfermedades emblemáticas. Así, hay una época bacterial que toca a su fin con la invención del antibiótico. A pesar del manifiesto miedo a la pandemia gripal, actualmente no vivimos en la época viral. La hemos dejado atrás gracias a la técnica inmunológica. El comienzo del siglo XXI, desde un punto de vista patológico, no sería ni bacterial ni viral, sino neuronal. La depresión, el trastorno por déficit de atención con hiperactividad (TDAH), el trastorno límite de la personalidad (TLP) o el síndrome de desgaste ocupacional (SDO) definen el panorama patológico de comienzos de este siglo. Estas enfermedades no son infecciones, sino estados patológicos que siguen a su vez una dialéctica, pero no una dialéctica de la negatividad, sino de la positividad, hasta el punto de que cabría atribuirles un exceso de esta última.",
    genres: ["Ensayo", "Filosofía"],
  },
  {
    id: 10000011,
    name: "El capital",
    author: "Karl Marx",
    plot: "El capital. Crítica de la economía política (en alemán, Das Kapital - Kritik der politischen Ökonomie), de Karl Marx es, como reza su subtítulo, un tratado de crítica de la economía política; al mismo tiempo, ha sido también leído como una obra de filosofía, como un tratado de economía, o como un tratado político sobre las relaciones de dominación entre las clases, de un lado los proletarios y de otro los burgueses.",
    genres: ["Ensayo"],
  },
  {
    id: 10000012,
    name: "La última reverencia de sherlock holmes",
    author: "Arthur Conan Doyle",
    plot: "Publicada en 1917, esta recopilación de historias de Sherlock Holmes se enfoca en aquellos relatos que vieron la luz entre 1908 y 1917 en la revista The Strand, como toda la obra previa y posterior de Arthur Conan Doyle sobre el famoso detective. Holmes disfruta de un merecido descanso, alejado del crimen y la intriga de Londres, mientras el Doctor Watson recuenta las aventuras que toman lugar en los últimos años de vida del detective. Otra dosis del infalible intelecto de Sherlock Holmes y de las aventuras que le convirtieron, junto al Doctor Watson, en un referente mundial de lo detectivesco y en el ejemplo inmortal de los poderes de deducción para resolver crímenes.",
    genres: ["Policiaco"],
  },
  {
    id: 10000013,
    name: "El anticristo",
    author: "Friedrich Nietzsche",
    plot: "Friedrich Nietzsche captó como ningún otro filósofo el mundo de finales del siglo XIX: colonialismo, industrialización, deshumanización... Cambios rápidos que también afectaron a la relación del hombre occidental con Dios. En el Anticristo, una de sus últimas obras arremete contra la moral con la que el cristianismo había corrompido a los europeos. Controvertida en su momento, es un magnífico ejemplo de la prosa directa y cautivadora del autor germano.",
    genres: ["Ensayo", "Filosofía"],
  },
  {
    id: 10000014,
    name: "Madame Bovary",
    author: "Gustave Flaubert",
    plot: "Considerada unánimemente una de las mejores novelas de todos los tiempos, Madame Bovary narra la oscura tragedia de Emma Bovary, mujer infelizmente casada, cuyos sueños choca cruelmente con la realidad. Al hechizo que ejerce la figura de la protagonista hay que añadir la sabia combinación argumental de rebeldía, violencia, melodrama y sexo, «los cuatro grandes ríos», como afirmó en su día Mario Vargas Llosa, que alimentan esta historia inigualable. La publicación de esta obra en 1857 fue recibida con gran polémica y se procesó a Flaubert por atentar contra la moral. A través del personaje de Madame Bovary, el autor rompe con todas las convenciones morales y literarias de la Burguesía del siglo XIX, tal vez porque nadie antes se había atrevido a presentar un prototipo de heroína de ficción rebelde y tan poco resignada al destino. Hoy existe el término «bovarismo» para aludir aquel cambio del prototipo de la mujer idealizada que difundió el romanticismo, negándole sus derechos a la pasión. Ella actúa de acuerdo a la pasión y necesidad que siente su corazón de avanzar en la búsqueda de su felicidad, pasando por los ideales establecidos para la mujer en esa época. Rompe con el denominado encasillamiento en que la mayoría de las mujeres estaban sometidas.",
    genres: ["Novela Realista"],
  },
  {
    id: 10000015,
    name: "¿Qué hace un bosón como tú en un big bang como este?",
    author: "Javier Santaolalla",
    plot: "Si cuando sales de noche a un sitio despejado levantas la cabeza y sólo ves puntos de luz, te estás perdiendo la mejor parte de estar vivo. Yo veo partículas que surgen de una gran “ explosión” hace miles de millones de años, que chocan y se transforman mientras se van agrupando por gravedad. Veo cómo se van creando cúmulos de materia en forma de nubes de gas, que dan lugar a sistemas mayores llamados “galaxias”. Pero también veo ese maravilloso viaje del ser humano para entender quiénes somos, qué hacemos aquí, acompañados de genios como Galileo o Einstein, de grandes ideas como la relatividad o la mecánica cuántica, de historias como el gato de Schrödinger, el sombrero mexicano o la manzana de Newton... Este libro es un viaje hacia las estrellas, hacia el Big Bang, pero por encima de todo hacia el interior de nosotros mismos. Nos permitirá situar mejor el lugar que ocupamos en este mundo",
    genres: ["Ensayo", "Ciencia"],
  },
  {
    id: 10000016,
    name: "Javier Santaolalla",
    author: "El Bosón De Higgs No Te Va A Hacer La Cama",
    plot: "¿Qué tienen en común Frodo Baggins, Luke Skywalker, Pikachu y Ronaldo? Muy sencillo: que todos ellos pueden ayudarnos a comprender, de manera amena y reveladora, los secretos más complejos de la física. En este libro sorprendente, que ya se ha convertido en un best seller en España, Javier Santaolalla nos presenta los conceptos más fascinantes de nuestro universo, desde la mecánica cuántica y el comportamiento impredecible de las partículas subatómicas, hasta los agujeros negros y la antimateria. Un volumen fundamental para entender mejor de qué estamos hechos, cómo funciona nuestro mundo y cuál es nuestro lugar en el universo.",
    genres: ["Ensayo", "Ciencia"],
  },
  {
    id: 10000017,
    name: "Hijos de Dune",
    author: "Frank Herbert",
    plot: "Leto Atreides, el hijo de Paul -el mesías de una religión que arrasó el universo, el mártir que, ciego, se adentró en el desierto para morir-, tiene ahora nueve años. Pero es mucho más que un niño, porque dentro de él laten miles de vidas que lo arrastran a un implacable destino. Él y su hermana gemela, bajo la regencia de su tía Alia, gobiernan un planeta que se ha convertido en el eje de todo el universo. Arrakis, más conocido como Dune. Y en este planeta, centro de las intrigas de una corrupta clase política y sometido a una sofocante burocracia religiosa, aparece de pronto un predicador ciego, procedente del desierto. ¿Es realmente Paul Atreides, que regresa de entre los muertos para advertir a la humanidad del peligro más abominable?",
    genres: ["Ciencia Ficción"],
  },
  {
    id: 10000018,
    name: "El imperio final",
    author: "Brandon Sanderson",
    plot: "Durante mil años han caído cenizas del cielo. Durante mil años nada ha florecido. Durante mil años los skaa han sido esclavizados y viven en la miseria, sumidos en un miedo inevitable. Durante mil años el Lord Legislador ha reinado con poder absoluto, dominando gracias al terror, a sus poderes y a su inmortalidad, ayudado por «obligadores» e «inquisidores», junto a la poderosa magia de la alomancia. Pero los nobles a menudo han tenido trato sexual con jóvenes skaa y, aunque la ley lo prohíbe, algunos de sus bastardos han sobrevivido y heredado los poderes alománticos: son los «nacidos de la bruma» (mistborn). Ahora, Kelsier, el «superviviente», el único que ha logrado huir de los Pozos de Hathsin, ha encontrado a Vin, una pobre chica skaa con mucha suerte... Tal vez los dos, con el mejor equipo criminal jamás reunido, unidos a la rebelión que los skaa intentan desde hace mil años, logren cambiar el mundo y acabar con la atroz mano de hierro del Lord Legislador. Pero, ¿qué pasa si el héroe de la profecía falla?",
    genres: ["Fantasía"],
  },
  {
    id: 10000019,
    name: "El pozo de la ascensión",
    author: "Brandon Sanderson",
    plot: "El mal ha sido derrotado. Pero la guerra acaba de empezar. Lograron lo imposible y pusieron fin al reinado milenario de lord Legislador. Ahora Vin, que ha pasado de ser una ladronzuela a una poderosa nacida de la bruma, y Elend Venture, el joven noble e idealista que la ama, deberán construir una sociedad nueva y próspera sobre las cenizas de ese imperio derrotado. Mientras las tensiones siguen creciendo tras la revuelta, una antigua leyenda ofrece un atisbo de esperanza para el pueblo. Sin embargo, incluso si las habladurías son ciertas, nadie sabe dónde se encuentra el Pozo de la Ascensión ni que clase de poder otorga. Es muy posible que matar al lord Legislador fuera la parte fácil. Sobrevivir a las consecuencias de su caída será el verdadero desafío.",
    genres: ["Fantasía"],
  },
  {
    id: 10000020,
    name: "El héroe de las eras",
    author: "Brandon Sanderson",
    plot: "En El héroe de las eras se explican el porqué de la niebla y las cenizas, las tenebrosas acciones del Lord Legislador y la naturaleza del Pozo de la Ascensión. Vin y el Rey Elend buscan en los últimos escondites del Lord Legislador y descubren el peligro que acecha a la humanidad. ¿Conseguirán detenerlo a tiempo?",
    genres: ["Fantasía"],
  },
  {
    id: 10000021,
    name: "El Hobbit",
    author: "J. R. R. Tolkien",
    plot: "Smaug parecía profundamente dormido cuando espió una vez más la entrada. ¡Pero fingía estar dormido! ¡Estaba vigilando la entrada del túnel! Sacado de su cómodo agujero hobbot por Gandalf y una banda de enanos, Bilbo se encuentra de pronto en medio de una conspiración que pretende apoderarse del tesoro de Smaug el Magnífico, un enorme y muy peligroso dragón...",
    genres: ["Fantasía"],
  },
  {
    id: 10000022,
    name: "El Señor de los Anillos: La Comunidad del Anillo",
    author: "J. R. R. Tolkien",
    plot: "En la adormecida e idílica Comarca, un joven hobbit recibe un encargo:  custodiar el Anillo Único y emprender el viaje para su destrucción en  las Grietas del Destino. Consciente de la importancia de su misión,  Frodo abandona la Comarca e inicia el camino hacia Mordor con la  compañía de inesperada de Sam, Pippin y Merry.  Pero sólo con la ayuda  de Aragorn conseguirán vencer a los Jinetes Negros y alcanzar el refugio  de la Casa de Elrond en Rivendel.",
    genres: ["Fantasía"],
  },
  {
    id: 10000023,
    name: "El Señor de los Anillos: Las dos torres",
    author: "J. R. R. Tolkien",
    plot: "La Compañía se ha disuelto y sus integrantes emprenden caminos  separados. Frodo y Sam continúan solos su viaje a lo largo del río  Anduin, perseguidos por la sombra misteriosa de un ser extraño que  también ambiciona la posesión del Anillo. Mientras, hombres, elfos y  enanos se preparan para la batalla final contra las fuerzas del Señor  del Mal.",
    genres: ["Fantasía"],
  },
  {
    id: 10000024,
    name: "El Señor de los Anillos: El Retorno del Rey",
    author: "J. R. R. Tolkien",
    plot: "Los ejércitos del Señor Oscuro van extendiendo cada vez más su maléfica  sombra por la Tierra Media. Hombres, elfos y enanos unen sus fuerzas  para presentar batalla a Sauron y sus huestes. Ajenos a estos  preparativos, Frodo y Sam siguen adentrándose en el país de Mordor en su  heroico viaje para destruir el Anillo de Poder en las Grietas del  Destino.",
    genres: ["Fantasía"],
  },
];

export default pendingBooks;
