// All Ids start at 1000000001

let completedMangas = [
  {
    id: 1000000001,
    name: "Mi vecino metalero",
    author: "Mamita",
    review: ``,
    plot: `Kento se muda a un nuevo lugar para vivir, pero que todavía no está acondicionado y no tiene calefacción. Muerto de frío, es salvado por su vecino Soushi, un amante del metal, siempre vestido de negro, con el pelo largo y cara de malas pulgas. Aunque parece algo distante, está claro que Soushi esconde algo más de lo que su aspecto dice.
    A partir de ese día, los dos chicos se hacen amigos y empiezan a comer juntos día tras día durante un año. Kento no le dice nunca que es gay porque tiene miedo de estropear la relación entre ellos, pero, ¿será capaz de esconder sus sentimientos?`,
    genres: ["Boys Love", "Drama", "Romance"],
    favourite: false,
    score: 4,
  },
  {
    id: 1000000002,
    name: "Home Far Away",
    author: "Teki Yatsuda",
    plot: `Años 90, Estados Unidos. En un hogar con unos padres ultrarreligiosos, vive como si estuviera muerto el joven Alain Saverio. Cuando conoce a Hayden, se siente fuertemente atraído por él, pero descubre que lleva una vida errante y no suele quedarse mucho en un mismo sitio.
    Para estar con él, decide irse de casa, por lo que acaban tomando a Hayden por su secuestrador. Aun así, este se deshace de todo y rescata a Alain del infierno.    
    Las huellas del coche son su vía de escape. Para ambos se trata del camino de vuelta al “hogar de ellos dos solos”`,
    review: ``,
    genres: ["Boys Love", "Drama", "Romance"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000003,
    name: "Twilight Outfocus",
    author: "Jyanome",
    plot: `Mao vive en la residencia de un instituto masculino, donde comparte habitación con Hisashi, un lobo solitario rebelde. Hasta ahora se han llevado bien gracias a que siguen a rajatabla las tres promesas que se hicieron: “Mao no revelará que Hisashi es gay y que tiene novio”, “Hisashi no mirará a Mao con intereses románticos ni le meterá mano”.
    En la primavera de segundo de bachillerato, el director del club de cine al que pertenece Mao le pide que convenza a Hisashi para que interprete al protagonista de una película: un chico atractivo, rebelde... ¡y gay!
    Así empieza esta historia de amor refrescante entre dos jóvenes que aún no conocen el amor y dudan sobre la naturaleza de sus sentimientos.`,
    review: ``,
    genres: ["Boys Love", "Romance"],
    favourite: false,
    score: 7,
  },
  {
    id: 1000000004,
    name: "Links",
    author: "Natsuki Kizu",
    plot: `Sekiya, locutor de radio, y Shibata, que trabaja en la cafetería a la que suele acudir; Kameda y Ogikawa, que se conocen en una fría noche y quedan unidos por un gato; Akiha, que no ha podido olvidar su primer amor, y Yahiko, su amante; y Nakajô y Sado, que llevan tiempo juntos, pero siempre andan discutiendo. Estas cuatro parejas deberán lidiar con sus sentimientos más profundos si quieren que sus relaciones no descarrilen.`,
    review: ``,
    genres: ["Boys Love", "Drama", "Romance"],
    favourite: false,
    score: 7,
  },
  {
    id: 1000000005,
    name: "Given",
    author: "Natsuki Kizu",
    plot: `Justo cuando está empezando a hastiarse de la guitarra y el baloncesto que tanto adoraba, Uenoyama se encuentra con Mafuyu, que está abrazado a una guitarra estropeada. Después de arreglársela, no puede evitar sentir cierta simpatía hacia él. Entonces le oye cantar... y su voz se le clava en lo más hondo del alma...`,
    review: ``,
    genres: ["Boys Love", "Drama", "Romance"],
    favourite: true,
    score: 9,
  },
  {
    id: 1000000006,
    name: "Ao Haru Ride",
    author: "Io Sakisaka",
    plot: `Aoha Ride muestra las vicisitudes de la vida en el instituto: la amistad, la dificultad de entablar relaciones con otros compañeros con personalidades distintas, el primer amor… mediante la emotiva historia que protagonizan Futaba y Kou.`,
    review: ``,
    genres: ["Romance", "Drama", "Comedia", "Escolar"],
    favourite: false,
    score: 8,
  },
  {
    id: 1000000007,
    name: "Guang Xiang",
    author: "D-Kun",
    plot: `Una historia de dos chicos jóvenes - uno llamado Yu Xiao Guang, el otro llamado Lin Xiang - que tienen que hacer frente a los problemas impuestos por la realidad y su familias, en medio de sus difíciles años de la adolescencia, ¿cómo van a consolarse el uno al otro? ¿Cuál será la verdadera naturaleza de su amistad? Y lo ¿que sera lo que depara el futuro para ellos?`,
    review: ``,
    genres: ["Romance", "Boys Love", "Drama", "Escolar"],
    favourite: false,
    score: 7,
  },
  {
    id: 1000000008,
    name: "Al final del camino",
    author: "Haribo",
    plot: `Luego de un accidente automovilístico, Tae Min se encuentra dentro del cuerpo de Si won, un chico que es víctima de bullying escolar. Dejando de ser una persona fácil de influenciar, él comienza a plantarle cara a la situación pero luego se encuentra a Woo Jin, un viejo amigo del pasado. De alguna manera, Woo Jin capta la "esencia" de Tae Min en Si Won. ¿Qué ha sucedido entre ellos dos en el pasado y cómo afectará al futuro?`,
    review: `Realmente no recuerdo haberlo leído pero esta en una lista de completados que tenía. Por lo tanto va a quedar sin puntaje.`,
    genres: ["Romance", "Drama", "Boys Love"],
    favourite: false,
    score: 0,
  },
  {
    id: 1000000009,
    name: "Cherry Blossoms After Winter",
    author: "Bam U",
    plot: `Haebom y Taesung, antaño jóvenes amigos, se distanciaron tras la tragedia que les golpeó hace casi 10 años. Ahora vuelven a estar juntos tras graduarse en el instituto, pero sus sentimientos mutuos no han hecho más que crecer`,
    review: ``,
    genres: ["Romance", "Drama", "Boys Love"],
    favourite: false,
    score: 5,
  },
  {
    id: 1000000010,
    name: "Tokyo Ghoul",
    author: "Sui Ishida",
    plot: `Los habitantes de Tokio viven aterrados: en las sombras de la metrópolis se ocultan horribles monstruos que se camuflan entre la multitud, cazando y devorando seres humanos. Un joven se topa con uno de estos ghouls, pero aunque consigue sobrevivir, su existencia ya no será igual…`,
    review: ``,
    genres: ["Acción", "Drama", "Psicológico"],
    favourite: true,
    score: 8,
  },
  {
    id: 1000000011,
    name: "Tokyo Ghoul:re",
    author: "Sui Ishida",
    plot: `Ciudad de Tokio, la cual sigue sumergida en la desesperación. Seres devoradores de hombres misteriosos, espíritus necrófagos, proliferan en Tokio. Vivir escondido es la vida cotidiana de sus habitantes, la existencia de demonios, cuya identidad verdadera y llena de misterio aterroriza permanentemente residentes de Tokio.
    En CCG, la única institución que investiga y resuelve los casos relacionados con vampiros, se le asigna un nuevo caso a Haise Sasaki. Mientras que hace frente a cuatro revoltosos y problemáticos niños conocidas como “Quinx”, los problemas comienzan para Haise.`,
    review: ``,
    genres: ["Acción", "Drama", "Psicológico"],
    favourite: true,
    score: 9,
  },
  {
    id: 10000000012,
    name: "Un chicho como tú",
    author: "Waje",
    plot: `Los sueños de Go Siwon son constantemente visitados por el inteligente y bello Kang Jinha. En el sueño Jinha mantiene en mención el "incidente" que les habia ocurrido pero ¡Siwon no puede recordar nada! Y ¿como se siente en realidad? Afortunadamente para Siwon, partes del "incidente" empezaron a aparecer y Siwon esta poco a poco recuperando su memoria. ¿Cómo cambiará su relación al final de esto?`,
    review: `Realmente no recuerdo haberlo leído pero esta en una lista de completados que tenía. Por lo tanto va a quedar sin puntaje.`,
    genres: ["Romance", "Boys Love"],
    favourite: false,
    score: 0,
  },
  {
    id: 1000000013,
    name: "De ventana a ventana",
    author: "Lee Aru",
    plot: `Yubin es amigo de infancia de Shin Ginu desde preescolar. Él descubrió que le gustaba desde primer año de secundaria; ahora están asistiendo a la universidad juntos, pero él todavía sigue guardando en secreto sus sentimientos por Shin`,
    review: ``,
    genres: ["Romance", "Boys Love"],
    favourite: false,
    score: 5,
  },
  {
    id: 1000000014,
    name: "Heartstopper",
    author: "Alice Oseman",
    plot: `Dos chicos se conocen. Se hacen amigos. Se enamoran. ¿Por qué nos empeñamos en hacer complicadas las emociones más sencillas?
    Esta historia de amor entre dos chicos, uno de ellos declaradamente homosexual y el otro en vías de autodescubrimiento, nos recordaráque hay primeros amores frágiles como el cristal y memorables como el diamante. Con los titubeos propios de cualquier amor adolescente,Heartstopper responde a la manera de sentir de los jóvenes reales, con una visión abierta, natural y sensible sobre el amor y la identidad sexual, sin perder nunca la delicadeza y la emoción.`,
    review: ``,
    genres: ["Romance", "Boys Love"],
    favourite: true,
    score: 10,
  },
];

export default completedMangas;
