// start id with A1
let completedAnimes = [
  {
    id: "A1",
    name: "Jujutsu Kaisen",
    author: "Gege Akutami / Mappa",
    review: ``,
    plot: `Yuji Itadori se traga un dedo maldito para salvar a alguien de su clase y ahora Ryomen Sukuna, un poderoso hechicero malvado conocido como el Rey de las Maldiciones, vive en su alma. Las maldiciones son seres sobrenaturales creadas a partir de las emociones negativas de los humanos. Esta energía maldita puede usarse como fuente de poder por parte de los hechiceros y de los espíritus malditos.
    Guiado por los hechiceros, Yuji Itadori se une a la Escuela de Bachillerato Técnico de Brujería de Tokio, una organización que enfrenta a las maldiciones. Con la ayuda de su maestro, Satoru Gojo, Itadori hace amistad con Megumi Fushiguro y Nobara Kugisaki, ambos estudiantes de primer año como él.`,
    genres: ["Acción", "Sobrenatural", "Fantasia"],
    favourite: false,
    score: 8,
  },
  {
    id: "A2",
    name: "Shigatsu wa Kimi no Uso",
    author: "Naoshi Arakawa / A-1 Pictures",
    review: ``,
    plot: `Arima Kosei es un prodigio del piano, y cualquier niño músico del mundo conoce su nombre, pero cuando su madre y también maestra fallece, se desmorona en mitad de un recital y desde ese momento es completamente incapaz de escuchar el sonido de su piano aunque no tenga problemas de oído. Dos años después, Kosei sigue sin tocar un piano y ve el mundo como algo monótono, sin color. Se conformaba con llevar una vida tranquila junto a sus amigos Tsubaki y Watari, al menos hasta que una chica lo cambia todo: Miyazono Kaori.`,
    genres: ["Musica", "Drama", "Romance"],
    favourite: true,
    score: 9,
  },
  {
    id: "A3",
    name: "Death Parade",
    author: "Yuzuru Tachikawa / Madhouse",
    review: ``,
    plot: `En algún lugar existe un misterioso bar llamado Quindecim, donde un empleado y encargado de la barra llamado Decim trabaja. En el momento en el que dos personas salen de los ascensores del bar, sin saber por qué, deben participar en un juego de la muerte apostando sus vidas. Los resultados revelarán qué secretos los llevaron ahí y cuál será su destino.`,
    genres: ["Drama", "Thriller"],
    favourite: false,
    score: 7,
  },
  {
    id: "A4",
    name: "Bokurano",
    author: "Mohiro Kitoh / Gonzo",
    review: ``,
    plot: `Bokurano narra la historia de 15 niños, de edades comprendidas entre los 10 y 15 años, que se ven metidos en un “juego” para salvar el planeta de una invasión de monstruos que vienen de una galaxia muy lejana. Para ello cuentan con Zearth, un robot gigante que tendrán que pilotar para luchar. Si pierden alguna de las batallas su mundo se destruirá. Existen además otras reglas que lo hacen aún más cruel, el robot solo puede ser dirigido por una persona cada vez, y después de dirigirlo morirá.`,
    genres: ["Drama", "Thriller"],
    favourite: false,
    score: 7,
  },
  {
    id: "A5",
    name: "Yuri!!! On Ice",
    author: "Mappa",
    review: ``,
    plot: `La historia se centra en Yuuri Katsuki, un joven patinador artístico sobre hielo japonés que sufre una dura derrota durante las competiciones finales del Grand Prix, quedando último en la competición. Abrumado y deprimido por este hecho, Yuri comienza a dudar de su carrera como patinador, a la vez que lidia con los otros problemas en su vida personal. Al regresar a su ciudad natal de Hasetsu luego de cinco años, Yuri se dirige a una pista de patinaje donde imita a la perfección una coreografía del famoso patinador ruso Victor Nikiforov, a quien admira desde pequeño. Cuando el vídeo de Yuri patinando es subido al internet sin su conocimiento, atrae la atención de Victor, quien decide convertirse en el entrenador de Yuri y entrenarlo junto a su otro pupilo, Yuri Plisetsky.`,
    genres: ["Drama", "Deportes"],
    favourite: false,
    score: 8,
  },
  {
    id: "A6",
    name: "Charlotte",
    author: "Jun Maeda / P.A Works",
    review: ``,
    plot: `La historia gira en torno a unos chicos y chicas especiales que en cierto punto de sus vidas desarrollan habilidades sobrehumanas que va desapereciendo durante su pubertad. Yu Otosaka usa su poder sin que nadie lo sepa y lleva una vida bastante normal utilizando su habilidad para cambiar de cuerpo y copiarse las respuestas de los exámenes en clase,  con una vida estudiantil común. Ante él aparece un día una chica llamada Nao Tomori. Debido a su encuentro con ella, el destino de aquellos con poderes especiales quedará al descubierto. Esta es la historia de cómo aquellos con poderes especiales experimentan la juventud.`,
    genres: ["Sobrenatural", "Escolar"],
    favourite: false,
    score: 6,
  },
  {
    id: "A7",
    name: "Super Lovers",
    author: "Abe Miyuki",
    review: ``,
    plot: `Haru Kaido viaja de Japón a Canadá cuando su madre le dice que está al borde de la muerte, pero cuando llega descubre que todo era un engaño y que su madre quiere que cuide de un niño que dice que es su nuevo hermano. El nuevo hermanito de Haru es Ren, un niño obstinado y cuyo nacimiento oculta cierto secreto. Sin embargo, cuando Ren comienza a abrirse a Haru, ocurre una tragedia. Cinco años después Haru y Ren se reúnen algo más mayores en Tokio, pero…`,
    genres: ["Drama", "Romance", "Boys Love"],
    favourite: false,
    score: 6,
  },
  {
    id: "A8",
    name: "Your Name",
    author: "CoMix Wave Films",
    review: ``,
    plot: `Mitsuha es una chica de pueblo cuyo padre participa en las elecciones a alcalde de la ciudad. Sin embargo, ella anhela la emoción de la vida de la ciudad y por eso tiene un deseo: “quiere encontrarse con el chico guapo de sus sueños que seguro que encuentra en Tokio”. Un día sueña con un chico tal y como desea pero ese chico en cuestión, Taki, de la gran ciudad, sueña a su vez con Mitsuha, una encantadora chica del campo. Taki y Mitsuha descubren un día que durante el sueño sus cuerpos se intercambian, y comienzan a comunicarse por medio de notas. A medida que consiguen superar torpemente un reto tras otro, se va creando entre los dos un vínculo que poco a poco se convierte en algo más romántico.`,
    genres: ["Drama", "Romance"],
    favourite: true,
    score: 10,
  },
  {
    id: "A9",
    name: "Aldnoah Zero",
    author: "A-1 Pictures",
    review: ``,
    plot: `En 1972 se descubría un portal espacial en la superficie de la Luna con el que la humanidad entró en contacto con seres de Marte… lo que llevó a una guerra.
    1999: El Imperio Vers finalmente declara la guerra a la Alianza Terrestre. Durante la fiera lucha, la hypergate perdía el control, destrozando la Luna. Han pasado 15 años desde entonces.`,
    genres: ["Mecha", "Acción", "Ciencia Ficción"],
    favourite: false,
    score: 7,
  },
  {
    id: "A10",
    name: "Stars Align",
    author: "Eight Bit",
    review: ``,
    plot: `Cuando un viejo amigo se muda a la ciudad, Toma, el capitán del equipo, tiene un plan para salvar el club de tenis de los chicos que está en peligro de ser disuelto por lo horrible que es.`,
    genres: ["Drama", "Deportes"],
    favourite: false,
    score: 8,
  },
  {
    id: "A11",
    name: "Sasaki and Miyano",
    author: "Shō Harusono / Studio Deen",
    review: ``,
    plot: `Miyano es un estudiante que adora el manga de corte boys love y al que le acompleja un poco el tener unos rasgos muy poco masculinos. Su afición por la ficción se convertirá en algo más real cuando conozca por casualidad a Sakaki, un estudiante mayor que él que lo salva de unos abusones. Juntos comenzarán una relación de amistad que pronto querrá convertirse en algo más... si ambos son capaces de dar el paso y admitir lo que sienten.`,
    genres: ["Drama", "Boys Love"],
    favourite: false,
    score: 8,
  },
  {
    id: "A12",
    name: "March comes in like a lion",
    author: "Chica Umino / Shaft",
    review: ``,
    plot: `Una dulce historia de personas que intentan recuperar algo, y a su vez, la historia de una lucha.
    Rei Kiryama perdió a su familia en un accidente siendo muy joven, y ahora, con 17 años, es un jugador profesional de shogi sumido en una profunda soledad. El muchacho vive solo en un viejo pueblo de Tokio, pero tras comenzar a relacionarse con las tres hermanas Akari, Hinata y Momo, comienza a cambiar poco a poco.`,
    genres: ["Drama", "Romance", "Deportes"],
    favourite: true,
    score: 10,
  },
  {
    id: "A13",
    name: "Code Geass",
    author: "Sunrise",
    review: ``,
    plot: `Año 2017 del calendario imperial. Lelouch, un joven cuyo derecho de sucesión al trono le fue arrebatado, se convierte en "Zero", el hombre enmascarado, y conduce una insurrección a gran escala, la "Rebelión Negra", contra su propia patria, la superpotencia del Sacro Imperio de Britannia. Mientras el sentimiento anti Britannia se hace más fuerte, el imperio decide utilizar su abrumador poderío militar para someter a los rebeldes.`,
    genres: ["Acción", "Drama", "Ciencia Ficción", "Mecha"],
    favourite: true,
    score: 10,
  },
  {
    id: "A14",
    name: "Trigun",
    author: "Yasuhiro Nightow / Madhouse",
    review: ``,
    plot: `En una tierra similar al Lejano Oeste se cuentan historias de un cruel y peligroso criminal cuya recompensa asciende a 60 mil millones. Meryl y Milly deciden encontrarlo y vigilarlo para así evitar sus fechorías.`,
    genres: ["Drama", "Acción"],
    favourite: false,
    score: 9,
  },
  {
    id: "A16",
    name: "Death Note",
    author: "Tsugumi Ōba / ",
    review: ``,
    plot: `Light Yagami es un estudiante brillante con mucho futuro que se aburre a más no poder. Pero todo cambia cuando encuentra la Death Note, un cuaderno que dejó caer un rebelde dios de la muerte.`,
    genres: ["Sobrenatural", "Thriller"],
    favourite: true,
    score: 10,
  },
  {
    id: "A17",
    name: "Cowboy Bebop",
    author: "Sunrise",
    review: ``,
    plot: `En el futuro, nuestro sistema solar ha entrado a la era espacial y es posible viajar a distintos planetas en poco tiempo gracias a una serie de portales espaciales. Spike y Jet, un antiguo miembro de la mafia y un antiguo policía respectivamente, se ganan ahora la vida como cazarrecompensas y recorren el espacio atrapando a los criminales sobre cuyas cabezas hay recompensas. Los acompañan Faye, una misteriosa mujer que ha perdido la memoria y carga con una gran deuda, y Ed, una joven genio del hackeo que se comporta como un niño que solo busca divertirse.`,
    genres: ["Drama", "Acción", "Ciencia Ficción"],
    favourite: true,
    score: 9,
  },
  {
    id: "A18",
    name: "Assassination Classroom",
    author: "Yūsei Matsui",
    review: ``,
    plot: `Olvídate de las tareas y los exámenes sorpresa. Los estudiantes de la Clase 3E tienen una tarea mucho más importante: ¡matar a su profesor antes de fin de año! Un sensei con tentáculos que se mueve a Mach 20 quiere conquistar el aula después de destruir el setenta por ciento de la luna. Además de leer, escribir y aritmética, el monstruo asesino detrás del atril enseñará a sus alumnos todo lo que sabe sobre el juego del asesinato. Si algún castor entusiasta demuestra ser un experto en matar, salvará a la Tierra de la extinción y obtendrá una considerable recompensa.`,
    genres: ["Drama", "Acción", "Ciencia Ficción", "Comedia"],
    favourite: false,
    score: 8,
  },
  {
    id: "A19",
    name: "Knights of Sidonia",
    author: "Tsutomu Nihei / Polygon Pictures",
    review: ``,
    plot: `Mil años después de que el extraterrestre Gauna destruyera la Tierra, un pequeño resto de humanidad todavía lucha por sobrevivir, huyendo en la gigantesca nave espacial Sidonia, basada en un asteroide.`,
    genres: ["Drama", "Acción", "Ciencia Ficción", "Mecha"],
    favourite: false,
    score: 8,
  },
  {
    id: "A20",
    name: "Elfen Lied",
    author: "Lynn Okamoto / GENCO, VAP",
    review: `La verdad que después de verlo no entiendo todo el hype que le hacen a la serie. El opening está bueno eso si...`,
    plot: `Cuando Kota conoce a Nyu, conoce a una chica desvalida, que no recuerda nada y que es como una niña pequeña e inocente. En ese momento no sabía su secreto: Nyu en realidad es una Diclonius, un poderoso ser, que se ha escapado de un laboratorio. Desde el laboratorio están dispuestos a todo para recuperar a su sujeto de pruebas, aunque deban matarlo. ¿Cómo proteger a la inocente joven de un ejército armado?`,
    genres: ["Drama", "Thriller", "Acción", "Ciencia Ficción"],
    favourite: false,
    score: 4,
  },
  {
    id: "A21",
    name: "Inuyashiki Last Hero",
    author: " Hiroya Oku / Mappa",
    review: `Terrible anime, la verdad que unas pocas escenas interesantes me baitearon para verlo, gran error. Ni los personajes ni la historia son interesantes.`,
    plot: `Ichiro Inuyashiki era un aburrido oficinista que vivía rechazado por su familia y sus compañeros de trabajo. Una noche, un ovni chocó con él, y su cuerpo fue reconstruido para formar un poderoso robot. Un alumno de secundaria llamado Hiro Shishigami participó del mismo accidente, y comienza a usar sus nuevos poderes para cumplir sus impulsos más oscuros. ¿la naturaleza del hombre es buena o mala?`,
    genres: ["Drama", "Ciencia Ficción", "Acción"],
    favourite: false,
    score: 3,
  },
  {
    id: "A22",
    name: "Karneval",
    author: "Touya Mikanagi / Manglobe",
    review: ``,
    plot: `Armada sólo con un brazalete abandonado como pista, Nai busca a un ser querido desaparecido. Después de un encuentro con un carterista llamado Gareki, los dos se ven atrapados en una organización gubernamental que los convierte a ambos en criminales buscados. Desesperados y huyendo, Nai y Gareki recurren a la organización de defensa más poderosa del país, "Circus", en busca de ayuda.`,
    genres: ["Drama", "Acción", "Fantasia", "Comedia"],
    favourite: false,
    score: 6,
  },
  {
    id: "A23",
    name: "Schwarzes Marken",
    author: "",
    review: ``,
    plot: `Año 1983, el 666º Escuadrón TSF del Ejército de Alemania Oriental, "Schwarzes marken", es una fuerza especial de respuesta inmediata contra los BETA. Su objetivo son específicamente los BETA de tipo Láser y Láser Pesado para así disminuir la enorme potencia de fuego del enemigo. Las órdenes de este equipo sin piedad tienen siempre la más alta prioridad, y las siguen tan al pie de la letra, que el 666º escuadrón es bien conocido por ignorar incluso las llamadas de auxilio de sus aliados si eso interfiere con su misión aunque sea por un instante.`,
    genres: ["Drama", "Acción", "Ciencia Ficción", "Mecha"],
    favourite: false,
    score: 8,
  },
  {
    id: "A24",
    name: "Muu-Luv alternative: total eclipse",
    author: "Satelight",
    review: ``,
    plot: `Los últimos restos de la humanidad aguantan como pueden en Alaska, donde dos jóvenes pilotos se enfrentarán a su destino. Desde 1973, la Tierra está bajo el ataque de unos extraterrestres conocidos como BETA, y su ferocidad ha dejado a la humanidad al borde de la extinción.`,
    genres: ["Drama", "Acción", "Ciencia Ficción", "Mecha"],
    favourite: false,
    score: 7,
  },
  {
    id: "A25",
    name: "Log Horizon",
    author: "Mamare Touno / Satelight, Studio Deen",
    review: `Es SAO pero bueno. Lastima que la tercera temporada salió muy tarde para mí...`,
    plot: `La historia comienza cuando 30.000 jugadores japoneses quedan atrapados en el mundo de fantasía online Elder Tale. Lo que en su momento era una vía de escape del mundo real, es ahora toda la realidad que conocen. Shiroe, el protagonista, intenta sobrevivir como puede en ese mundo junto a su viejo amigo Naotsugu y a la preciosa asesina Akatsuki.`,
    genres: ["Drama", "Acción", "Fantasia"],
    favourite: false,
    score: 7,
  },
  {
    id: "A26",
    name: "Psycho-Pass",
    author: "Production I.G",
    review: `La primera temporada está buena, la segunda es mejor hacer que no existe.`,
    plot: `En el año 2113, la población se somete a un escáner que determina las probabilidades de cometer un crimen. Quienes no pasan la prueba son detenidos o condenados a morir.`,
    genres: ["Ciencia Ficción", "Acción", "Thriller"],
    favourite: false,
    score: 7,
  },
  {
    id: "A27",
    name: "Given",
    author: "Natsuki Kizu / Lerche",
    review: `La historia es excelente como en el manga pero el poder vivir la historia con la música hace que para mí el anime sea mucho mejor.`,
    plot: `Ritsuka Uenoyama es un joven que se aficionó a la guitarra siendo muy joven y tras mucho esfuerzo, consiguió alcanzar el nivel que quería, pero la guitarra que tanto amaba ha perdido su brillo y no le divierte ni le apasiona como antes... hasta que un día conoce a Mafuyu Sato, un joven que se aferra a una guitarra con toda su alma pese a que no sabe tocarla y quien le pedirá que le enseñe a tocar... haciendo que todo en la vida de Uenoyama cambie y la música acelere nuevamente su corazón.`,
    genres: ["Música", "Drama", "Boys Love"],
    favourite: true,
    score: 10,
  },
  {
    id: "A28",
    name: "ID: Invaded",
    author: "NAZ",
    review: `Está bien pero no me causó grandes pasiones.`,
    plot: `Sakaido, el gran detective, despierta en un mundo extraño y fragmentado. ¿Podrán él y la organización policiaca conocida como Kura unir las piezas antes de que el asesino cobre otra víctima?`,
    genres: ["Ciencia Ficción", "Thriller"],
    favourite: false,
    score: 5,
  },
  {
    id: "A29",
    name: "Uchuu Kyoudai",
    author: "",
    review: `Excelente anime. Es un anime bastante largo pero engancha con su trama. Puede parecer simple pero los personajes nos atrapan en su lucha por seguir sus sueños. `,
    plot: `Había una vez dos hermanos, Hibito y Mutta. Hibito, el menor, fue bendecido con buena suerte desde el día que nació. Mutta, el mayor, tuvo siempre mala suerte. Un día los dos hermanos vieron un OVNI. Esta experiencia hizo que se decidieran a convertirse en astronautas. Mientras que Hibito tuvo éxito, Mutta estuvo trabajando en una empresa de autos. Pero luego de un incidente tuvo que renunciar. Y ahora Hibito está a punto de viajar a la luna.`,
    genres: ["Drama", "Comedia"],
    favourite: true,
    score: 9,
  },
  {
    id: "A30",
    name: "Natsume Yujin-cho",
    author: "Yuki Midorikawa / Brain's Base",
    review: `Cada historia te deja algo y es imposible dejar de verlo.`,
    plot: `Takashi Natsume ha visto yokai toda su vida. Heredó de su abuela Reiko un libro de nombres de yokai, los cuales le dan al dueño poder sobre los mismos, así que él y su guardaespaldas autoproclamado, Nyanko-sensei, pasan sus días devolviendo esos nombres a sus dueños originales. Muchos yokai lo confunden con su abuela, lo que da pie a muchas situaciones emotivas... y peligrosas.`,
    genres: ["Drama", "Fantasia", "Sobrenatural"],
    favourite: true,
    score: 9,
  },
  {
    id: "A31",
    name: "Orange",
    author: "Ichigo Takano / TMS Entertainment",
    review: `¿Cuántas cosas nos gustaría cambiar de nuestro pasado si pudiéramos? En esta historia aprendemos lo importante de vivir sin arrepentimientos, tomar las decisiones con las que vamos a estar orgullosos en el futuro`,
    plot: `Todo el mundo se arrepiente en la vida. ¿Y si pudieras tener la oportunidad de cambiar el pasado? Cuando Naho Takamiya, de 16 años, recibe una carta misteriosa que dice ser de parte de su yo del futuro con 26 años, su vida cambia por completo. La carta le explica cómo un nuevo estudiante transferido llamado Naruse Kakeru llegará a su clase, se enamorará de él y morirá en el invierno de su 17º cumpleaños. ¿Por qué? Naho deberá decidir si hacer caso a la críptica advertencia de la carta o no.`,
    genres: ["Drama", "Romance", "Sobrenatural"],
    favourite: false,
    score: 8,
  },
  {
    id: "A32",
    name: "Angel Beats!",
    author: "P.A. Works",
    review: `Excelente anime con un final que te destroza... Tiene la combinación perfecta de drama y comedia. `,
    plot: `Cuando Otonashi despierta en una escuela desconocida y sin recuerdos, la situación que tiene frente a él es completamente caótica: un grupo de estudiantes le dice que está muerto, que está en el más allá y que debe pelear si no quiere ser aniquilado. ¿El enemigo? Ángel, enviada de Dios y cuya misión es que estos jóvenes acepten sus injustas muertes. Pero en el más allá también se puede hacer vida escolar corriente... o al menos dentro de unos márgenes aceptables para alguien supuestamente muerto que quiere enfrentarse a Dios. ¡Bienvenido al Frente de los No Muertos!`,
    genres: ["Drama", "Fantasia", "Romance", "Acción", "Comedia"],
    favourite: false,
    score: 8,
  },
  {
    id: "A33",
    name: "Kitsutsuki Tanteidokoro",
    author: "Kei Ii / Liden Films",
    review: `Está bien pero no sale de la media`,
    plot: `La historia se desarrolla en 1909, durante la era Meiji, se centra en versiones ficticias del poeta Takuboku Ishikawa y del lingüista Kyōsuke Kindaichi, que eran conocidos en la vida real. En la novela, Takuboku dirige una agencia de detectives privados para apoyar a su familia. Ambos comienzan a investigar un caso de supuestas apariciones de fantasmas en el edificio Asakus Jūnikai, también conocido como Ryōunkai.`,
    genres: ["Drama", "Thriller"],
    favourite: false,
    score: 5,
  },
  {
    id: "A34",
    name: "Sword Art Online: Alicization",
    author: "Reki Kawahara / A-1 Pictures",
    review: `Teniendo cuenta que hablamos de Sao está bien... pero eso es poner la vara baja`,
    plot: `"¿Dónde estoy...?". Sin recordar cómo, Kirito se ha sumergido en un nuevo mundo virtual de fantasía. Con apenas unos pequeños retazos de recuerdos sobre lo que ocurrió antes de entrar al juego, comienza a vagar por él buscando alguna pista. Finalmente llega a un enorme y oscuro árbol, el Cedro Gigas, donde conoce a un joven. "Me llamo Eugeo. Es un placer conocerte, Kirito". Aunque es supuestamente un habitante de ese mundo virtual, un mero NPC, el joven parece mostrar el mismo abanico de emociones que cualquier ser humano. Kirito forja amistad con Eugeo y continúa buscando la forma de salir de este mundo virtual. Es entonces cuando recuerda algo que ocultaba en su interior. Recuerda haber corrido por las montañas con Eugeo cuando solo era un niño... Un recuerdo imposible que no debería tener, y en ese recuerdo ve también a una niña de cabellos rubios: Alice. Ese es un nombre que nunca deberá olvidar...`,
    genres: ["Fantasia", "Acción", "Aventura"],
    favourite: false,
    score: 6,
  },
  {
    id: "A35",
    name: "Kono Oto Tomare!",
    author: "Amyū / Platinum Vision",
    review: `Me gustan los animes de música en general y este cumple muy bien. Después de ver todo el esfuerzo de los personajes uno se siente contento con sus logros sobre el escenario.`,
    plot: `La historia nos presenta a Takezo, el último miembro del club de koto, un instrumento tradicional japonés. Si no logra encontrar nuevos miembros para el club, este desaparecerá. Un día, estando a solas en la sala del club, aparece un estudiante asegurando que quiere formar parte del club. Este estudiante es Chika Kudo, un delincuente que atemoriza incluso a los peores delincuentes de otras escuelas.`,
    genres: ["Drama", "Música", "Escolar"],
    favourite: false,
    score: 7,
  },
  {
    id: "A36",
    name: "Shingeki no Kyojin",
    author: "Hajime Isayama / Wit Studio",
    review: `Buena historia con giros interesantes y personajes que uno los va queriendo al avanzar la serie. El final es code geass... y nadie me va a convencer de lo contrario. Erwin el mejor personaje Shinzo wo Sasageyo!`,
    plot: `La historia nos traslada a un mundo en el que la humanidad estuvo a punto de ser exterminada cientos de años atrás por los gigantes. Los gigantes son enormes, parecen no ser inteligentes y devoran seres humanos. Lo peor es que parece que lo hacen por placer y no por alimentarse. Una pequeña parte de la humanidad ha conseguido sobrevivir protegiéndose en una ciudad con unos altísimos muros, más altos que el mayor de los gigantes. La ciudad vive su vida tranquila, y hace más de 100 años que ningún gigante aparece por allí. Eren y su hermana adoptiva Mikasa son todavía unos adolescentes cuando ven algo horroroso: un gigante mucho mayor que todos los que la humanidad había conocido hasta el momento está destruyendo los muros de la ciudad. No pasa mucho tiempo hasta que los gigantes entran por el hueco abierto en el muro y comienzan a devorar a la gente.`,
    genres: ["Drama", "Acción", "Fantasia"],
    favourite: true,
    score: 9,
  },
  {
    id: "A37",
    name: "Tokyo Ghoul",
    author: "Sui Ishida / Pierrot",
    review: `Buena historia, pero no me gusta mucho la adaptación que hicieron del manga. Aunque la historia del manga no es perfecta, es mucho mejor que el anime.`,
    plot: `Extraños asesinatos se están sucediendo uno tras otro en Tokyo. Debido a las pruebas encontradas en las escenas, la policía concluye que los ataques son obra de ghouls que se comen a las personas. Kaneki y Hide, dos compañeros de clase, llegan a la conclusión de que si nadie ha visto nunca a esos necrófagos es porque toman la apariencia de seres humanos para ocultarse. Poco sabían entonces de que su teoría sería más cierta de lo que pensaban cuando Kaneki es herido de gravedad por un monstruo y comienza a atraerle cada vez más la carne humana…`,
    genres: ["Drama", "Sobrenatural", "Acción", "Terror/Psicológico"],
    favourite: false,
    score: 6,
  },
  {
    id: "A38",
    name: "JoJo",
    author: "Hirohiko Araki / A.P.P.P.",
    review: `Excelente anime de poderes. Joseph Joestar siempre va a ser el mejor jojo`,
    plot: `La historia comienza con Jonathan Joestar, que vive con su padre George en Inglaterra con un nivel económico alto. Otro chico Dio Brando es adoptado por ellos dos ya que George creía que su padre Dario Brando les había salvado la vida. Jonathan trata de ser amigo de Dio, pero el plan de Dio es llevar a JoJo a la locura y ganar la confianza de George para conventirse en el heredero de la fortuna Joestar. Para lograrlo Dio golpea a Jonathan, besa a su novia Erina y quema a su perro Danny, y al mismo tiempo se gana la confianza de George con sus buenos modales, pero eso es solo el comienzo todo se complica cuando DIO se cruza con la "mascara del demonio" y su odio por jojo deja de ser un asunto de dinero. La Historia sigue con todos los susesores de Jonathan Joestar(JoJo), hijos, nietos que comparten sus ideales`,
    genres: ["Acción", "Aventura"],
    favourite: false,
    score: 9,
  },
  {
    id: "A39",
    name: "Steins Gate",
    author: "White Fox",
    review: `Si te gustan los viajes en el tiempo tenes que verlo. Si no te gustan los viajes en el tiempo igual hay que verlo. ¡Es perfecto! La segunda temporada baja un poco en mi opinión comparado con la primera pero de todas formas es excelente `,
    plot: `La historia de "Steins;Gate" toma lugar en Akihabara y trata acerca de un grupo de amigos que modificaron su microondas conviertiendolo en un dispositivo que puede mandar mensajes de texto al pasado. Mientras realizan diversos experimentos, una organizacion llamada SERN, que ha estado realizando su propia investigacion sobre viajes en el tiempo, los localiza y ahora los personajes deben buscar una manera de evitar ser capturados por ellos.`,
    genres: ["Ciencia Ficción", "Drama"],
    favourite: true,
    score: 10,
  },
  {
    id: "A40",
    name: "Piano no Mori",
    author: "Makoto Isshiki / Gaina",
    review: `Buen anime, es de música lo cual siempre es un punto a favor conmigo, pero tampoco me enloquece. La trama está bien, pero la animación no me gustó mucho, se vuelve extraña, casi incomoda, en algunas partes.`,
    plot: `Kai y Shuhei son dos chicos muy diferentes que tienen un punto en común: la música. Mientras que Kai es hijo de una prostituta y aprendió a tocar con un piano abandonado en un bosque cerca de su casa, Shuhei es hijo de dos prestigiosos pianistas. Cuando los dos chicos se conozcan, surgirá una peculiar amistad y el camino de Kai por perfeccionar su técnica con el piano.`,
    genres: ["Música"],
    favourite: false,
    score: 6,
  },
  {
    id: "A41",
    name: "Ginga Eiyuu Densetsu",
    author: " Yoshiki Tanaka / Kitty Films /Production I.G",
    review: `Tanto la serie del 88 como el remake más reciente son excelentes. Para mi es el anime perfecto, tanto los personajes, la historia y las reflexiones filosóficas que contiene. Es una serie para sentarse y pensar sobre lo que nos quiere decir, o llegar a nuestras propias conclusiones. Contiene acción, pero diría que es algo secundario por lo que es difícil de recomendar si es lo único que estás buscando. Pero si queres una historia profunda, que te deje en que pensar, con grandes personajes, entonces este anime es para vos. Recomiendo ver el remake si no te gusta la animación vieja, ambos son excelentes...`,
    plot: `Ginga Eiyuu Densetsu cuenta la historia de dos bandos, el Imperio Galáctico y la Alianza de Planetas Libres. En el bando del Imperio Galactico se encuentra el Almirante Reinhard von Musel, hermano de la protegida del Emperador y en el bando de la Alianza se encuentra el Almirante Yang Wenli. Ambos tienen una visión estratégica impresionante que los lleva a enfrentarse una y otra vez en las batallas. Sin embargo cada uno de ellos es repudiado por sus superiores por motivos distintos. La batalla de los Héroes comienza aquí.`,
    genres: ["Drama", "Ciencia Ficción", "Acción"],
    favourite: true,
    score: 10,
  },
  {
    id: "A42",
    name: "Itsudatte Bokura no Koi wa 10 cm Datta",
    author: "",
    review: `Definitivamente lo ví pero no me acuerdo de nada por lo tanto se queda con un score de 0.`,
    plot: `Bajo el cerezo en flor en la ceremonia de entrada de la Preparatoria Sakuragaoka, Miou Aida se encuentra con Haruki Serizawa por primera vez. "Me llamo Miou, y mi nombre significa 'el lindo cerezo en flor'". "Yo soy Haruki. Significa 'primavera brillante'". Con el inicio de la primavera, ambos sienten cómo se forma un vínculo inexplicable entre ellos. Desde entonces, sus miradas siempre se buscan mutuamente. Miou, que pertenece al club de arte, es una persona reservada, mientras que Haruki, quien forma parte del club de cine, es una persona mucho más activa y social. Pese a sus diferencias en las personalidades, ambos regresan juntos a casa cada día. Son muchos los que los toman por pareja, pero aunque su relación va más allá que la de unos simples amigos, todavía no se declararon su amor. Pero sus sentimientos van creciendo cada día que pasa... Un día Miou no lo aguanta más y de camino a casa pregunta: "Haruki... ¿te gusta alguien?". La respuesta de Haruki es ambigua: "Me gusta alguien... ¿y a ti?". Sus manos están separadas por apenas 10 centímetros, pero esa distancia será difícil de superar.`,
    genres: ["Drama", "Comedia", "Escolar", "Romance"],
    favourite: false,
    score: 0,
  },
  {
    id: "A43",
    name: "Hitorijime My Hero",
    author: "Memeco Arii / Encourage Films",
    review: `Bien pero tampoco una locura`,
    plot: `En esta serie se narra la historia del profesor de instituto Kōsuke Ōshiba y el delincuente e incompetente Masahiro Setagawa. Ambos personajes ya aparecieron en Hitorijime Boyfriend y, de hecho, Kōsuke es el hermano del protagonista de dicho manga, Kensuke.`,
    genres: ["Escolar", "Boys Love"],
    favourite: false,
    score: 6,
  },
  {
    id: "A44",
    name: "Terra Formars",
    author: "Yū Sasuga / Liden Films",
    review: `Un anime de acción decente pero no me gusto para nada el cambio en el eestilo de la animación en la segunda temporada`,
    plot: `Con el programa espacial que intentó viajar a Marte, científicos del siglo XXI fueron encargados con la tarea de calentar el planeta para que así los humanos puedan vivir en su superficie. Tenían un plan eficiente y rentable de enviar cucarachas y moldear la superficie para que así absorbiera la luz del sol y los insectos sirvieran como fuente de comida para el molde. Ahora es el año 2577 y la primera nave tripulada con dirección a Marte ha aterrizado en el planeta y el grupo de seis miembros ya está preparado para su misión. Pero lo que encuentran son gigantescos y mutados humanoides cucarachas con increíble fuerza física. Los miembros de la tripulación son fácilmente eliminados, pero no antes de enviar una transmisión a la Tierra. Ahora, la humanidad enviará a guerreros de élite para exterminara a los insectos mutados y recuperar Marte.`,
    genres: ["Acción", "Ciencia Ficción", "Terror/Psicológico"],
    favourite: false,
    score: 6,
  },
  {
    id: "A45",
    name: "Owari no Seraph",
    author: "Takaya Kagami / Wit Studio",
    review: `Lo poco que recuerdo es que estaba bien pero no destacaba`,
    plot: `Un día, un misterioso virus apareció en la Tierra y liquidó a todos los humanos infectados sobre 13 años. Al mismo tiempo, los vampiros emergieron de lo más profundo del mundo y de la humanidad esclavizada. Hyakuya Yuuichirou, un joven que junto al resto de los niños de su orfanato son tratadas como ganado por lo vampiros. Incluso cautivo, Yuuichirou tiene una gran meta. Él sueña con asesinar a los vampiros. Él sueña con asesinarlos a todos.`,
    genres: ["Drama", "Acción", "Sobrenatural"],
    favourite: false,
    score: 6,
  },
  {
    id: "A46",
    name: "Heavy Object",
    author: "Kazuma Kamachi / J.C.Staff",
    review: `Normal, nada más que decir`,
    plot: `El mundo de Heavy Object están inmerso en una guerra cuyo máximo exponente son los “Objects”, poderosísimas armas capaces de decidir batallas. Milinda, una piloto de Object, conocen a Quenser, un estudiante que desea convertirse en mecánico de Objects, y a Heivia, un soldado novato, en un campo de batalla en Alaska.`,
    genres: ["Acción", "Ciencia Ficción", "Mecha"],
    favourite: false,
    score: 6,
  },
  {
    id: "A47",
    name: "Junjou Romantica",
    author: "Shungiku Nakamura / Studio Deen",
    review: `Lo ví hace mucho y no recuerdo demasiado la verdad. En su momento me gustó pero no se si ahora pensaría lo mismo.`,
    plot: `Misaki Takahashi tiene problemas con sus estudios y necesita un tutor para poder acceder a la carrera de economía en la universidad.De esta forma, Akihiko Usami, un escritor de renombre y amigo de su hermano se convierte en su tutor.En un primer momento no se llevan demasiado bién, ya que Misaki Takahasi descubre que Akihiko Usami es gay, escribe novelas tipo "boys love" y además esta enamorado perdidamente de su hermano, al que usa en sus novelas eróticas. Lo que comienza con una mala relación poco a poco se ira transformando en un romance.Además en la misma linea argumental se incorporarán dos parejas mas relacionadas de alguna manera con la pareja protagonista y con la universidad donde estudia Misaki Takahashi. Así este anime nos mostrara 3 facetas diferentes de tres parejas distintas pero siempre con algo en común: la romántica ( Misaki Takahashi y Akihiko Usami), la egoista (Hiroki Kamijou y Nowaki Kusama ) y la terrorista (You Miyagi y Shinobu Takatsuki ).`,
    genres: ["Drama", "Comedia", "Boys Love", "Romance"],
    favourite: false,
    score: 7,
  },
  {
    id: "A48",
    name: "Hibike! Euphonium",
    author: "Ayano Takeda / Kyoto Animation",
    review: `No es malo, pero tampoco lo recuerdo como algo muy destacable. Que sea de música ayuda para engancharme, pero no es suficiente`,
    plot: `La historia comienza cuando Kumiko Oumae, una chica que estaba en club de banda de instrumentos de bronce en secundaria, visita su club esta vez como estudiante de primer año de preparatoria. Las compañeras de Kumiko, Hazuki y Sapphire deciden unirse al club, pero Kumiko ve a su antigua compañera Reina y comienza a dudar. Ella recuerda el incidente que tuvo con Reina en su antiguo club de instrumentos de bronce.`,
    genres: ["Drama", "Escolar", "Música"],
    favourite: false,
    score: 6,
  },
  {
    id: "A50",
    name: "Zankyō no Terror",
    author: "Mappa",
    review: `Nada del otro mundo`,
    plot: `Un día de verano… De repente, un ataque bomba de un grupo terrorista azota Tokio. Los culpables de tal acto que ha despertado a toda una nación complaciente, fueron dos simples muchachos. Ahora a los culpables se les conoce como “Sphinx” y dan comienzo a un juego a gran escala que involucra a todo Japón.`,
    genres: ["Terror/Psicológico"],
    favourite: false,
    score: 6,
  },
  {
    id: "A51",
    name: "Ao Haru Ride",
    author: "Io Sakisaka / Production I.G",
    review: `Tengo el manga completo y es una lástima que no lo hayan adoptado completo en el anime. De todas formas, está muy bueno y vale la pena verlo`,
    plot: `Ao Haru Ride gira en torno a Futaba, una chica que en secundaria estaba enamorada de un chico llamado Ko Tanaka. Sin embargo, tras un malentendido, su relación como amigos finaliza cuando él cambia de escuela durante las vacaciones de verano. En el instituto, el mundo de Futaba se pone del revés al coincidir nuevamente con Ko, que ahora se llama Ko Mabuchi.`,
    genres: ["Comedia", "Drama", "Escolar", "Romance"],
    favourite: false,
    score: 8,
  },
  {
    id: "A52",
    name: "Sword Art Online II",
    author: "A-1 Pictures",
    review: `No. Peor que la primera`,
    plot: `Phantom Bullet transcurre un año después de completarse SAO, cuando Kirito recibe una llamada del investigador Seijirou Kikuoka para hablar de un extraño caso relacionado con el juego Gun Gale Online. Un misterioso jugador llamado Death Gun es capaz de matar a personajes en el juego y, a su vez, matar a quienes los controlan en el mundo real. Kirito entrará en el juego para investigar cómo es eso posible y allí conocerá a Sinon, que será su guía en este nuevo mundo.`,
    genres: ["Acción", "Aventura", "Fantasia"],
    favourite: false,
    score: 4,
  },
  {
    id: "A53",
    name: "Sword Art Online",
    author: "A-1 Pictures",
    review: `Para su momento fue entretenida pero no, no merece el 6 que le estoy dando...`,
    plot: `Escapar es imposible hasta terminar el juego; un game over significaría una verdadera "muerte". Sin saber la "verdad" de la siguiente generación del Multijugador Masivo Online, 'Sword Art Online(SAO)', con 10 mil usuarios unidos juntos abriendo las cortinas para esta cruel batalla a muerte. Participando solo en SAO, el protagonista Kirito ha aceptado inmediatamente la "verdad" de este MMO. <br/><br/> Y, en el mundo del juego, un gigante castillo flotante llamado 'Aincrad', Kirito se distinguió a si mismo como un jugador solitario. Apuntando a terminar el juego al alcanzar la planta mas alta el solo continua avanzando arriesgadamente hasta que recibe una invitación a la fuerza de una guerrera y esgrimista experta, Asuna, con la cual tendra que hacer equipo.`,
    genres: ["Acción", "Aventura", "Fantasia"],
    favourite: false,
    score: 6,
  },
  {
    id: "A54",
    name: "No Game No Life",
    author: "Yū Kamiya / Madhouse",
    review: `En su momento me gustaba, es decente`,
    plot: `La historia está protagonizada por Sora y Shiro, hermano y hermana, que son muy famosos en todo Internet como NEETs y hikikomoris que se pasan el día jugando a videojuegos, tanto que son una leyenda. Los dos consideran el mundo real como “un juego malo”. Un día, un chico llamado “Dios” les invoca a otro mundo. Allí, Dios ha prohibido las guerras y declara que en el mundo todo se decidirá mediante juegos, incluso cuáles serán las fronteras entre países. La humanidad se ha visto reducida a una sola ciudad debido a que el resto de razas le han ido quitando todo el territorio. Shiro y Sora tendrán que ser los salvadores de la humanidad en este mundo alternativo.`,
    genres: ["Fantasia", "Comedia", "Aventuras"],
    favourite: false,
    score: 6,
  },
  {
    id: "A55",
    name: "Gokukoku no Brynhildr",
    author: "Lynn Okamoto / Arms",
    review: `En su momento no me gustó y si antes no me gustó ahora de seguro menos`,
    plot: `Cuando era un niño, Murakami estaba enamorado de una chica que llamó Kuroneko. Ella insistió en saber acerca de los extraterrestres y que se reunió con ellos, pero nadie le creyó, incluso el joven Murakami se mostró escéptico. Un día, ella decide mostrarle a los extraterrestres, hasta que se produce un accidente y muere mientras Kuroneko Murakami se queda gravemente herido en el hospital. Pasan los años y Murakami se obsesiona en la búsqueda de pruebas de la existencia de los extraterrestres debido a una promesa que había hecho con Kuroneko. Entonces, un día, una nueva estudiante llega a su clase, que se parece mucho a Kuroneko, pero su nombre es Kuroha Neko!`,
    genres: ["Ciencia Ficción", "Drama"],
    favourite: false,
    score: 2,
  },
  {
    id: "A56",
    name: "Valvrave the Liberator",
    author: "Sunrise",
    review: ``,
    plot: `Kakumeiki Valvrave tiene lugar en una era en la que el 70% de la raza humana vive en el espacio debido al desarrollo de colonias o ciudades espaciales. Entre dos poderosas facciones, la Federación Militar Dorushia y los Estados Unidos del Anillo Atlántico, se sitúa una pequeña nación neutral llamada Jiooru que ha prosperado económicamente. El protagonista, Haruto Tokishima, es un estudiante de instituto que vive en Jiooru. Cuando el ejército de Dorushia invade Jiooru, Haruto encontrará el arma de forma humanoide conocido como Valvrave.`,
    genres: ["Acción", "Ciencia Ficción", "Mecha"],
    favourite: false,
    score: 7,
  },
  {
    id: "A57",
    name: "Phi Brain: Kami no Puzzle",
    author: "Sunrise",
    review: `Entretenido anime en el que los personajes tienen que resolver puzzles`,
    plot: `La historia gira en torno a Kaito, un nuevo estudiante de la Academia Root, que es aficionado a los puzzles. Es seleccionado como candidato para el Phi Brain por sus increíbles habilidades mentales. Un día él y su amiga de la infancia Nonoha se encuentran en unas ruinas cercanas a la academia lo que se conoce como el puzzle imposible de resolver. El puzzle resulta ser una prueba de una organización llamada POG, y al resolverlo se convertira en el Solver, con lo que irá por el mundo resolviendo otros tantos puzzles supuestamente imposibles.`,
    genres: ["Acción", "Drama"],
    favourite: false,
    score: 7,
  },
  {
    id: "A58",
    name: "Neon Genesis Evangelion",
    author: "Hideaki Anno / Gainax",
    review: `Simplemente perfecto. Un clásico que todo el mundo tendría que ver, desde la serie original hasta las películas más recientes.`,
    plot: ``,
    genres: ["Acción", "Drama", "Mecha", "Terror/Psicológico"],
    favourite: true,
    score: 10,
  },
  {
    id: "A59",
    name: "Zetsuen no Tempest",
    author: "Sano y Ren Saizaki / Bones",
    review: `Estoy un poco olvidado de los detalles pero recuerdo que me gustó mucho cuando la vi. Tenía varios giros y general era entretenida.`,
    plot: `Yoshino y Mahiro son amigos de la infancia. Cuando la familia de Mahiro es asesinada, éste decide investigar el caso y desaparece. Al mes, una mujer llamada Evangeline Yamato, confronta a su amigo sobre su paradero. Ella le explica que en los lugares a los que Mahiro había ido se habían desencadenado epidemias. Es entonces, cuando Mahiro reaparece y rescata a su amigo. Tal parece que hizo un pacto con una poderosa hechicera para encontrar al asesino de su familia.`,
    genres: ["Acción", "Drama", "Fantasia", "Terror/Psicológico"],
    favourite: false,
    score: 8,
  },
  {
    id: "A60",
    name: "Uchuu Senkan Yamato 2199",
    author: "AIC / Xebec ",
    review: `Muy bueno y entretenido. Si se quiere no tiene nada muy original pero está bien hecho. Para aclara no vi el original, solo este remake`,
    plot: `Es el año 2199. La última flota de la Tierra va a una misión en Plutón donde es destruida por alienígenas. El Almirante Okita es herido al cumplir la mision llamada "Operación M", donde el objetivo era distraer al enemigo y cambiar su posición. En la misión murió el hermano de Kodai Susumu, un joven soldado que en Marte encuentra un dispositivo que al parecer lleva un mensaje. Mientras tanto el Almirante Okita no se rendira hasta liberar a la humanidad de este enemigo extraterrestre que lucha con ellos desde hace ocho años.`,
    genres: ["Acción", "Ciencia Ficción", "Drama"],
    favourite: false,
    score: 8,
  },
  {
    id: "A61",
    name: "Hyouka",
    author: "Honobu Yonezawa / Kyoto Animation",
    review: `Lindo anime para ver, siempre lo recuerdo con cariño. Tirar un paquete de harina nunca fue tan significativo para un personaje... Lástima que nunca lo siguieron.`,
    plot: `La historia sigue a un muchacho llamado Houtarou que se une al club de literatura clásica por orden de su hermana mayor, aunque él prefiere no involucrarse en nada. En el club se va acercando poco a poco a la verdad tras cierto incidente relacionado con el tío de una muchacho del mismo y que ocurrió 33 años atrás. Él acabará viéndose arrastrado a resolver el misterio por otra chica.`,
    genres: ["Drama", "Escolar", "Romance"],
    favourite: true,
    score: 9,
  },
  {
    id: "A62",
    name: "Sakamichi no Apollon",
    author: "Yuki Kodama / Mappa",
    review: `Otro anime de música, pero este sí que está bien hecho. Los personajes están bien hechos y uno logra simpatizar con los conflictos que ellos enfrentan`,
    plot: `A principios de verano de 1966, Kaoru es trasladado a la escuela secundaria local de Yokosuka. Gracias a su familia en constante movimiento de pueblo en pueblo, Kaoru conoce la escuela como un lugar difícil en el que encajar. Sin embargo, en su primer día en esta nueva escuela, conoce a un chico y comienza una nueva dirección en su vida.`,
    genres: ["Drama", "Escolar", "música", "Romance"],
    favourite: true,
    score: 9,
  },
  {
    id: "A63",
    name: "Kimi to Boku",
    author: "Kiichi Hotta / J.C.Staff",
    review: ``,
    plot: `La historia gira en torno a los gemelos Yuta y Yuki Asaba, el afeminado Shun Matsuoka y el líder de la clase Kaname Tsukuhara, todos ellos se conocen desde la infancia, aunque eso no signifique que sean los mejores amigos. Una estudiante recientemente transferida al colegio de los chicos, Chizuru Tachibana, entra al círculo de estos amigos, en una comedia sobre el día a día de un grupo de adolescentes.`,
    genres: ["Comedia", "Drama", "Escolar", "Romance"],
    favourite: false,
    score: 7,
  },
  {
    id: "A64",
    name: "Sekaiichi Hatsukoi",
    author: "Shungiku Nakamura / Studio Deen",
    review: ``,
    plot: `Onodera Ritsu decide transferirse de la compañía de su padre a Marukawa Shoten. donde es asignado a la división de manga shoujo, ahí se encontrara con la persona que menos espera, su ex amor de secundaria`,
    genres: ["Comedia", "Boys Love", "Romance", "Drama"],
    favourite: false,
    score: 7,
  },
  {
    id: "A65",
    name: "No. 6",
    author: "Atsuko Asano / Bones",
    review: ``,
    plot: `Basada en la novela de ciencia-ficcion de Asano Atsuko, creador de "Telepathy Shoujo Ran". La historia se situa en "No.6" una ciudad futurista en el año 2013. Habitada por una elite de alto rango desde hace 2 años, un chico llamado Shion vive en una zona exclusiva de "No.6". En la noche de su decimo-segundo cumpleaños rescata a un Tipo que se llama "Nezumi" . Nezumi escapó de los agentes de seguridad en la ciudad especial, a partir de ese momento, cambió la vida de Shion para siempre...`,
    genres: ["Acción", "Ciencia Ficción", "Romance"],
    favourite: false,
    score: 7,
  },
  {
    id: "A66",
    name: "Kimi ni Todoke",
    author: "Karuho Shiina / Production I.G",
    review: ``,
    plot: `Sawako Kuronuma, llamada Sadako por sus compañeras por su parecido con el personaje de Ringu (película original del remake estadounidense The Ring), siempre se ha entendido mal y teme por su apariencia. Hay rumores de que Sawako puede ver fantasmas y es una maldición para las personas. Pero cuando su ídolo, el popular muchacho Kazehaya, comienza a hablar con ella, todo cambia. Se encuentra en un nuevo mundo, tratando de hacer amigos y hablar con gente diferente y no puede agradecer lo suficiente a Kazehaya por darle estas oportunidades. Lento pero seguro, florece un dulce amor entre los dos, ya que superará cualquier circunstancia y obstáculos en el camino.`,
    genres: ["Drama", "Romance", "Escolar"],
    favourite: false,
    score: 7,
  },
  {
    id: "A67",
    name: "Heroic Age",
    author: "Xebec",
    review: ``,
    plot: `Respondiendo al llamado de la "Raza de Oro" (Gold Race), todas las razas se van al espacio. La raza humana es la ultima en salir, y por ello son conocidos como la "Raza de Hierro".Mucho tiempo ha pasado desde eso, y la humanidad es amenazada con la extinción a manos de la dominante "Raza de Plata". Para poder salvar a su gente, la Princesa Deianeira se embarca en una aventura a una galaxia muy lejana, siguiendo las profecías de la Raza Dorada heredadas por la familia real. Ella conoce a Eiji, juntos cambiaran el destino del universo.`,
    genres: ["Acción", "Ciencia Ficción", "Mecha"],
    favourite: false,
    score: 7,
  },
  {
    id: "A68",
    name: "Gakuen Heaven",
    author: "Spray",
    review: ``,
    plot: `Ito Keita es un chico que podríamos llamar ordinario; no tiene ningún talento que lo haga destacar sobre un muchacho común y corriente de instituto; por eso se sorprende cuando le llega una carta anunciándole una plaza en la escuela Bell Liberty, conocida por albergar a chicos con grandes dotes y talentos: Keita se siente opacado y fuera de lugar, pero conoce a Endo Kazuki; también alumno de Bell Liberty, quien le devuelve la confianza y se convierte en su intimo amigo; pero hay un misterio tras la plaza de Keita en esta escuela; ¿Por qué un alumno sin talento tiene lugar en un colegio tan prestigioso?; junto con su nuevo amigo Kazuki (quien parece tener una doble vida), Keita lo ira descubriendo a medida que se ira enamorando de este.`,
    genres: ["Boys Love", "Romance", "Comedia", "Escolar"],
    favourite: false,
    score: 7,
  },
  {
    id: "A69",
    name: "Blood+",
    author: "Production I.G",
    review: `Lo vi hace mucho pero por lo que recuerdo estaba bien.`,
    plot: `Saya es una estudiante que lleva una vida tranquila con su familia, con una excepción: ella no recuerda nada acerca de su vida anterior al último año. Un día, un inesperado evento transforma su pacífica vida en una aventura caótica. Un apuesto músico que viste de negro se aparece ante ella, su nombre es Hagi(pronunciado:hatgi). En el momento en que pone en sus manos una katana, la historia comienza un nuevo curso.`,
    genres: ["Acción", "Sobrenatural", "Terror/Psicológico"],
    favourite: false,
    score: 7,
  },
  {
    id: "A70",
    name: "Howl no Ugoku Shiro",
    author: "Studio Ghibli",
    review: `Excelente película. Si algo nos tiene que quedar es que a veces las apariencias engañan y más importante que nuestro exterior es lo que sentimos en nuestro interior.`,
    plot: `El día que Sophie decide visitar a su hermana, tiene un encuentro desafortunado con un par de guardias, y es ayudada por un misterioso mago. Durante la huida, extraños hombres de goma comienzan a perseguirlos. Más tarde, Sophie se entera que su salvador no era nada más ni nada menos que el mago Howl, famoso por su afición por robar los corazones de las muchachas jóvenes. Esa misma noche, la Bruja Calamidad hace una visita nocturna a Sophie y le echa un maleficio, sometiéndola a ser una anciana a partir de ese día. Por esa misma razón, la chica decide dejar su casa y en su viaje hacia las montañas encuentra un castillo que vaga por los campos y valles, y comienza a trabajar ahí.`,
    genres: ["Drama", "Aventura", "Fantasia"],
    favourite: true,
    score: 10,
  },
  {
    id: "A71",
    name: "Spirited Away",
    author: "Studio Ghibli",
    review: `Otra muy buena película, es simplemente mágica.`,
    plot: `Se trata de Chihiro, quien con sus padres se mudan a vivir a otra cuidad, aunque ella no esta de acuerdo con dicha decision. Al no encontrar el camino correcto a casa, se pierden en un bosque misterioso; llegan al final del camino y se encuentran de frente a un tunel. Al llegar al otro lado del tunel encuentran un pueblito deshabitado pero con muchos restaurantes, al no encontrarse nadie, sus padres deciden empezar a comer y pagar luego. Al ponerse el sol se convierten en cerdos. Ahora Chihiro tienen que hacer lo imposible para hacer que sus padres vuelven a la normalidad y asi llevarselos de vuelta a casa. Es la única película en la historia del anime que ganó un premio Oscar por animación`,
    genres: ["Aventura", "Drama", "Fantasia"],
    favourite: true,
    score: 9,
  },
  {
    id: "A72",
    name: "La colina de las amapolas",
    author: "Studio Ghibli",
    review: `Mi película favorita del estudio Gibli. No tendríamos que olvidarnos del pasado porque lo necesitamos para darle significado al presente y ayudarnos a entender quienes somos.`,
    plot: `La historia se desarrolla en el Japón de 1963. Umi Matsuzaki es una estudiante de secundaria que, en ausencia de su madre, cuida a sus dos hermanos menores, Sora y Riku, así como también de su abuela, a la par que administra una pensión de estilo occidental llamada el Coquelicot Manor, ubicada en lo alto de una colina y cercana al mar. Umi compagina tranquilamente sus responsabilidades con su vida escolar. Un día conoce a Shun Kazama, un muchacho miembro del club de periodismo, y Shirō Mizunuma, presidente del consejo estudiantil. Ambos son representantes del Quartier Latin, un edificio antiguo que alberga las diferentes asociaciones y grupos de estudiantes y que corre peligro de ser demolido por la renovación de edificios con motivo de los Juegos Olímpicos de Tokio de 1964. Entre Umi y Kazama surgirá una profunda amistad que podría verse complicada con el inesperado descubrimiento de un secreto del pasado. Juntos descubrirán una forma de convivir entre el turbio pasado, el difícil presente y el esperanzador futuro en un momento del tiempo donde Japón empezaba a levantar cabeza`,
    genres: ["Drama", "Romance"],
    favourite: true,
    score: 10,
  },
  {
    id: "A73",
    name: "Kiki: Entregas a domicilio",
    author: "Studio Ghibli",
    review: ``,
    plot: `Al cumplir los 13 años, la brujita Kiki debe, como manda la tradición, abandonar su casa. Así llega a una ciudad donde un panadero la contrata para repartir el pan con su escoba. Un día, Kiki descubre que ya no puede hacerla levitar.`,
    genres: ["Drama", "Fantasia"],
    favourite: false,
    score: 8,
  },
  {
    name: "Doukyuusei",
    author: "Shoko Nakamura",
    plot: `Una tierna historia de amor entre dos compañeros de clase en una escuela secundaria masculina. Rihito Sajou, un estudiante sobresaliente, y Hikaru Kusakabe, un guitarrista en una banda de rock, desarrollan una profunda conexión mientras se preparan para el festival de coro de la escuela.`,
    genres: ["Romance", "Boys Love", "Drama"],
    id: "A74",
    review: `Muy linda película que vuelvo a ver cada tanto`,
    favourite: true,
    score: 8,
  },
  {
    name: "Un Extraño a la Orilla del Mar",
    author: "Akiyo Ohashi",
    plot: `Shun Hashimoto, un aspirante a novelista, y Mio Chibana, un joven estudiante de secundaria, se encuentran en una tranquila isla. Ambos desarrollan una profunda conexión, pero Mio repentinamente deja la isla. Tres años después, regresa para enfrentar sus sentimientos por Shun y explorar su relación mientras lidian con sus propios miedos e inseguridades.`,
    genres: ["Romance", "Drama", "Boys Love"],
    id: "A75",
    review: ``,
    favourite: false,
    score: 7,
  },
];

export default completedAnimes;
