// start id with M1
let completedMovies = [
  {
    id: "M1",
    name: "Star Wars - Episodio I: La amenaza fantasma",
    author: "George Lucas",
    plot: `Ambientada treinta años antes que "La guerra de las galaxias" (1977), muestra la infancia de Darth Vader, el pasado de Obi-Wan Kenobi y el resurgimiento de los Sith, los caballeros Jedi dominados por el Lado Oscuro. La Federación de Comercio ha bloqueado el pequeño planeta de Naboo, gobernado por la joven Reina Amidala; se trata de un plan ideado por Sith Darth Sidious, que, manteniéndose en el anonimato, dirige a los neimoidianos, que están al mando de la Federación. El Jedi Qui-Gon Jinn y su aprendiz Obi-Wan Kenobi convencen a Amidala para que vaya a Coruscant, la capital de la República y sede del Consejo Jedi, y trate de neutralizar esta amenaza. Pero, al intentar esquivar el bloqueo, la nave real resulta averiada, viéndose así obligada la tripulación a aterrizar en el desértico y remoto planeta de Tatooine...`,
    review: `Pasable, ni lejos de ser de mis favoritas dentro de la saga`,
    genres: ["Ciencia ficción", "Aventuras", "Acción"],
    favourite: false,
    score: 5,
  },
  {
    id: "M2",
    name: "Star Wars - Episodio II: El ataque de los clones",
    author: "George Lucas",
    plot: `Corren tenebrosos tiempos para la República, que continúa envuelta en luchas y sumida en el caos. Un movimiento separatista, formado por centenares de planetas y poderosas alianzas encabezadas por el misterioso conde Dooku, amenaza la galaxia. Ni siquiera los Jedi parecen capaces de conjurar el peligro. Este movimiento provoca el estallido de las guerras clones, que representa el principio del fin de la República. Para allanar el camino, los separatistas intentan asesinar a la senadora Padme Amidala. Para evitar futuros atentados, su seguridad es encomendada a dos caballeros Jedi... `,
    review: `De chico era de mis favoritas, con el tiempo le perdí un poco el aprecio`,
    genres: ["Ciencia ficción", "Aventuras", "Acción"],
    favourite: false,
    score: 6,
  },
  {
    id: "M3",
    name: "Star Wars - Episodio III Revenge of the Sith",
    author: "George Lucas",
    plot: `Último capítulo de la trilogía de precuelas de Star Wars, en el que Anakin Skywalker definitivamente se pasa al lado oscuro. En el Episodio III aparece el General Grievous, un ser implacable mitad-alien mitad-robot, el líder del ejército separatista Droid. Los Sith son los amos del lado oscuro de la Fuerza y los enemigos de los Jedi. Fueron prácticamente exterminados por los Jedi hace mil años, pero esta orden del mal sobrevivió en la clandestinidad.`,
    review: `De las precuelas es mi favorita, de todas formas, no me genera grandes pasiones.`,
    genres: ["Ciencia ficción", "Aventuras", "Acción"],
    favourite: false,
    score: 7,
  },
  {
    id: "M4",
    name: "Star Wars - Episodio IV: Una nueva esperanza",
    author: "George Lucas",
    plot: `La princesa Leia, líder del movimiento rebelde que desea reinstaurar la República en la galaxia en los tiempos ominosos del Imperio, es capturada por las Fuerzas Imperiales, capitaneadas por el implacable Darth Vader, el sirviente más fiel del Emperador. El intrépido y joven Luke Skywalker, ayudado por Han Solo, capitán de la nave espacial "El Halcón Milenario", y los androides, R2D2 y C3PO, serán los encargados de luchar contra el enemigo e intentar rescatar a la princesa para volver a instaurar la justicia en el seno de la galaxia.`,
    review: ``,
    genres: ["Ciencia ficción", "Aventuras", "Acción"],
    favourite: false,
    score: 7,
  },
  {
    id: "M5",
    name: "Star Wars - Episodio V: El imperio contraataca",
    author: "George Lucas",
    plot: `Tras un ataque sorpresa de las tropas imperiales a las bases camufladas de la alianza rebelde, Luke Skywalker, en compañía de R2D2, parte hacia el planeta Dagobah en busca de Yoda, el último maestro Jedi, para que le enseñe los secretos de la Fuerza. Mientras, Han Solo, la princesa Leia, Chewbacca, y C3PO esquivan a las fuerzas imperiales y piden refugio al antiguo propietario del Halcón Milenario, Lando Calrissian, en la ciudad minera de Bespin, donde les prepara una trampa urdida por Darth Vader.`,
    review: `Icónica sin duda`,
    genres: ["Ciencia ficción", "Aventuras", "Acción"],
    favourite: true,
    score: 9,
  },
  {
    id: "M6",
    name: "Star Wars - Episodio VI: El retorno del Jedi",
    author: "George Lucas",
    plot: `Para ir a Tatooine y liberar a Han Solo, Luke Skywalker y la princesa Leia deben infiltrarse en la peligrosa guarida de Jabba the Hutt, el gángster más temido de la galaxia. Una vez reunidos, el equipo recluta a tribus de Ewoks para combatir a las fuerzas imperiales en los bosques de la luna de Endor. Mientras tanto, el Emperador y Darth Vader conspiran para atraer a Luke al lado oscuro, pero el joven está decidido a reavivar el espíritu del Jedi en su padre. La guerra civil galáctica termina con un último enfrentamiento entre las fuerzas rebeldes unificadas y una segunda Estrella de la Muerte, indefensa e incompleta, en una batalla que decidirá el destino de la galaxia.`,
    review: ``,
    genres: ["Ciencia ficción", "Aventuras", "Acción"],
    favourite: false,
    score: 8,
  },
  {
    id: "M7",
    name: "Rogue One: Una historia de Star Wars",
    author: "Gareth Edwards / Otros",
    plot: `El Imperio Galáctico ha terminado de construir el arma más poderosa de todas, la Estrella de la muerte, pero un grupo de rebeldes decide realizar una misión de muy alto riesgo: robar los planos de dicha estación antes de que entre en operaciones, mientras se enfrentan también al poderoso Lord Sith conocido como Darth Vader, discípulo del despiadado Emperador Palpatine. Historia ambientada entre los episodios III y IV de Star Wars.`,
    review: `Dejando aparte la trilogía original, la mejor película de Star Wars`,
    genres: ["Ciencia ficción", "Bélico", "Acción"],
    favourite: true,
    score: 8,
  },
  {
    id: "M8",
    name: "Star Wars: El despertar de la Fuerza",
    author: "J.J. Abrams",
    plot: `Treinta años después de la victoria de la Alianza Rebelde sobre la segunda Estrella de la Muerte (hechos narrados en el Episodio VI: El retorno del Jedi), la galaxia está todavía en guerra. Una nueva República se ha constituido, pero una siniestra organización, la Primera Orden, ha resurgido de las cenizas del Imperio Galáctico. A los héroes de antaño, que luchan ahora en la Resistencia, se suman nuevos héroes: Poe Dameron, un piloto de caza, Finn, un soldado desertor de la Primera Orden, Rey, una joven chatarrera, y BB-8, un androide rodante. Todos ellos luchan contra las fuerzas del Mal: el Capitán Phasma, de la Primera Orden, y Kylo Ren, un temible y misterioso personaje que empuña un sable de luz roja`,
    review: `Pasable, solo pasable. No trae nada nuevo.`,
    genres: ["Ciencia ficción", "Aventuras", "Acción"],
    favourite: false,
    score: 6,
  },
  {
    id: "M9",
    name: "Star Wars: Los últimos Jedi",
    author: "Rian Johnson",
    plot: `La malvada Primera Orden se ha vuelto más poderosa y tiene contra las cuerdas a la Resistencia, liderada por la General Leia Organa (Carrie Fisher). El piloto Poe Dameron (Oscar Isaac) encabeza una misión para intentar destruir un acorazado de la Primera Orden. Mientras tanto, la joven Rey (Daisy Ridley) tendrá que definir su futuro y su vocación, y el viejo jedi Luke Skywalker (Mark Hamill) revaluar el significado de su vida.`,
    review: `Destruyó Star Wars para mí, te odio Disney!`,
    genres: ["Ciencia ficción", "Aventuras", "Acción"],
    favourite: false,
    score: 3,
  },
  {
    id: "M10",
    name: "Star Wars: El ascenso de Skywalker",
    author: "J.J. Abrams",
    plot: `Un año después de los eventos de "Los últimos Jedi", los restos de la Resistencia se enfrentarán una vez más a la Primera Orden, involucrando conflictos del pasado y del presente. Mientras tanto, el antiguo conflicto entre los Jedi y los Sith llegará a su clímax, lo que llevará a la saga de los Skywalker a un final definitivo. Final de la trilogía iniciada con "El despertar de la Fuerza".`,
    review: `Terrible, de todas formas mejor que la anterior pero eso es pedir muy poco`,
    genres: ["Ciencia ficción", "Aventuras", "Acción"],
    favourite: false,
    score: 4,
  },
  {
    id: "M11",
    name: "El señor de los anillos: La comunidad del anillo",
    author: "Peter Jackson / J.R.R. Tolkien",
    plot: `En la Tierra Media, el Señor Oscuro Sauron ordenó a los Elfos que forjaran los Grandes Anillos de Poder. Tres para los reyes Elfos, siete para los Señores Enanos, y nueve para los Hombres Mortales. Pero Saurón también forjó, en secreto, el Anillo Único, que tiene el poder de esclavizar toda la Tierra Media. Con la ayuda de sus amigos y de valientes aliados, el joven hobbit Frodo emprende un peligroso viaje con la misión de destruir el Anillo Único. Pero el malvado Sauron ordena la persecución del grupo, compuesto por Frodo y sus leales amigos hobbits, un mago, un hombre, un elfo y un enano. La misión es casi suicida pero necesaria, pues si Sauron con su ejército de orcos lograra recuperar el Anillo, sería el final de la Tierra Media.`,
    review: `El inicio de una excelente trilogía, sin duda unos clásicos y se encuentran entre las películas que más vi de chico.`,
    genres: ["Fantasía", "Aventuras", "Acción"],
    favourite: false,
    score: 8,
  },
  {
    id: "M12",
    name: "El señor de los anillos: Las dos torres",
    author: "Peter Jackson / J.R.R. Tolkien",
    plot: `Tras la disolución de la Compañía del Anillo, Frodo y su fiel amigo Sam se dirigen hacia Mordor para destruir el Anillo Único y acabar con el poder de Sauron, pero les sigue un siniestro personaje llamado Gollum. Mientras, y tras la dura batalla contra los orcos donde cayó Boromir, el hombre Aragorn, el elfo Legolas y el enano Gimli intentan rescatar a los medianos Merry y Pipin, secuestrados por los orcos de Mordor. Por su parte, Saurón y el traidor Sarumán continúan con sus planes en Mordor, a la espera de la guerra contra las razas libres de la Tierra Media.`,
    review: `Excelente continuación luego de la primera y en mi opinión incluso mejor. La música es un elemento esencial de la trilogía y sin duda alguna Howard Shore hizo un excelente trabajo. `,
    genres: ["Fantasía", "Aventuras", "Acción"],
    favourite: true,
    score: 10,
  },
  {
    id: "M13",
    name: "El señor de los anillos: El retorno del rey",
    author: "Peter Jackson / J.R.R. Tolkien",
    plot: `Las fuerzas de Saruman han sido destruidas, y su fortaleza sitiada. Ha llegado el momento de decidir el destino de la Tierra Media, y, por primera vez, parece que hay una pequeña esperanza. El interés del señor oscuro Sauron se centra ahora en Gondor, el último reducto de los hombres, cuyo trono será reclamado por Aragorn. Sauron se dispone a lanzar un ataque decisivo contra Gondor. Mientras tanto, Frodo y Sam continuan su camino hacia Mordor, con la esperanza de llegar al Monte del Destino`,
    review: `El final perfecto para la trilogía y de esta increíble adaptación al cine.`,
    genres: ["Fantástico", "Aventuras", "Acción"],
    favourite: true,
    score: 10,
  },
  {
    id: "M15",
    name: "Harry Potter y la Piedra Filosofal",
    author: "J.K. Rowling",
    plot: `Esta es la primera película de la serie de Harry Potter, donde seguimos a Harry mientras descubre que es un mago y asiste a la Escuela de Magia y Hechicería de Hogwarts. Junto con sus amigos Ron y Hermione, Harry descubre la verdad sobre la Piedra Filosofal que otorga la inmortalidad.`,
    genres: ["Fantasía", "Aventura", "Familia"],
    review: `El inicio de una excelente trilogía que apasiona tanto a niños, jóvenes y adultos. Sin duda uno de los mayores éxitos de nuestro tiempo y ahora de adulto he llegado a apreciarlas incluso más que cuando era chico. `,
    favourite: false,
    score: 7,
  },
  {
    id: "M16",
    name: "Harry Potter y la Cámara Secreta",
    author: "J.K. Rowling",
    plot: `En esta segunda película, Harry Potter regresa a Hogwarts a pesar de las advertencias de un elfo doméstico llamado Dobby. Harry y sus amigos investigan una serie de ataques misteriosos en la escuela y descubren la existencia de la Cámara Secreta, así como la verdad sobre el heredero de Slytherin.`,
    genres: ["Fantasía", "Aventura", "Familia"],
    review: `De chico era mi favorita e incluso es la primera que “vi” de la saga. Sin duda alguna es la que más he visto `,
    favourite: false,
    score: 8,
  },
  {
    id: "M17",
    name: "Harry Potter y el Prisionero de Azkaban",
    author: "J.K. Rowling",
    plot: `En la tercera entrega de la serie, Harry Potter se enfrenta al peligro que representa Sirius Black, un prisionero fugado de la prisión de Azkaban que se cree que es un aliado de Lord Voldemort. Harry aprende más sobre su pasado y descubre la verdad sobre el padrino que nunca supo que tenía.`,
    genres: ["Fantasía", "Aventura", "Familia"],
    review: `¡La mejor de la saga! Si hay viajes en el tiempo, es un éxito instantáneo en mi libro.`,
    favourite: true,
    score: 10,
  },
  {
    id: "M18",
    name: "Harry Potter y el Cáliz de Fuego",
    author: "J.K. Rowling",
    plot: `En la cuarta película, Harry es misteriosamente seleccionado para participar en el peligroso Torneo de los Tres Magos. A lo largo de la competencia, Harry enfrenta desafíos mortales, traiciones y descubre la resurrección de Lord Voldemort.`,
    genres: ["Fantasía", "Aventura", "Familia"],
    review: `Por lo que tengo entendido en el libro suceden muchas más cosas que las que se ven en la película, de todas formas es muy entretenida. `,
    favourite: false,
    score: 7,
  },
  {
    id: "M19",
    name: "Harry Potter y la Orden del Fénix",
    author: "J.K. Rowling",
    plot: `En la quinta película, Harry enfrenta desafíos y revelaciones mientras lucha contra la negativa del Ministerio de Magia a aceptar el regreso de Lord Voldemort. La Orden del Fénix, un grupo secreto, se reúne para combatir a las fuerzas oscuras.`,
    genres: ["Fantasía", "Aventura", "Familia"],
    review: `Muy bueno poder ver las reacciones al regreso de Voldemort y sin duda alguna Madam Umbridge, aunque de los personajes más odiables de la saga, sin duda es icónico. La pelea final es excelente y no hay ninguna otra, al menos en las películas, que se compare con esta. Una perdida muy grande para Harry y los espectadores nos espera en esta entrega...`,
    favourite: false,
    score: 9,
  },
  {
    id: "M20",
    name: "Harry Potter y el Misterio del Príncipe",
    author: "J.K. Rowling",
    plot: `En la sexta película, Harry descubre un antiguo libro de pociones marcado como propiedad del Misterioso Príncipe y comienza a aprender más sobre el oscuro pasado de Lord Voldemort. Mientras tanto, Hogwarts se ve amenazada por fuerzas oscuras que se fortalecen.`,
    genres: ["Fantasía", "Aventura", "Familia"],
    review: `Descubrimos un montón de cosas importantes para la saga y lamentablemente perdemos uno de los personajes más icónicos, ya nos encaminamos hacia el final. `,
    favourite: false,
    score: 7,
  },
  {
    id: "M21",
    name: "Harry Potter y las Reliquias de la Muerte - Parte 1",
    author: "J.K. Rowling",
    plot: `En la primera parte de la séptima película, Harry, Ron y Hermione se embarcan en una peligrosa misión para destruir los Horrocruxes, los objetos que contienen fragmentos del alma de Voldemort. Mientras tanto, el mundo mágico se encuentra en guerra y la seguridad de Hogwarts ya no está garantizada.`,
    genres: ["Fantasía", "Aventura", "Familia"],
    review: `Esta primera parte no me gustan demasiado pero es el inicio del final.   `,
    favourite: false,
    score: 7,
  },
  {
    id: "M22",
    name: "Harry Potter y las Reliquias de la Muerte - Parte 2",
    author: "J.K. Rowling",
    plot: `En la segunda parte de la séptima película, la batalla final entre las fuerzas del bien y del mal del mundo mágico estalla. Harry, Ron y Hermione continúan su tarea de destruir los Horrocruxes restantes, y la lucha final contra Voldemort se acerca.`,
    genres: ["Fantasía", "Aventura", "Familia"],
    review: `Que decir... always`,
    favourite: true,
    score: 9,
  },
  {
    id: "M24",
    name: "Los Vengadores",
    author: "Joss Whedon",
    plot: `Los héroes más poderosos de la Tierra, incluyendo Iron Man, Capitán América, Thor, Hulk, Black Widow y Hawkeye, son convocados por S.H.I.E.L.D. para luchar contra Loki, quien planea invadir la Tierra con un ejército alienígena.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    id: "M25",
    name: "Vengadores: La era de Ultrón",
    author: "Joss Whedon",
    plot: `Tony Stark y Bruce Banner intentan iniciar un programa de mantenimiento de la paz llamado Ultrón, pero las cosas se salen de control y es deber de los Vengadores detener al villano Ultrón de enacting su terrible plan.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    id: "M26",
    name: "Vengadores: Infinity War",
    author: "Anthony Russo, Joe Russo",
    plot: `Los Vengadores y sus aliados deben estar dispuestos a sacrificar todo en un intento de derrotar al poderoso Thanos antes de que su blitz de devastación y ruina ponga fin al universo.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    id: "M27",
    name: "Vengadores: Endgame",
    author: "Anthony Russo, Joe Russo",
    plot: `Después de los eventos devastadores de 'Avengers: Infinity War', el universo está en ruinas. Con la ayuda de los aliados restantes, los Vengadores se reúnen una vez más para revertir las acciones de Thanos y restaurar el orden en el universo.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    review: `El final de todo, lo último que vi de Marvel. Siempre me parecieron entretenidas pero lejos de ser lo que más me gusta ver.`,
    favourite: false,
    score: 7,
  },
  {
    id: "M28",
    name: "Capitán América: El Primer Vengador",
    author: "Joe Johnston",
    plot: `Steve Rogers, un rechazado militar, se transforma en Capitán América después de tomar un suero de super soldado. Pero ser Capitán América tiene un precio mientras intenta derrotar a un enemigo de guerra y a un terrorista organización conocida como HYDRA.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    review: `La primera que ví de Marvel, tal vez de las mejores`,
    favourite: false,
    score: 7,
  },
  {
    id: "M29",
    name: "Iron Man",
    author: "Jon Favreau",
    plot: `Después de ser retenido en una cueva afgana, el ingeniero multimillonario Tony Stark crea una armadura única para luchar contra el mal.`,
    genres: ["Acción", "Aventura"],
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    id: "M30",
    name: "Thor",
    author: "Kenneth Branagh",
    plot: `El poderoso Thor es desterrado de Asgard a la Tierra por su padre Odin, donde se ve obligado a vivir entre humanos. Cuando el villano más peligroso de su mundo envía las fuerzas más oscuras de Asgard a la Tierra, Thor aprende lo que se necesita para ser un verdadero héroe.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    id: "M31",
    name: "Doctor Strange",
    author: "Scott Derrickson",
    plot: `Después de que su carrera se destruye, un brillante pero arrogante cirujano obtiene una nueva vida cuando un hechicero lo toma bajo su ala y lo entrena para defender al mundo contra el mal.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    id: "M32",
    name: "Thor: Ragnarok",
    author: "Taika Waititi",
    plot: `Thor está encarcelado al otro lado del universo y se encuentra en una carrera contra el tiempo para volver a Asgard y detener el Ragnarok, la destrucción de su mundo natal y el fin de la civilización asgardiana, a manos de una nueva y todopoderosa amenaza, la implacable Hela.`,
    genres: ["Acción", "Aventura", "Comedia"],
    review: ``,
    favourite: false,
    score: 8,
  },
  {
    id: "M33",
    name: "Black Panther",
    author: "Ryan Coogler",
    plot: `T'Challa, heredero del reino oculto pero avanzado de Wakanda, debe dar un paso adelante para liderar a su pueblo hacia un nuevo futuro y debe enfrentar un desafío del pasado de su familia.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    id: "M34",
    name: "Forrest Gump",
    author: "Robert Zemeckis",
    plot: `La película cuenta la historia de Forrest Gump, un hombre con un coeficiente intelectual bajo pero con un gran corazón, que vive una serie de aventuras que lo llevan a ser testigo y participante involuntario de varios momentos históricos de los Estados Unidos en la segunda mitad del siglo XX.`,
    genres: ["Drama", "Romance"],
    review: `Clásico podría decirse`,
    favourite: false,
    score: 8,
  },
  {
    id: "M35",
    name: "Hombres de Negro",
    author: "Barry Sonnenfeld",
    plot: `La película sigue a dos agentes de una organización secreta que supervisa y maneja la actividad extraterrestre en la Tierra mientras trabajan para evitar la interacción entre los humanos y los extraterrestres.`,
    genres: ["Acción", "Aventura", "Comedia"],
    review: `Siempre me gustó la trilogía, tiene cierto encanto imaginar que los extraterrestres viven entre nosotros.`,
    favourite: false,
    score: 7,
  },
  {
    id: "M36",
    name: "Hombres de Negro II",
    author: "Barry Sonnenfeld",
    plot: `En esta secuela, los agentes J y K vuelven a unirse para detener a un monstruo alienígena en forma de modelo de lencería que intenta apoderarse del universo.`,
    genres: ["Acción", "Aventura", "Comedia"],
    review: `Mi favorita de las tres`,
    favourite: false,
    score: 8,
  },
  {
    id: "M37",
    name: "Hombres de Negro III",
    author: "Barry Sonnenfeld",
    plot: `El agente J viaja en el tiempo hasta los años 60 para detener a un alienígena de asesinar a su amigo el agente K y cambiar la historia.`,
    genres: ["Acción", "Aventura", "Comedia"],
    review: `Es entretenida pero para mi no es tan buena como las anteriores`,
    favourite: false,
    score: 6,
  },
  {
    id: "M38",
    name: "El Pianista",
    author: "Roman Polanski",
    plot: `La película narra la historia de Władysław Szpilman, un pianista polaco de origen judío, que lucha por sobrevivir al holocausto en Varsovia durante la Segunda Guerra Mundial. Basada en la autobiografía de Szpilman, muestra su supervivencia gracias a la música y la bondad de unos pocos que le ayudaron en tiempos de desesperación.`,
    genres: ["Biografía", "Drama", "Bélico"],
    review: `Excelente película. Perfecta para perder más aún la fe en la humanidad`,
    favourite: false,
    score: 8,
  },
  {
    id: "M39",
    name: "Batman Begins",
    author: "Christopher Nolan",
    plot: `La película explora los orígenes de la leyenda de Batman y la aparición de Bruce Wayne como el caballero de la noche en Gotham City. Después de entrenar con su mentor, Batman comienza su lucha contra el crimen y la corrupción que asola su ciudad.`,
    genres: ["Acción", "Crimen", "Drama"],
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    id: "M40",
    name: "El Caballero de la Noche",
    author: "Christopher Nolan",
    plot: `Batman se enfrenta al criminal psicópata conocido como el Joker, quien desata una ola de caos en Gotham City. Batman debe aceptar una de las pruebas psicológicas y físicas más grandes de su habilidad para luchar contra la injusticia.`,
    genres: ["Acción", "Crimen", "Drama"],
    review: ``,
    favourite: true,
    score: 8,
  },
  {
    id: "M41",
    name: "El Caballero de la Noche Asciende",
    author: "Christopher Nolan",
    plot: `Ocho años después de los eventos de 'El Caballero de la Noche', un nuevo líder terrorista, Bane, abruma a Gotham y el caballero de la noche debe resurgir para proteger una ciudad que lo ha marcado como un enemigo.`,
    genres: ["Acción", "Drama", "Crimen"],
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    id: "M42",
    name: "Shrek",
    author: "Andrew Adamson, Vicky Jenson",
    plot: `Shrek, un ogro verde, emprende un viaje con un burro parlante para rescatar a la princesa Fiona y así recuperar la tranquilidad de su pantano, que ha sido invadido por personajes de cuentos de hadas desterrados por el malvado Lord Farquaad.`,
    genres: ["Animación", "Aventura", "Comedia"],
    review: `Excelente, más allá de los memes (si fingimos que la 3 no existió) es una serie de películas muy buena. Entretenidas y divertidas`,
    favourite: false,
    score: 8,
  },
  {
    id: "M43",
    name: "Shrek 2",
    author: "Andrew Adamson, Kelly Asbury, Conrad Vernon",
    plot: `Shrek y Fiona viajan al Reino de Muy Muy Lejano para conocer a los padres de Fiona, pero no todo sale como esperaban. El hada madrina y el Príncipe Encantador tienen sus propios planes para separarlos.`,
    genres: ["Animación", "Aventura", "Comedia"],
    review: `Peak animación. La secuencia final debe ser lo mejor que existe en el universo`,
    favourite: true,
    score: 10,
  },
  {
    id: "M44",
    name: "Shrek Tercero",
    author: "Chris Miller, Raman Hui",
    plot: `Shrek se enfrenta a la perspectiva de convertirse en rey y, con la ayuda de sus amigos, busca a un nuevo candidato adecuado para el trono de Muy Muy Lejano mientras el Príncipe Encantador planea un golpe de estado.`,
    genres: ["Animación", "Aventura", "Comedia"],
    review: `Terrible, solo algunos momentos son rescatables`,
    favourite: false,
    score: 5,
  },
  {
    id: "M45",
    name: "Shrek Para Siempre",
    author: "Mike Mitchell",
    plot: `Esta película rescata a la saga. Creo que a mucha gente no la vio o le interesó mucho, pero para mí luego de la tercera esta película vuelve en gran medida a lo que hizo excelentes a las dos primeras`,
    genres: ["Animación", "Aventura", "Comedia"],
    review: `Esta película rescata a la saga. Creo que a mucha gente no la vió o le interesó mucho pero para mí luego de la tercera esta película vulve en gran medida a lo que hizo excelentes a las dos primeras`,
    favourite: false,
    score: 8,
  },
  {
    id: "M46",
    name: "Kung Fu Panda",
    author: "John Stevenson, Mark Osborne",
    plot: `La historia sigue a Po, un panda torpe y amante del kung fu, que es elegido inesperadamente como el Guerrero Dragón. A pesar de la incredulidad de los demás, Po se embarca en un viaje de autodescubrimiento y entrenamiento para enfrentarse al malvado Tai Lung.`,
    genres: ["Animación", "Acción", "Aventura", "Comedia"],
    review: `El secreto de la sopa de ingrediente secreto es...`,
    favourite: true,
    score: 8,
  },
  {
    id: "M47",
    name: "Kung Fu Panda 2",
    author: "Jennifer Yuh Nelson",
    plot: `Po ahora vive su sueño como el Guerrero Dragón, protegiendo el Valle de la Paz junto a sus amigos y compañeros maestros de kung fu. Sin embargo, su nueva vida se ve amenazada por la aparición de un villano que planea usar un arma secreta imparable para conquistar China y destruir el kung fu.`,
    genres: ["Animación", "Acción", "Aventura", "Comedia"],
    review: ``,
    favourite: true,
    score: 9,
  },
  {
    id: "M48",
    name: "Kung Fu Panda 3",
    author: "Jennifer Yuh Nelson, Alessandro Carloni",
    plot: `Cuando el padre biológico de Po reaparece, el dúo se reúne y viaja a un paraíso secreto de pandas donde conocen a un montón de nuevos personajes pandásticos. Pero cuando el villano sobrenatural Kai comienza a barrer China derrotando a todos los maestros de kung fu, Po debe hacer lo imposible: entrenar a un pueblo lleno de sus hermanos pandas amantes de la diversión para convertirse en el último equipo de Kung Fu Pandas.`,
    genres: ["Animación", "Acción", "Aventura", "Comedia"],
    review: `Un buen final para la trilogía, lástima que hace poco salió una cuarta película que no aporta mucho a la saga.`,
    favourite: false,
    score: 7,
  },
  {
    id: "M49",
    name: "I, Robot",
    author: "Alex Proyas",
    plot: `En el año 2035, los robots son una parte común de la vida humana, pero cuando el detective Del Spooner investiga el aparente suicidio de un destacado científico de robótica, descubre una amenaza que podría cambiar la relación entre humanos y robots para siempre.`,
    genres: ["Ciencia ficción", "Acción", "Misterio"],
    review: `Entretenida pero no destaca para mí`,
    favourite: false,
    score: 6,
  },
  {
    id: "M50",
    name: "Lo que el viento se llevó",
    author: "Victor Fleming",
    plot: `La película, ambientada en el sur de Estados Unidos durante la Guerra Civil y la Reconstrucción, sigue la vida de Scarlett O'Hara, la obstinada hija de un plantador, y su tumultuosa relación amorosa con Rhett Butler.`,
    genres: ["Drama", "Romance", "Bélico"],
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    id: "M51",
    name: "Interstellar",
    author: "Christopher Nolan",
    plot: `La película sigue a un grupo de astronautas que viajan a través de un agujero de gusano cerca de Saturno en busca de un nuevo hogar para la humanidad, ya que la Tierra se está volviendo inhabitable. La narrativa explora temas complejos de amor, sacrificio y la naturaleza del tiempo.`,
    genres: ["Ciencia ficción", "Aventura", "Drama"],
    review: `Tiene buenas bases científicas y eso se agradece, aunque los sucesos del final son más especulativos. De todas formas, muy buena película`,
    favourite: true,
    score: 9,
  },
  {
    id: "M52",
    name: "Inception",
    author: "Christopher Nolan",
    plot: `La película sigue a Dom Cobb, un ladrón de habilidades excepcionales, que se especializa en la extracción de secretos valiosos del subconsciente durante el estado de sueño. Cobb tiene la oportunidad de redimirse cuando se le ofrece una tarea aparentemente imposible: realizar la 'inception', es decir, implantar una idea en la mente de una persona.`,
    genres: ["Ciencia ficción", "Acción", "Aventura"],
    review: `Está buena pero en lo personal no me engacha tanto`,
    favourite: false,
    score: 7,
  },
  {
    id: "M53",
    name: "Tenet",
    author: "Christopher Nolan",
    plot: `La película sigue a un protagonista, cuyo nombre nunca se revela, en su misión para evitar una Tercera Guerra Mundial. Utiliza una tecnología de inversión temporal que le permite experimentar el tiempo de manera no lineal, enfrentándose a amenazas en el presente y en el pasado.`,
    genres: ["Ciencia ficción", "Acción", "Thriller"],
    review: `Me pasa lo mismo que con Inception, la idea me parece interesante y la considero una buena película, pero no logra engancharme del todo.`,
    favourite: false,
    score: 8,
  },
  {
    id: "M54",
    name: "Intensamente",
    author: "Pete Docter, Ronnie del Carmen",
    plot: `La película sigue a una niña llamada Riley y las emociones en su mente - Alegría, Tristeza, Ira, Miedo y Desagrado - mientras navegan por los cambios en su vida cuando se muda a una nueva ciudad.`,
    genres: ["Animación", "Aventura", "Comedia"],
    review: `It's enough to make a grown man cry...`,
    favourite: false,
    score: 8,
  },
  {
    id: "M55",
    name: "Espanta Tiburones",
    author: "Vicky Jenson, Bibo Bergeron, Rob Letterman",
    plot: `La historia se centra en Oscar, un pez pequeño que quiere ser rico y famoso, y cómo se convierte en un héroe al mentir sobre haber matado al hijo de un tiburón mafioso.`,
    genres: ["Animación", "Aventura", "Comedia"],
    review: `Un horror`,
    favourite: false,
    score: 3,
  },
  {
    id: "M56",
    name: "El Hobbit: Un Viaje Inesperado",
    author: "Peter Jackson",
    plot: `Bilbo Bolsón es arrastrado a una búsqueda para reclamar el reino perdido de Erebor del temible dragón Smaug, junto con el mago Gandalf y trece enanos liderados por el legendario guerrero Thorin Escudo de Roble.`,
    genres: ["Aventura", "Fantasía", "Acción"],
    review: `La trilogía en general está bien pero no me causa tantas pasiones como el Señor de los Anillos`,
    favourite: false,
    score: 7,
  },
  {
    id: "M57",
    name: "El Hobbit: La Desolación de Smaug",
    author: "Peter Jackson",
    plot: `Bilbo y los enanos continúan su viaje hacia Erebor, enfrentando múltiples peligros, incluyendo al dragón Smaug, mientras el mago Gandalf investiga la creciente oscuridad en la Tierra Media.`,
    genres: ["Aventura", "Fantasía"],
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    id: "M58",
    name: "El Hobbit: La Batalla de los Cinco Ejércitos",
    author: "Peter Jackson",
    plot: `La conclusión épica de la aventura de Bilbo Bolsón, quien se encuentra en medio de una batalla que pondrá en juego el futuro de la Tierra Media.`,
    genres: ["Aventura", "Fantasía"],
    review: ``,
    favourite: false,
    score: 8,
  },
  {
    id: "M60",
    name: "Call Me By Your Name",
    author: "Luca Guadagnino",
    plot: `La película es una historia de amor ambientada en 1983 en Italia, donde Elio Perlman, un joven de 17 años, comienza una relación con el asistente de su padre, Oliver, durante el verano.`,
    genres: ["Drama", "Romance", "LGBT"],
    review: ``,
    favourite: true,
    score: 8,
  },
  {
    id: "M61",
    name: "Love, Simon",
    author: "Greg Berlanti",
    plot: `Simon Spier mantiene un secreto de su familia, sus amigos y todos sus compañeros de clase: es gay. Cuando ese secreto es amenazado, Simon debe enfrentar a todos y aceptar su identidad.`,
    genres: ["Comedia", "Drama", "Romance", "LGBT"],
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    id: "M62",
    name: "Rescatando al Soldado Ryan",
    author: "Steven Spielberg",
    plot: `Tras el desembarco de Normandía, un grupo de soldados estadounidenses van detrás de las líneas enemigas para recuperar a un paracaidista cuyos hermanos han muerto en la guerra.`,
    genres: ["Drama", "Bélico"],
    review: ``,
    favourite: false,
    score: 8,
  },
  {
    id: "M63",
    name: "Yo, Adolescente",
    author: "Lucas Santa Ana",
    plot: `Tras el suicidio de un compañero, un adolescente argentino comienza a explorar su sexualidad y busca su lugar en el mundo mientras lidia con la pérdida y el dolor.`,
    genres: ["Drama", "LGBT"],
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    id: "M64",
    name: "The Way He Looks",
    author: "Daniel Ribeiro",
    plot: `Leonardo, un adolescente ciego, busca su independencia y se enfrenta a los problemas de la adolescencia. Su vida cambia con la llegada de Gabriel, un nuevo compañero de clase.`,
    genres: ["Drama", "Romance", "LGBT"],
    review: ``,
    favourite: false,
    score: 8,
  },
  {
    id: "M65",
    name: "El Día de la Independencia",
    author: "Roland Emmerich",
    plot: `La Tierra se enfrenta a una amenaza extraterrestre masiva y solo la ingeniosidad y valentía de los humanos pueden salvar al planeta de la destrucción.`,
    genres: ["Ciencia ficción", "Acción", "Aventura"],
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    id: "M66",
    name: "El Día de la Independencia: Contraataque",
    author: "Roland Emmerich",
    plot: `Veinte años después de la primera invasión, la Tierra se enfrenta a una nueva amenaza extraterrestre de proporciones aún mayores.`,
    genres: ["Ciencia ficción", "Acción", "Aventura"],
    review: `Si no pensas es pasable`,
    favourite: false,
    score: 5,
  },
  {
    id: "M67",
    name: "Terminator",
    author: "James Cameron",
    plot: `Un cyborg asesino es enviado desde el futuro para matar a Sarah Connor, una mujer cuyo hijo no nacido liderará a la humanidad en una guerra contra las máquinas.`,
    genres: ["Ciencia ficción", "Acción"],
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    id: "M68",
    name: "Terminator 2: El Juicio Final",
    author: "James Cameron",
    plot: `Sarah Connor y su hijo John, con la ayuda de un Terminator reprogramado, deben evitar el día del juicio final, una catástrofe nuclear instigada por las máquinas.`,
    genres: ["Ciencia ficción", "Acción"],
    review: `Una buena secuela`,
    favourite: false,
    score: 8,
  },
  {
    id: "M69",
    name: "Terminator 3: La Rebelión de las Máquinas",
    author: "Jonathan Mostow",
    plot: `John Connor, ahora adulto, debe enfrentarse a un nuevo Terminator femenino y evitar el levantamiento de las máquinas.`,
    genres: ["Ciencia ficción", "Acción"],
    review: `No está mal pero hay una caída respecto a las dos anteriores`,
    favourite: false,
    score: 6,
  },
  {
    id: "M70",
    name: "Terminator Salvation",
    author: "McG",
    plot: `En un futuro post-apocalíptico, John Connor lidera la resistencia humana contra Skynet y su ejército de Terminators.`,
    genres: ["Ciencia ficción", "Acción"],
    review: `Terrible`,
    favourite: false,
    score: 5,
  },
  {
    id: "M71",
    name: "Esperando la Carroza",
    author: "Alejandro Doria",
    plot: `Una comedia clásica argentina que gira en torno a las desventuras de una familia disfuncional y su matriarca desaparecida.`,
    genres: ["Comedia"],
    review: `Un clásico sin duda alguna`,
    favourite: true,
    score: 10,
  },
  {
    id: "M72",
    name: "La Película de Los Simpsons",
    author: "David Silverman",
    plot: `Homer Simpson debe salvar a la ciudad de Springfield después de causar una catástrofe ambiental.`,
    genres: ["Animación", "Aventura", "Comedia"],
    review: `Fue divertido ir a verla al cine cuando salió, no es para tirar cohetes, pero es divertida`,
    favourite: false,
    score: 6,
  },
  {
    id: "M73",
    name: "Big Time Movie",
    author: "Savage Steve Holland",
    plot: `La banda Big Time Rush se encuentra en una misión en Londres, donde deben salvar al mundo y dar un gran concierto.`,
    genres: ["Comedia", "Familia", "Música"],
    review: `Siendo objetivos no es buena pero bueno, fueron mi infancia.`,
    favourite: false,
    score: 6,
  },
  {
    id: "M74",
    name: "El Cisne Negro",
    author: "Darren Aronofsky",
    plot: `Una bailarina de ballet se ve envuelta en una competencia feroz y su psique se desmorona mientras se prepara para el papel principal en 'El lago de los cisnes'.`,
    genres: ["Drama", "Psicológico"],
    review: `Excelente película en la que vemos el cambio total que se produce en la protagonista a medida que se adentra en su papel en el ballet del lago de los cisnes.`,
    favourite: true,
    score: 9,
  },
  {
    name: "Los Juegos del Hambre",
    author: "Gary Ross",
    plot: `En un futuro distópico, el Capitolio de Panem mantiene su control sobre los 12 distritos realizando anualmente un evento televisado conocido como los Juegos del Hambre, en el que un chico y una chica de cada distrito deben luchar a muerte hasta que solo quede uno. La protagonista, Katniss Everdeen, se ofrece voluntaria para ocupar el lugar de su hermana menor en los juegos.`,
    genres: ["Acción", "Aventura", "Ciencia ficción"],
    id: "M76",
    review: `Un buen inicio y la que más me gusta de la saga`,
    favourite: false,
    score: 7,
  },
  {
    name: "Los Juegos del Hambre: En llamas",
    author: "Francis Lawrence",
    plot: `Tras ganar los 74º Juegos del Hambre, Katniss Everdeen y Peeta Mellark deben embarcarse en la gira de la victoria por los distritos. Sin embargo, su victoria ha encendido una chispa de rebelión en los distritos de Panem. El Capitolio, para controlarlos, organiza los 75º Juegos del Hambre, el "Quarter Quell", donde los ganadores anteriores deben enfrentarse nuevamente.`,
    genres: ["Acción", "Aventura", "Ciencia ficción"],
    id: "M77",
    review: `Me gusta un poco menos que la primera pero todavía hay juegos y son entretenidos`,
    favourite: false,
    score: 7,
  },
  {
    name: "Los Juegos del Hambre: Sinsajo - Parte 1",
    author: "Francis Lawrence",
    plot: `Katniss Everdeen se encuentra en el Distrito 13 tras destrozar los juegos para siempre. Bajo el liderazgo de la Presidenta Coin y el consejo de sus amigos, Katniss decide convertirse en el "Sinsajo", el símbolo de la rebelión. Con Peeta prisionero del Capitolio, Katniss se enfrenta a desafíos personales y políticos en su lucha por salvar a Panem.`,
    genres: ["Acción", "Aventura", "Ciencia ficción"],
    id: "M78",
    review: `Muy aburrida, tal vez dividir la última parte en dos no fue lo más apropiado`,
    favourite: false,
    score: 5,
  },
  {
    name: "Los Juegos del Hambre: Sinsajo - Parte 2",
    author: "Francis Lawrence",
    plot: `En la última entrega de la saga, Katniss y sus aliados lanzan una ofensiva final contra el Capitolio. Mientras la guerra contra el Presidente Snow se intensifica, Katniss debe enfrentarse no solo a sus enemigos, sino también a las dudas sobre sus propios aliados y las motivaciones detrás de la guerra.`,
    genres: ["Acción", "Aventura", "Ciencia ficción"],
    id: "M79",
    review: `Pasable`,
    favourite: false,
    score: 6,
  },
  {
    name: "Dune: Parte 1",
    author: "Denis Villeneuve",
    plot: `En un futuro distante, el joven Paul Atreides se enfrenta a un destino monumental al ser arrastrado a un conflicto intergaláctico por el control del planeta desértico Arrakis, también conocido como Dune. Mientras familias nobles conspiran y traicionan, Paul debe aceptar su herencia y su destino para proteger a su gente y salvar el planeta.`,
    genres: ["Acción", "Aventura", "Ciencia ficción"],
    id: "M80",
    review: `Muy buena adaptación`,
    favourite: false,
    score: 8,
  },
  {
    name: "Dune: Parte 2",
    author: "Denis Villeneuve",
    plot: `La continuación de la épica saga de Paul Atreides, quien busca venganza contra los traidores que destruyeron a su familia mientras se enfrenta a su destino como el Mesías de los Fremen y líder del planeta Dune. La batalla por Arrakis se intensifica, y Paul debe unir a las facciones y enfrentar decisiones que determinarán el futuro del universo.`,
    genres: ["Acción", "Aventura", "Ciencia ficción"],
    id: "M81",
    review: `Muy buena adaptación al igual que la primera parte`,
    favourite: true,
    score: 9,
  },
  {
    name: "Oppenheimer",
    author: "Christopher Nolan",
    plot: `La biografía de J. Robert Oppenheimer, el físico teórico que desempeñó un papel crucial en el desarrollo de la bomba atómica durante la Segunda Guerra Mundial como parte del Proyecto Manhattan. La película explora tanto sus logros científicos como las implicaciones morales y personales de su trabajo.`,
    genres: ["Biografía", "Drama", "Historia"],
    id: "M82",
    review: `Es interesante poder aprender sobre su vida y sobre un momento histórico muy particular a través de su punto de vista`,
    favourite: false,
    score: 9,
  },
  {
    name: "Napoleón",
    author: "Ridley Scott",
    plot: `Una exploración épica de la vida de Napoleón Bonaparte, desde sus humildes comienzos en Córcega hasta convertirse en el emperador de Francia. La película sigue sus campañas militares, su ascenso y caída del poder, y su relación tumultuosa con su esposa, Josefina.`,
    genres: ["Biografía", "Drama", "Historia"],
    id: "M83",
    review: `Se la criticó mucho, pero a mí no me pareció mala, aunque tampoco espectacular, simplemente buena.`,
    favourite: false,
    score: 8,
  },
  {
    name: "Gladiador",
    author: "Ridley Scott",
    plot: `El general romano Máximo Décimo Meridio es traicionado por el hijo corrupto del emperador, Cómodo, y se ve obligado a convertirse en gladiador. En su lucha por la libertad y la justicia, Máximo se convierte en el héroe del pueblo y planea su venganza contra Cómodo mientras lucha por restaurar el honor a Roma.`,
    genres: ["Acción", "Aventura", "Drama"],
    id: "M84",
    review: `De chico la vi un montón de veces, siempre me gustó.`,
    favourite: false,
    score: 8,
  },
  {
    name: "Arma Mortal",
    author: "Richard Donner",
    plot: `El veterano detective Roger Murtaugh y su nuevo y temerario compañero Martin Riggs forman un equipo improbable para resolver una serie de crímenes en Los Ángeles. A medida que se enfrentan a peligrosos criminales y una trama de drogas, su asociación profesional se convierte en una amistad inquebrantable.`,
    genres: ["Acción", "Crimen"],
    id: "M85",
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    name: "Arma Mortal 2",
    author: "Richard Donner",
    plot: `Los detectives Murtaugh y Riggs regresan para enfrentarse a una peligrosa red de narcotraficantes sudafricanos que operan en Los Ángeles. Mientras investigan el caso, descubren una conspiración que pone sus vidas en peligro, pero su lealtad y valentía los ayudan a luchar contra el crimen.`,
    genres: ["Acción", "Crimen"],
    id: "M86",
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    name: "Duro de Matar",
    author: "John McTiernan",
    plot: `El oficial de policía de Nueva York John McClane visita a su esposa en Los Ángeles durante la Navidad. Sin embargo, su visita se convierte en una pesadilla cuando terroristas liderados por Hans Gruber toman el edificio Nakatomi Plaza. McClane, solo y sin refuerzos, debe enfrentarse a los terroristas y salvar a los rehenes.`,
    genres: ["Acción"],
    id: "M87",
    review: `La mejor película navideña.`,
    favourite: false,
    score: 6,
  },
  {
    name: "La mentira original",
    author: "James Cameron",
    plot: `Una pareja de casados se ve envuelta en una trama de espionaje internacional cuando el esposo, que lleva una doble vida como agente secreto, intenta salvar al mundo de un complot terrorista mientras intenta rescatar su matrimonio.`,
    genres: ["Acción", "Comedia", "Suspenso"],
    id: "M88",
    review: `Entretenida la idea, pero, incluso considerando que es una comedia, no es como para tirar cohetes`,
    favourite: false,
    score: 6,
  },
  {
    name: "El rey león (1994)",
    author: "Roger Allers, Rob Minkoff",
    plot: `Un joven león llamado Simba debe aprender a aceptar su papel como legítimo rey de la Tierra del Orgullo después de la trágica muerte de su padre, Mufasa, mientras enfrenta la traición de su tío Scar.`,
    genres: ["Animación", "Aventura", "Drama"],
    id: "M89",
    review: `Clásico`,
    favourite: false,
    score: 7,
  },
  {
    name: "Jumanji (1995)",
    author: "Joe Johnston",
    plot: `Dos niños descubren un misterioso juego de mesa que libera una serie de peligros selváticos en el mundo real. Junto con el hombre que quedó atrapado en el juego durante décadas, deben terminar la partida para revertir el caos.`,
    genres: ["Aventura", "Familia", "Fantasía"],
    id: "M90",
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    name: "Jumanji: Bienvenidos a la jungla",
    author: "Jake Kasdan",
    plot: `Cuatro adolescentes son absorbidos por un videojuego mágico y se encuentran en una jungla virtual, ocupando cuerpos de avatares adultos. Para regresar al mundo real, deben completar una peligrosa aventura y aprender a trabajar juntos.`,
    genres: ["Acción", "Aventura", "Comedia"],
    id: "M91",
    review: `Capaz que es la opinión controversial, pero me gusta más que la original.`,
    favourite: false,
    score: 7,
  },
  {
    name: "Jumanji: El siguiente nivel",
    author: "Jake Kasdan",
    plot: `El grupo de amigos regresa al mundo de Jumanji para rescatar a uno de los suyos, descubriendo que nada es como esperaban. Deben enfrentarse a nuevos desafíos y peligros para salir del juego una vez más.`,
    genres: ["Acción", "Aventura", "Comedia"],
    id: "M92",
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    name: "La grieta de Jara",
    author: "Nicolás Gil Lavedra",
    plot: `Un arquitecto descubre una grieta en la pared de un edificio que revela una red de corrupción y secretos ocultos en su empresa. A medida que investiga, se enfrenta a peligros que amenazan su vida.`,
    genres: ["Drama", "Suspenso"],
    id: "M93",
    review: `Entretenida como para pasar el rato`,
    favourite: false,
    score: 6,
  },
  {
    name: "Once Upon a Time in Hollywood",
    author: "Quentin Tarantino",
    plot: `En 1969, un actor de televisión y su doble de riesgo intentan encontrar su camino en una industria cinematográfica cambiante mientras se cruzan con figuras reales y ficticias del Hollywood de la época.`,
    genres: ["Comedia", "Drama"],
    id: "M94",
    review: ``,
    favourite: false,
    score: 9,
  },
  {
    name: "Charlie y la fábrica de chocolate",
    author: "Tim Burton",
    plot: `Un niño pobre llamado Charlie gana un concurso para visitar la misteriosa fábrica de chocolate de Willy Wonka, donde descubre un mundo de fantasía y dulces increíbles.`,
    genres: ["Aventura", "Comedia", "Familia"],
    id: "M95",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "Footloose",
    author: "Herbert Ross",
    plot: `Un adolescente de ciudad se muda a un pequeño pueblo donde la música rock y el baile están prohibidos. Lucha contra las restricciones y busca cambiar la mentalidad de la comunidad.`,
    genres: ["Drama", "Música", "Romance"],
    id: "M96",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "El fin de los tiempos",
    author: "M. Night Shyamalan",
    plot: `Un maestro de ciencias y su esposa huyen de una catástrofe natural inexplicable que provoca suicidios masivos, mientras intentan descubrir el origen del fenómeno y sobrevivir.`,
    genres: ["Ciencia ficción", "Suspenso"],
    id: "M97",
    review: `No tiene nada para destacar, es curiosa la idea tras la película pero se torna aburrida`,
    favourite: false,
    score: 4,
  },
  {
    name: "Indiana Jones y los cazadores del arca perdida",
    author: "Steven Spielberg",
    plot: `El arqueólogo Indiana Jones se enfrenta a nazis y otros enemigos en su búsqueda para encontrar el Arca de la Alianza, un artefacto bíblico de gran poder.`,
    genres: ["Acción", "Aventura"],
    id: "M98",
    review: `Es una película decente, pero al fin y al cabo Indiana Jones no hace nada significativo. `,
    favourite: false,
    score: 6,
  },
  {
    name: "Indiana Jones y el templo de la perdición",
    author: "Steven Spielberg",
    plot: `Indiana Jones se embarca en una peligrosa aventura en la India, donde debe rescatar a niños esclavos y recuperar una piedra sagrada robada por una secta maligna.`,
    genres: ["Acción", "Aventura"],
    id: "M99",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "Indiana Jones y la última cruzada",
    author: "Steven Spielberg",
    plot: `Indiana Jones y su padre se embarcan en una búsqueda para encontrar el Santo Grial antes de que los nazis lo consigan. Su aventura está llena de peligros y enigmas históricos.`,
    genres: ["Acción", "Aventura"],
    id: "M100",
    review: `La que más vi de chico y mi favorita de la trilogía. Es entretenido ver las escenas entre Indy y su padre. `,
    favourite: false,
    score: 8,
  },
  {
    name: "Indiana Jones y el reino de la calavera de cristal",
    author: "Steven Spielberg",
    plot: `Indiana Jones se enfrenta a agentes soviéticos en la búsqueda de una misteriosa calavera de cristal que posee poderes sobrenaturales.`,
    genres: ["Acción", "Aventura"],
    id: "M101",
    review: `Se cayó a pedacitos en esta entrega, pasable en todo caso.`,
    favourite: false,
    score: 5,
  },
  {
    name: "El conde de Montecristo",
    author: "Kevin Reynolds",
    plot: `Un hombre es traicionado por sus amigos y encarcelado injustamente. Después de escapar de prisión, encuentra un tesoro escondido y se reinventa como el Conde de Montecristo para vengarse de quienes lo traicionaron.`,
    genres: ["Aventura", "Drama"],
    id: "M102",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "Jurassic Park",
    author: "Steven Spielberg",
    plot: `Un parque temático de dinosaurios clonados se convierte en un caos cuando los sistemas de seguridad fallan y las criaturas escapan, poniendo en peligro a los visitantes y al personal del parque.`,
    genres: ["Aventura", "Ciencia ficción", "Suspenso"],
    id: "M103",
    review: `"No hemos reparado en gastos"`,
    favourite: false,
    score: 7,
  },
  {
    name: "El mundo perdido: Jurassic Park",
    author: "Steven Spielberg",
    plot: `Un equipo de científicos y cazadores se adentran en una isla donde los dinosaurios han sido liberados para estudiar su comportamiento y sobrevivir a los peligros de la naturaleza salvaje.`,
    genres: ["Aventura", "Ciencia ficción", "Suspenso"],
    id: "M104",
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    name: "Jurassic Park III",
    author: "Joe Johnston",
    plot: `Un paleontólogo es engañado para regresar a una isla infestada de dinosaurios para rescatar al hijo desaparecido de una pareja adinerada, enfrentándose a nuevos peligros y especies de dinosaurios.`,
    genres: ["Aventura", "Ciencia ficción", "Suspenso"],
    id: "M105",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "Resident Evil",
    author: "Paul W. S. Anderson",
    plot: `Una corporación sombría llamada Umbrella libera accidentalmente un virus que convierte a las personas en zombis. Un grupo de supervivientes debe enfrentarse a los horrores dentro de una instalación subterránea para contener el brote.`,
    genres: ["Acción", "Horror", "Ciencia ficción"],
    id: "M106",
    review: `El inicio de la saga y probablemente junto con la 2 las únicas que están bien.`,
    favourite: false,
    score: 7,
  },
  {
    name: "Resident Evil: Apocalipsis",
    author: "Alexander Witt",
    plot: `Alice regresa para luchar contra los zombis y otros monstruos mutados en Raccoon City, mientras trata de encontrar una salida de la ciudad infestada antes de que sea destruida por una bomba nuclear.`,
    genres: ["Acción", "Horror", "Ciencia ficción"],
    id: "M107",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "Resident Evil: Extinción",
    author: "Russell Mulcahy",
    plot: `En un mundo post-apocalíptico, Alice lidera a un grupo de supervivientes a través del desierto en busca de un refugio seguro mientras se enfrenta a la corporación Umbrella y sus experimentos biológicos.`,
    genres: ["Acción", "Horror", "Ciencia ficción"],
    id: "M108",
    review: `El inicio de la debacle`,
    favourite: false,
    score: 6,
  },
  {
    name: "Resident Evil: Ultratumba",
    author: "Paul W. S. Anderson",
    plot: `Alice continúa su lucha contra la corporación Umbrella mientras busca supervivientes y un lugar seguro. En su viaje, se enfrenta a nuevas amenazas y descubre secretos sobre su propia identidad.`,
    genres: ["Acción", "Horror", "Ciencia ficción"],
    id: "M109",
    review: ``,
    favourite: false,
    score: 5,
  },
  {
    name: "Resident Evil: Venganza",
    author: "Paul W. S. Anderson",
    plot: `Alice se despierta en una instalación de la corporación Umbrella y debe escapar mientras enfrenta sus peores enemigos y descubre una conspiración global para acabar con la humanidad.`,
    genres: ["Acción", "Horror", "Ciencia ficción"],
    id: "M110",
    review: ``,
    favourite: false,
    score: 5,
  },
  {
    name: "Resident Evil: Capítulo final",
    author: "Paul W. S. Anderson",
    plot: `Alice regresa a donde comenzó todo para enfrentarse a la corporación Umbrella en una última batalla que decidirá el destino de la humanidad.`,
    genres: ["Acción", "Horror", "Ciencia ficción"],
    id: "M111",
    review: `Sin duda la peor de la saga, lo único de "horror" en esta película es el guion.`,
    favourite: false,
    score: 3,
  },
  {
    name: "¡Sí, señor!",
    author: "Peyton Reed",
    plot: `Un hombre con una actitud negativa hacia la vida decide cambiar su enfoque y aceptar todas las oportunidades que se le presentan, con resultados cómicos e inesperados.`,
    genres: ["Comedia", "Drama", "Romance"],
    id: "M112",
    review: `Entretenida pero nada destacable.`,
    favourite: false,
    score: 6,
  },
  {
    name: "The Truman Show",
    author: "Peter Weir",
    plot: `Un hombre descubre que su vida es un reality show televisado y que todo su mundo es una ilusión controlada por un productor ejecutivo. Lucha por descubrir la verdad y escapar de su falsa realidad.`,
    genres: ["Comedia", "Drama", "Ciencia ficción"],
    id: "M113",
    review: `Una buena película que trata muchos temas, como puede ser la alegoría de la caverna de Platón (adaptado a un contexto más moderno).`,
    favourite: true,
    score: 8,
  },
  {
    name: "La momia",
    author: "Stephen Sommers",
    plot: `Un grupo de arqueólogos despierta accidentalmente a una momia antigua que desata una maldición en Egipto. Deben detener a la criatura antes de que destruya el mundo.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    id: "M114",
    review: `De chico me gustaban bastante y aunque la dos debe ser la que más vi, esta es mi favorita.`,
    favourite: false,
    score: 7,
  },
  {
    name: "El regreso de la momia",
    author: "Stephen Sommers",
    plot: `La momia resucitada busca venganza y poder mientras un grupo de aventureros intenta detener su plan maligno y proteger el mundo de una nueva amenaza.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    id: "M115",
    review: `De las películas que más vi de chico`,
    favourite: false,
    score: 7,
  },
  {
    name: "La momia: la tumba del emperador dragón",
    author: "Rob Cohen",
    plot: `Un guerrero momificado y su ejército son resucitados en China, y un grupo de aventureros debe detenerlo antes de que conquiste el mundo.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    id: "M116",
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    name: "La guerra de los mundos",
    author: "Steven Spielberg",
    plot: `Una invasión extraterrestre amenaza con destruir la humanidad, y un padre lucha por proteger a sus hijos y sobrevivir al caos mientras los alienígenas devastan el planeta.`,
    genres: ["Ciencia ficción", "Suspenso"],
    id: "M117",
    review: ``,
    favourite: false,
    score: 5,
  },
  {
    name: "Soy leyenda",
    author: "Francis Lawrence",
    plot: `En un mundo post-apocalíptico, un científico lucha por encontrar una cura para un virus que ha convertido a la humanidad en criaturas nocturnas mientras sobrevive en un Nueva York desolado.`,
    genres: ["Drama", "Ciencia ficción", "Suspenso"],
    id: "M118",
    review: `Prefiero el final alternativo al que dejaron pero está bien en genral como para pasar un rato`,
    favourite: false,
    score: 6,
  },
  {
    name: "El diario de Bridget Jones",
    author: "Sharon Maguire",
    plot: `Bridget Jones, una mujer soltera de treinta y tantos, decide llevar un diario en el que narra sus luchas con el amor, el trabajo y su peso, mientras busca la felicidad y el amor verdadero.`,
    genres: ["Comedia", "Romance"],
    id: "M119",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "Bridget Jones: Sobreviviré",
    author: "Beeban Kidron",
    plot: `Bridget Jones enfrenta nuevas aventuras y desafíos en su relación con Mark Darcy, mientras lidia con las tentaciones de su exjefe, Daniel Cleaver.`,
    genres: ["Comedia", "Romance"],
    id: "M120",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "Bridget Jones' Baby",
    author: "Sharon Maguire",
    plot: `Bridget Jones, ahora en sus cuarenta, se encuentra embarazada y no está segura de quién es el padre, enfrentándose a una nueva serie de aventuras y decisiones.`,
    genres: ["Comedia", "Romance"],
    id: "M121",
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    name: "Las crónicas de Narnia: El león, la bruja y el armario",
    author: "Andrew Adamson",
    plot: `Cuatro niños descubren un mundo mágico llamado Narnia a través de un armario, donde se unen al león Aslan para derrotar a la malvada Bruja Blanca.`,
    genres: ["Aventura", "Familia", "Fantasía"],
    id: "M122",
    review: `No me gusta mucho pero es pasable, más para su momento que la vi de chico `,
    favourite: false,
    score: 6,
  },
  {
    name: "Las crónicas de Narnia: El príncipe Caspian",
    author: "Andrew Adamson",
    plot: `Los niños Pevensie regresan a Narnia para ayudar al Príncipe Caspian a reclamar su trono y liberar a Narnia del tiránico Rey Miraz.`,
    genres: ["Aventura", "Familia", "Fantasía"],
    id: "M123",
    review: `Mucho peor que la primera y eso es decir bastante...`,
    favourite: false,
    score: 4,
  },

  {
    name: "El tren de las 3:10 a Yuma",
    author: "James Mangold",
    plot: `Un ranchero acepta escoltar a un peligroso forajido hasta un tren que lo llevará a la prisión, enfrentándose a múltiples desafíos y amenazas en el camino.`,
    genres: ["Acción", "Crimen", "Drama"],
    id: "M126",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "Scary Movie 2",
    author: "Keenen Ivory Wayans",
    plot: `Un grupo de estudiantes universitarios es invitado a pasar un fin de semana en una mansión embrujada, enfrentándose a situaciones hilarantes y parodias de películas de terror.`,
    genres: ["Comedia", "Horror"],
    id: "M127",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "Hellboy II: El ejército dorado",
    author: "Guillermo del Toro",
    plot: `Hellboy y su equipo enfrentan a un príncipe elfo que planea despertar un ejército dorado para destruir a la humanidad y reclamar el dominio del mundo.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    id: "M128",
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    name: "La niebla",
    author: "Frank Darabont",
    plot: `Un grupo de personas queda atrapado en un supermercado cuando una extraña niebla que oculta criaturas aterradoras invade su ciudad, enfrentándose al caos y al miedo.`,
    genres: ["Horror", "Suspenso"],
    id: "M129",
    review: `El final la salva un poco, pero no destaca en mi libro`,
    favourite: false,
    score: 5,
  },
  {
    name: "Impacto profundo",
    author: "Mimi Leder",
    plot: `Cuando se descubre que un cometa está en curso de colisión con la Tierra, la humanidad lucha por sobrevivir a los cataclismos y encontrar formas de asegurar la continuidad de la especie.`,
    genres: ["Drama", "Ciencia ficción"],
    id: "M130",
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    name: "Piratas del Caribe: La maldición del Perla Negra",
    author: "Gore Verbinski",
    plot: `El capitán Jack Sparrow y el herrero Will Turner buscan rescatar a Elizabeth Swann y recuperar el Perla Negra de los piratas malditos liderados por el capitán Barbossa.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    id: "M131",
    review: ``,
    favourite: true,
    score: 8,
  },
  {
    name: "Piratas del Caribe: El cofre del hombre muerto",
    author: "Gore Verbinski",
    plot: `Jack Sparrow se enfrenta al temible Davy Jones mientras busca el mítico Cofre del Hombre Muerto para salvarse de una eternidad de servidumbre.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    id: "M132",
    review: ``,
    favourite: false,
    score: 8,
  },
  {
    name: "Piratas del Caribe: En el fin del mundo",
    author: "Gore Verbinski",
    plot: `Will Turner, Elizabeth Swann y el Capitán Barbossa buscan rescatar a Jack Sparrow de la tierra de los muertos y detener los planes de la Compañía de las Indias Orientales.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    id: "M133",
    review: ``,
    favourite: false,
    score: 8,
  },
  {
    name: "Piratas del Caribe: Navegando aguas misteriosas",
    author: "Rob Marshall",
    plot: `Jack Sparrow busca la Fuente de la Juventud mientras se enfrenta a nuevos enemigos como Barbanegra y viejos conocidos como Angelica.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    id: "M134",
    review: `No me parece tan mala pero tampoco es tan buena como las anteriores.`,
    favourite: false,
    score: 7,
  },
  {
    name: "Piratas del Caribe: La venganza de Salazar",
    author: "Joachim Rønning, Espen Sandberg",
    plot: `El Capitán Jack Sparrow debe encontrar el Tridente de Poseidón para derrotar a su antiguo enemigo, el Capitán Salazar, y salvarse de su venganza.`,
    genres: ["Acción", "Aventura", "Fantasía"],
    id: "M135",
    review: `Un desastre, fui a verla al cine y me trae flashbacks de Vietnam recordarla…`,
    favourite: false,
    score: 4,
  },
  {
    name: "El amanecer de los muertos",
    author: "Zack Snyder",
    plot: `Un grupo de supervivientes se refugia en un centro comercial mientras un apocalipsis zombi arrasa con la humanidad, enfrentándose a la amenaza externa y a conflictos internos.`,
    genres: ["Acción", "Horror"],
    id: "M136",
    review: `Entretenida al menos, de chico me gustaba bastante.`,
    favourite: false,
    score: 6,
  },
  {
    name: "La isla",
    author: "Michael Bay",
    plot: `Un hombre descubre que su vida en una utopía futurista es una mentira y que él y otros son clones creados para proporcionar órganos a sus originales. Escapa para encontrar la verdad y su libertad.`,
    genres: ["Acción", "Ciencia ficción", "Suspenso"],
    id: "M137",
    review: ``,
    favourite: false,
    score: 6,
  },
  {
    name: "El plan perfecto",
    author: "Spike Lee",
    plot: `Un detective de Nueva York enfrenta un asalto bancario altamente organizado y trata de resolver el misterio detrás del robo mientras se desentrañan múltiples capas de engaño.`,
    genres: ["Crimen", "Drama", "Suspenso"],
    id: "M138",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "La leyenda del tesoro perdido",
    author: "Jon Turteltaub",
    plot: `Un cazador de tesoros sigue una serie de pistas para descubrir un vasto tesoro escondido por los Padres Fundadores de los Estados Unidos, enfrentándose a competidores y peligros a lo largo del camino.`,
    genres: ["Acción", "Aventura", "Misterio"],
    id: "M140",
    review: `Como para pasar un rato igual que la segunda`,
    favourite: false,
    score: 6,
  },
  {
    name: "La leyenda del tesoro perdido: El libro de los secretos",
    author: "Jon Turteltaub",
    plot: `El cazador de tesoros Ben Gates se embarca en una nueva aventura para limpiar el nombre de su antepasado y descubrir la verdad detrás del asesinato de Abraham Lincoln, utilizando un libro de secretos que revela información clasificada.`,
    genres: ["Acción", "Aventura", "Misterio"],
    id: "M141",
    review: `Como para pasar un rato igual que la primera`,
    favourite: false,
    score: 6,
  },
  {
    name: "Django Unchained",
    author: "Quentin Tarantino",
    plot: `Ambientada en el sur de Estados Unidos dos años antes de la Guerra Civil, Django Unchained sigue la historia de Django, un esclavo liberado que, con la ayuda de un cazador de recompensas alemán, busca rescatar a su esposa de un brutal terrateniente de Mississippi.`,
    genres: ["Drama", "Western"],
    id: "M142",
    review: `Excelente película que núnca me voy a cansar de ver`,
    favourite: true,
    score: 10,
  },
  {
    name: "The Martian",
    author: "Ridley Scott",
    plot: `El astronauta Mark Watney se encuentra varado en Marte después de una misión fallida. Con recursos limitados, Watney utiliza su ingenio y habilidades científicas para sobrevivir y encontrar una manera de comunicarse con la Tierra para organizar su rescate.`,
    genres: ["Aventura", "Ciencia ficción", "Drama"],
    id: "M143",
    review: ``,
    favourite: true,
    score: 8,
  },
  {
    name: "V de Vendetta",
    author: "James McTeigue",
    plot: `En una distopía totalitaria, un vigilante enmascarado conocido como "V" lidera una revolución contra el régimen opresivo, utilizando tácticas guerrilleras y explosivos para luchar contra el gobierno. Una joven llamada Evey se convierte en su aliada mientras "V" busca justicia y libertad.`,
    genres: ["Acción", "Drama"],
    id: "M144",
    review: ``,
    favourite: true,
    score: 8,
  },
  {
    name: "El Tren Bala",
    author: "David Leitch",
    plot: `Cinco asesinos a sueldo se encuentran a bordo de un tren bala que viaja a gran velocidad de Tokio a Morioka. A medida que avanzan, descubren que sus misiones están interconectadas, desatando una serie de enfrentamientos letales mientras intentan cumplir con sus objetivos.`,
    genres: ["Acción", "Suspenso", "Comedia"],
    id: "M145",
    review: ``,
    favourite: true,
    score: 8,
  },
];

export default completedMovies;
