// start id with "S" for series and a number after that
let completedSeries = [
  {
    id: "S1",
    name: "Godless",
    author: "Scott Frank",
    plot: `Frank Griffin, un despiadado bandido que está aterrorizando una amplia zona del oeste americano de 1880, va a la caza del joven Roy Goode, un antiguo protegido suyo reconvertido en su mayor enemigo. Roy, huyendo de Frank y su temida banda, se esconde en un rancho de La Belle, Nuevo México, una ciudad compuesta mayormente por mujeres viudas tras el derrumbamiento de la mina donde trabajaban los hombres`,
    review: `Linda series para ver y pasar un buen rato.`,
    genres: ["Western", "Drama"],
    favourite: false,
    score: 7,
  },
  {
    id: "S2",
    name: "Vikingos",
    author: "Michael Hirst",
    plot: `Narra las aventuras del héroe Ragnar Lothbrok, de sus hermanos vikingos y su familia, cuando él se subleva para convertirse en el rey de las tribus vikingas. Además de ser un guerrero valiente, Ragnar encarna las tradiciones nórdicas de la devoción a los dioses. Según la leyenda era descendiente directo del dios Odín.`,
    review: `Muy buena serie para matonear. Tiene muy buenos personajes con los que uno se encariña y se engancha para saber que les pasa a continuación`,
    genres: ["Acción", "Drama", "Bélico"],
    favourite: true,
    score: 8,
  },
  {
    id: "S3",
    name: "El marginal",
    author: "Sebastián Ortega",
    plot: `Mientras investiga un secuestro, un expolicía se infiltra en una cárcel, donde deberá evitar que los peligrosos criminales descubran su verdadera identidad.`,
    review: `Muy buena serie, aunque tiene sus altos y bajos a lo largo de todas sus temporadas. De todas formas, los personajes están muy bien logrados y sin duda alguna se destacan Antin y Mario. `,
    genres: ["Thriller", "Drama", "Policíaco"],
    favourite: false,
    score: 7,
  },
  {
    id: "S4",
    name: "BoJack Horseman",
    author: "Raphael Bob-Waksberg",
    plot: `En un mundo donde humanos y animales antropomórficos conviven, el protagonista de la serie es el caballo BoJack Horseman (Will Arnett), protagonista de la telecomedia "Horsin' Around" en la década de los 90. Después de años de decadencia y una tormentosa vida personal, BoJack se propone volver al candelero a través de una autobiografía para la que contará con ayuda de una escritora fantasma, Diane Nguyen (Alison Brie). Pero BoJack también tendrá que lidiar con las exigencias de su exnovia y agente, la gata Princess Carolyn, su compañero de piso, Todd Chávez, y su amienemigo Mr. Peanutbutter, un perro labrador que es novio de Diane y triunfó con una sitcom muy similar a "Horsin' Around".`,
    review: `Excelente serie que nos lleva por todo un viaje emocional. Es mucho más seria de lo que parece en un principio, tiene sus momentos intensos y serios ala vez que tiene sus momentos graciosos, casi siempre con cierto toque de humor negro. Muy recomendable. Lástima que Netflix la canceló una temporada antes de lo que querían los creadores… `,
    genres: ["Comedia", "Drama", "Animación"],
    favourite: true,
    score: 9,
  },
  {
    id: "S5",
    name: "Rick y Morty",
    author: "Dan Harmon / Justin Roiland",
    plot: `Comedia animada que narra las aventuras de un científico loco, Rick Sánchez, que regresa después de 20 años para vivir con su hija, su marido y sus hijos, Morty y Summer.`,
    review: `Muy entretenida como para pasar el rato`,
    genres: ["Ciencia ficción", "Comedia", "Animación"],
    favourite: true,
    score: 7,
  },
  {
    id: "S6",
    name: "Star Wars: la guerra de los clones",
    author: "Dave Filoni / George Lucas",
    plot: `Cada vez más Sistemas caen bajo el poder del Lado Oscuro. Anakin Skywalker y su Padawan Ahsoka Tano son enviados a una peligrosa misión. El Conde Dooku y sus siniestros agentes intentarán detenerlos...`,
    review: `Excelente serie animada, peak Star Wars. Es cierto que hay episodios que pueden ser más “infantiles” pero cuando despega la series es espectacular. Realmente se siente que se está luchando una guerra, mucho mejor que cualquiera de las series actuales si no fuera por...`,
    genres: ["Animación", "Ciencia ficción", "Aventuras", "Acción"],
    favourite: true,
    score: 8,
  },
  {
    id: "S7",
    name: "Andor",
    author: "Tony Gilroy",
    plot: `Ambientada cinco años antes de los eventos de la película Rogue One, la serie sigue al espía Cassian Andor durante los años de formación de la Alianza Rebelde.​ La serie muestra la transformación de Andor, un ladrón que se convierte en revolucionario y finalmente se une a la Rebelión contra el Imperio Galáctico.`,
    review: `Totalmente una de mis series favoritas, no solo como una serie de Star Wars, sino serie en general. Muy recomendable incluso si no sabes nada de Star Wars o si no te gusta. Es una versión mucho más seria que nos lleva a ver como se fue formando la rebelión, y no va a ser algo sencillo de lograr, realmente se siente la opresión del imperio y lo duro que es la vida de las personas bajo su régimen. Visualmente también es excelente. Esta serie arruinó Estar wars para mí, probablemente Disney no vuelva a hacer otra serie o una película de Star wars que se acerque a Andor, este es el nuevo estándar para mí y en el futuro no voy a poder aceptar menos que esto para la saga. `,
    genres: ["Ciencia ficción", "Aventuras", "Acción", "Drama"],
    favourite: true,
    score: 10,
  },
  {
    name: "Los Simpsons",
    author: "Matt Groening",
    plot: `Una comedia animada que sigue las aventuras y desventuras de la familia Simpson, formada por Homer, Marge, Bart, Lisa y Maggie, en la ciudad ficticia de Springfield.`,
    genres: ["Comedia", "Animación", "Familia"],
    id: "S8",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "2gether: The Series",
    author: "Weerachit Thongjila",
    plot: `Una comedia romántica tailandesa que narra la historia de Tine, un joven universitario que finge ser el novio de Sarawat para deshacerse de un admirador no deseado, pero los sentimientos entre ellos comienzan a desarrollarse.`,
    genres: ["Romance", "Comedia", "Drama"],
    id: "S9",
    review: ``,
    favourite: true,
    score: 9,
  },
  {
    name: "El problema de los 3 cuerpos",
    author: "Liu Cixin",
    plot: `Adaptación de la novela de ciencia ficción de Liu Cixin, en la que la humanidad se enfrenta a una inminente invasión alienígena después de que una señal de socorro enviada al espacio es respondida por una civilización en un sistema estelar triple.`,
    genres: ["Ciencia ficción", "Drama", "Misterio"],
    id: "S10",
    review: `Una buena adaptación, con algunos cambios respecto a los libros, pero bien hechos para poder adaptar la historia a una serie.`,
    favourite: false,
    score: 8,
  },
  {
    name: "Peaky Blinders",
    author: "Steven Knight",
    plot: `Un drama histórico que sigue las actividades delictivas de la familia Shelby, una pandilla de Birmingham, Inglaterra, justo después de la Primera Guerra Mundial.`,
    genres: ["Crimen", "Drama", "Historia"],
    id: "S11",
    review: ``,
    favourite: true,
    score: 9,
  },
  {
    name: "The Witcher",
    author: "Lauren Schmidt Hissrich",
    plot: `Basada en la serie de libros de Andrzej Sapkowski, sigue las aventuras del cazador de monstruos Geralt de Rivia en un mundo lleno de magia, intrigas políticas y criaturas sobrenaturales.`,
    genres: ["Fantasía", "Drama", "Aventura"],
    id: "S12",
    review: ``,
    favourite: false,
    score: 7,
  },
  {
    name: "Heartstopper",
    author: "Alice Oseman",
    plot: `Una serie basada en la novela gráfica de Alice Oseman, que sigue la relación entre dos chicos adolescentes, Charlie y Nick, que descubren su amor mutuo y navegan por las complicaciones de su vida escolar y personal.`,
    genres: ["Romance", "Drama", "LGBT"],
    id: "S13",
    review: `Muy linda serie. Lástima que algunas cosas del cómic no las pusieron en la serie, tal vez en la tercera temporada las podamos ver. `,
    favourite: true,
    score: 10,
  },
  {
    name: "Arcane",
    author: "Christian Linke, Alex Yee",
    plot: `Basada en el universo de League of Legends, esta serie animada explora la historia de dos emblemáticos campeones de la ciudad de Piltover y el submundo de Zaun, en un conflicto lleno de magia y tecnología.`,
    genres: ["Animación", "Fantasía", "Acción"],
    id: "S14",
    review: `Muy buena, realmente inesperado. Una cosa bien que hace Riot.`,
    favourite: false,
    score: 8,
  },
  {
    name: "The End of the F***ing World",
    author: "Charlie Covell",
    plot: `Dos adolescentes inadaptados, James y Alyssa, se embarcan en un viaje por carretera que pronto se convierte en una serie de aventuras peligrosas, mientras James lucha con su deseo de matar y Alyssa busca escapar de su vida problemática.`,
    genres: ["Comedia negra", "Drama", "Aventura"],
    id: "S15",
    review: ``,
    favourite: true,
    score: 9,
  },
  {
    name: "La caída de la Casa Usher",
    author: "Mike Flanagan",
    plot: `Basada en el cuento de Edgar Allan Poe, esta serie de terror sigue la historia de los últimos días de la ancestral y maldita Casa Usher, donde secretos oscuros y horrores familiares salen a la luz.`,
    genres: ["Horror", "Drama", "Misterio"],
    id: "S16",
    review: ``,
    favourite: false,
    score: 7,
  },
];

export default completedSeries;
