let completedGames = [
  {
    id: 1,
    name: "Baldur's Gate 3",
    author: "Larian Studios",
    plot: "Reúne a tu grupo y vuelve a los Reinos Olvidados en un relato de compañerismo y traición, sacrificio y supervivencia, además de la atracción de un poder absoluto.",
    review: `Nos da una cantidad de encuentro únicos con muchas decisiones para tomar las cuales tienen impacto real y duradero sobre la historia. Si te gusta el combate por turnos es excelente, con una gran
      variedad de encuentros y enemigos que enfrentar. Cuenta con una gran rejugabilidad, siendo cada partida diferente a la anterior. Simplemente el mejor juego de rol en existencia`,
    genres: ["Aventura, RPG, Estrategia"],
    favourite: true,
    score: 10,
  },
  {
    id: 2,
    name: "Dark Souls II: Scholar of the First Sin",
    author: "From Software",
    plot: "DARK SOULS™ II: Scholar of the First Sin lleva la característica oscuridad de la franquicia y su apasionante jugabilidad a un nuevo nivel. Únete al oscuro viaje y experimenta los sobrecogedores encuentros con enemigos, los peligros diabólicos y los desafíos implacables.",
    review: `Dark Souls 2 es para muchos la oveja negra de la saga souls. A pesar de que muchas de las críticas que recibe son apropiadas, como el spam de enemigos en algunas secciones, este juego sigue siendo un souls en toda regla. El desafío que caracteriza a la serie sigue estando presente y nos presenta con muy buenas zonas, como Majula, que vamos a poder disfrutar.
    Es un juego muy recomendable para todos los fanáticos de la saga souls o juegos de rol en general`,
    genres: ["Acción", "RPG", "Aventura"],
    favourite: false,
    score: 7,
  },
  {
    id: 3,
    name: "Dark Souls III",
    author: "From Software",
    plot: "Dark Souls continúa redefiniendo los límites con el nuevo y ambicioso capítulo de esta serie revolucionaria, tan aclamada por la crítica. ¡Prepárate para sumergirte en la oscuridad!",
    review: `Este fue mi primer souls y guarda un lugar en mi corazón. Uno de los mejores juegos de rol de nuestros tiempos. Si algo se destaca son los Bosses que son los más dinámicos de la trilogía. Un combate ágil pero aún conservando la esencial de los juegos anteriores.
     Probablemente el mejor lugar para arrancar sin tener en cuenta la última entrada en la serie (aka Elden Ring).`,
    genres: ["Acción", "RPG", "Aventura"],
    favourite: false,
    score: 9,
  },
  {
    id: 4,
    name: "Dark Souls",
    author: "From Software",
    plot: "Dark Souls es un juego de rol de acción de 2011 desarrollado por FromSoftware y publicado por Bandai Namco Entertainment. Sucesor espiritual de Demon's Souls, es el primer juego de la saga Dark Souls. El juego tiene lugar en el reino de Lordran, donde los jugadores asumen el papel de un personaje no muerto maldito que comienza una peregrinación para descubrir su destino.",
    review: `El último de la trilogía que juegue. La primera mitad del juego es perfecta, con una gran interconectividad de los escenarios y una ambientación espectacular. A partir de la mitad el juego baja un poco en calidad, pero de todas formas sigue siendo maravillosos. Incluso a día de hoy, aunque el combate puede ser un poco lento comparado con las entradas mas recientes en la serie, es un juego muy recomendable.`,
    genres: ["Acción", "RPG", "Aventura"],
    favourite: false,
    score: 8,
  },
  {
    id: 5,
    name: "Dead Cells",
    author: "Motion Twin",
    plot: "Dead Cells es un juego de acción de plataformas de estilo roguelite e inspirado en juegos tipo metroidvania. Explorarás un castillo en constante cambio y expansión, si es que logras abrirte paso contra los guardianes en los combates 2D de estilo Dark Souls.",
    review: `En general es un buen juego, pero me costó bastante. Me hubiese gustado jugarlo más pero luego de pasarlo varias veces se me volvió demasiado difícil seguir progresando. El estilo visual está bueno y cuenta con una buena banda sonora. `,
    genres: ["Acción", "Indie", "Roguelike"],
    favourite: false,
    score: 6,
  },
  {
    id: 6,
    name: "Deus Ex: Human Revolution",
    author: "Motion Twin",
    plot: "Juegas como Adam Jensen, un ex SWAT al que han escogido para supervisar las necesidades defensivas de una de las empresas de biotecnología más experimentales de América. Tu trabajo consiste en proteger los secretos de la empresa, pero, cuando irrumpe un equipo de operaciones encubiertas y mata a los mismos científicos que debías proteger, lo que creías saber sobre tu trabajo cambia totalmente.",
    review: `Muy buen juego de rol. En general no me gustan los juegos que implican sigilo, pero en este se cuentan con diferentes opciones para solucionar los niveles. Decidas utilizar 100% sigilo o no, no se puede negar que el sigilo y el gameplay pausado es un foco central del juego.`,
    genres: ["Acción", "RPG"],
    favourite: false,
    score: 7,
  },
  {
    id: 7,
    name: "Disco Elysium",
    author: "ZA/UM",
    plot: "Disco Elysium - The Final Cut es un revolucionario juego de rol de mundo abierto. Encarna a un detective con un conjunto único de habilidades a su disposición y un barrio entero que recorrer. Interroga personajes memorables, desentraña casos o acepta sobornos. Sé un héroe o un ser humano desastroso.",
    review: `Si te gusta leer probablemente vas a amar este juego. Lo que comienza como la simple resolución de un crimen muy rápidamente te va a llevar a conocer diferentes intrigas dentro del mundo. El juego implica leer muchos diálogos (podes estar media hora revisando una carpeta, por ejemplo) y en este caso es algo bueno. Tiene un componente de rol que se utiliza bien y un apartado visual que lo diferencia de otros juegos.`,
    genres: ["RPG"],
    favourite: false,
    score: 8,
  },
  {
    id: 8,
    name: "Dishonored 2",
    author: "Arkane Studios",
    plot: "Dishonored 2 tiene lugar 15 años después de la derrota del lord Regente. La temible peste ha pasado a la historia y un usurpador de otro mundo se ha hecho con el trono de la emperatriz Emily Kaldwin. El futuro de las islas pende de un hilo. Asume el papel de Emily o Corvo, y viaja más allá de las legendarias calles de Dunwall hasta Karnaca, una ciudad costera antaño deslumbrante, que alberga la clave para devolver a Emily al poder. Usa la marca del Forastero, así como nuevas y poderosas habilidades, para dar caza a tus enemigos y recuperar lo que te pertenece por derecho.",
    review: `Un gran juego con muchos poderes para utilizar. En lo personal la historia nunca me pareció nada del otro mundo, sin embargo, cuenta con un gameplay muy divertido. En general es una gran mejoría respecto al primero`,
    genres: ["Acción"],
    favourite: false,
    score: 7,
  },
  {
    id: 9,
    name: "Divinity Original Sin 2",
    author: "Larian Studios",
    plot: "Reúne a tu grupo. Domina el combate táctico profundo. Aventúrate con un grupo de hasta cuatro personas, pero debes saber que solo uno de ustedes tendrá la oportunidad de convertirse en Dios.",
    review: `Muy buen combate por turnos. Hoy en día puede quedar un poco en las sombras de BG 3 pero aún así es muy recomendable jugarlo. Una buena historia y cuenta con diferentes opciones a la hora de superar los desafíos planteados.`,
    genres: ["Aventura, RPG, Estrategia"],
    favourite: false,
    score: 8,
  },
  {
    id: 10,
    name: "Elden Ring",
    author: "From Software",
    plot: "Elden Ring es un RPG de fantasía oscura que te permite encarnar a uno de los descendientes de los Sinluz. Deberás adentrarte en las Tierras Intermedias para intentar ser readmitido en esa sociedad como un Señor del Círculo. Para ello, deberás desvelar el misterio del legendario Círculo de Elden. Tus aventuras en las Tierras Intermedias estarán llenas de amenazas y rebosarán de incógnitas.",
    review: `El combate perfecto de los souls junto con un mundo abierto totalmente interconectado y paisajes espectaculares crean el juego perfecto. Desafiante pero justo a la vez que nos da opciones con las que hacer más fácil los enfrentamientos si así lo deseamos, esto lo hace el punto perfecto para adentrarse en la saga. Bosses memorables que le dan el detalle final al juego para convertirlo en un clásico. Este es el mundo abierto definitivo.`,
    genres: ["Acción", "RPG", "Aventura"],
    favourite: true,
    score: 10,
  },
  {
    id: 11,
    name: "Enter the Gungeon",
    author: "Dodge Roll",
    plot: "Enter the Gungeon es un dungeon crawler de tiroteos que sigue a una banda de marginados arrepentidos en su intento de conseguir la absolución personal a base de disparar, saquear, dar volteretas y voltear mesas para alcanzar el tesoro supremo de la legendaria Armazmorra: el arma que puede matar el pasado. Elige un héroe y ábrete paso a tiros hasta el fondo de la Armazmorra, sobreviviendo a una desafiante y siempre cambiante serie de plantas llenas de los peligrosamente adorables armuertos y temibles jefes de la Armazmorra, armados hasta los dientes.",
    review: `Un buen juego para pasar el rato. Cada run es diferente y uno siempre tiene la expectativa sobre las armas que le van a tocar. Está buena la temática de matar el pasado y cuenta con un buen estilo visual. `,
    genres: ["Acción", "Roguelike", "Indie"],
    favourite: false,
    score: 7,
  },
  {
    id: 12,
    name: "Fallout: New Vegas",
    author: "Obsidian Entertainment",
    plot: "Es una de esas ciudades en las que cavas tu propia tumba antes de que te peguen un tiro en la cabeza para dejarte morir solo… y eso es antes de que las cosas se pongan realmente feas. Es una ciudad de soñadores y forajidos que se está desgarrando por la lucha entre las facciones que ansían hacerse con el control total de este oasis en pleno desierto. Es un lugar donde las personas apropiadas con el armamento adecuado pueden hacer historia, y de paso hacer algo más que un par de enemigos.",
    review: `Aunque a día de hoy visualmente se queda atrás sigue siendo un excelente juego de rol. Un buen diseño del mundo y como alguien que nunca había jugado un fallout antes, nunca sabia que me iba a encontrar a continuación. Vale la pena jugarlo!`,
    genres: ["Acción", "RPG"],
    favourite: false,
    score: 7,
  },
  {
    id: 13,
    name: "Forager",
    author: "HopFrog",
    plot: "Explora, craftea, junta y administra recursos, encuentra tesoros y secretos y construye tu base desde la nada! ¡Compra tierras para explorar y expandirte!",
    review: `Un buen juego como para pasar el rato. Excelente para jugar mientras se tienen clases de Zoom! `,
    genres: ["Indie", "Simulación"],
    favourite: false,
    score: 5,
  },
  {
    id: 14,
    name: "Gris",
    author: "Nomada Studio",
    plot: "Gris es una muchacha llena de esperanzas y perdida en su propio mundo, enfrentada a una experiencia dolorosa de su vida.",
    review: `El estilo visual es excelente y es de esos juegos que realmente te hacen sentir algo.  ¡Es mejor simplemente jugarlo sin saber mucho, no sé qué están esperando!`,
    genres: ["Indie", "Aventura"],
    favourite: false,
    score: 7,
  },
  {
    id: 15,
    name: "Hades",
    author: "Supergiant Games",
    plot: "Desafía al dios de los muertos y protagoniza una salvaje fuga del Inframundo en este juego de exploración de mazmorras de los creadores de Bastion, Transistor y Pyre.",
    review: `¡Es el roguelike perfecto! A diferencia de muchos juegos del género que he jugado este te engancha con la historia. Usualmente perder y tener que volver a empezar suele ser pesado en muchos roguelikes pero en este a uno no se le hace tan pesado porque puede ver que hay de nuevo en el hub e interactuar con los personajes para continuar con la historia. Un gameplay rápido y entretenido, con muchas opciones. Visualmente único y una temática con los dioses griegos que lo hacen especial.`,
    genres: ["Indie", "Roguelike", "Acción"],
    favourite: true,
    score: 9,
  },
  {
    id: 16,
    name: "Hollow Knight",
    author: "Team Cherry",
    plot: "Hollow Knight es una aventura de acción clásica en 2D ambientada en un vasto mundo interconectado. Explora cavernas tortuosas, ciudades antiguas y páramos mortales. Combate contra criaturas corrompidas, haz amistad con extraños insectos y resuelve los antiguos misterios que yacen en el corazón de reino.",
    review: `Muy buen juego con zonas interconectadas que, al típico estilo de los Metroidvania, vamos a poder ir accediendo a medida que adquirimos nuevos poderes. Si algo me gusta particularmente de este juego es el apartado visual que lo distingue y crea una buena ambientación junto con la banda sonora. El combate es difícil pero justo y lo mismo se puede decir respecto al plataformeo que va a poner aprueba nuestras habilidades.`,
    genres: ["Indie", "Aventura", "Acción", "Metroidvania", "Plataformas"],
    favourite: true,
    score: 9,
  },
  {
    id: 17,
    name: "Kerbal Space Program",
    author: "Squad",
    plot: "En Kerbal Space Program, dirige el programa espacial de una raza alienígena conocida como los Kerbals. Utiliza una gran variedad de piezas para construir naves espaciales completamente funcionales que volarán (o no) en función de las leyes de la aerodinámica y la física orbital.",
    review: `Muy buen juego de simulación, tan bueno que lo utilizó un profesor de facultad para explicarnos el aterrizaje en la luna. Cuenta con una simulación muy realista lo cual es bueno y malos a la vez ya que crean una experiencia que puede ser frustrante si no logras entender bien como funcionan las cosas. Por otro lado esta complejidad nos da una experiencia realista y un sentido de logro muy grande cuando nos salen las cosas. `,
    genres: ["Indie", "Simulación"],
    favourite: false,
    score: 7,
  },
  {
    id: 18,
    name: "Missed Messages",
    author: "Angela He",
    plot: "El iPhone de tu novia gótica te lanza desde el aire: ¿aceptar o rechazar? Una historia de amor/horror sobre la vida, la muerte y los memes.",
    review: `Pequeño juego free to play que nos da una experiencia interesante para pensar, no hay excusa para no jugarlo`,
    genres: ["Indie", "Simulación", "Casual", "Free-to-play", "Visual Novel"],
    favourite: false,
    score: 5,
  },
  {
    id: 19,
    name: "My time at Portia",
    author: "Pathea Games",
    plot: "¡Empieza una nueva vida en la encantadora ciudad de Portia! ¡Devuelve el taller abandonado de tu padre a su antigua gloria completando encargos, cultivando, criando animales y entablando amistad con los peculiares habitantes de esta encantadora tierra postapocalíptica!",
    review: `Juego muy relajante y diferente a lo que usualmente juego. Muy bueno para pasar un buen rato tranquilo ya se contrayendo, cultivando, peleando con enemigos o teniendo la vida social que no tenes en la vida real. Como punto negativo se puede decir que tiene varios bugs que pueden ser molestos, pero no destruyen la experiencia. ¡Excelente si jugaste al Stardew Valley y buscas algo parecido!`,
    genres: ["Aventura", "Simulación", "Casual", "Indie", "RPG"],
    favourite: false,
    score: 8,
  },
  {
    id: 20,
    name: "Ni No Kuni II",
    author: "Level 5",
    plot: "Únete al joven rey Evan mientras emprende una búsqueda épica para fundar un nuevo reino y, con la ayuda de algunos nuevos amigos, unir su mundo, salvando a su gente de un mal terrible.",
    review: `En cierta medida un clásico juego de rol japonés. Personalmente me gustó la banda sonora y la historia está bien. El combate es aceptable pero tampoco tiene nada que sea destacable. En general un buen juego que en todo caso puede llegar a convertirse repetitivo por fuera de las misiones principales.`,
    genres: ["Aventura", "RPG", "JRPG"],
    favourite: false,
    score: 7,
  },
  {
    id: 21,
    name: "Nioh: Complete Edition",
    author: "Koei Tecmo Games",
    plot: "En la era de los samuráis, un viajero solitario aterriza en las costas de Japón. Debe abrirse camino a través de los feroces guerreros y los Yokai sobrenaturales que infestan la tierra para encontrar lo que busca.",
    review: `Un juego difícil que intenta ser dark souls pero no lo logra. En genera es un buen juego con buenas ideas que lo diferencias de otros souls-like pero no logra terminar de convencerme. La historia y el apartado visual no son especialmente de mi agrado. El combate está bien y posibilita usar diferentes armas y formas de pelear. En conclusión, un buen juego que no lo considero especial en ningún apartado. `,
    genres: ["Aventura", "RPG", "Acción"],
    favourite: false,
    score: 6,
  },
  {
    id: 22,
    name: "Omori",
    author: "Omocat",
    plot: "Explora un mundo extraño lleno de coloridos amigos y enemigos. Cuando llegue el momento, el camino que hayas elegido determinará tu destino... y quizás también el destino de los demás.",
    review: `Este si es un juego de esos que te destruyen emocionalmente. Jugar a Omori es emprenderse en todo un viaje emocional que puede tener tanto un final agradable o uno terrible. Si algo se destaca es la historia y la forma en que realmente uno logra ponerse en el lugar de Sunny, el personaje principal. Al final debemos seguir adelante…`,
    genres: ["Aventura", "RPG", "Indie", "Terror"],
    favourite: true,
    score: 9,
  },
  {
    id: 23,
    name: "Operation Tango",
    author: "Clever Plays",
    plot: "Operation: Tango es una aventura de espionaje en equipo que os desafiará a ti y a un amigo a cumplir peligrosas misiones por todo el mundo en un futuro cercano altamente tecnológico. En un equipo exclusivo de dos personas, tú y tu compañero seréis AGENTE y HACKER, y trabajaréis juntos para infiltraros, investigar y acabar con las fuerzas que amenazan al mundo libre. Trabaja en equipo con dos puntos de vista diferentes y utilizando únicamente la voz para comunicarte. ¡El trabajo en equipo es vital y la comunicación es clave!",
    review: `Buen juego para jugar en cooperativo con un amigo. La temática de espías es entretenida y el juego requiere buena coordinación. Lo único malo es su corta duración. `,
    genres: ["Aventura", "Casual"],
    favourite: false,
    score: 6,
  },
  {
    id: 24,
    name: "Our Life: Beginnings & always",
    author: "GB Patch Games",
    plot: "Un billete de veinte dólares, cuatro veranos, quince años y una vida única. Crea una experiencia propia en esta novela visual casi totalmente personalizable en la que creces desde la niñez hasta la edad adulta con el chico solitario de al lado.",
    review: `Entretenida novela visual como para pasar el rato. Recomendable solo si te gustan los dating sim o juegos similares.`,
    genres: ["Aventura", "RPG", "Indie"],
    favourite: false,
    score: 6,
  },
  {
    id: 25,
    name: "Persona 4",
    author: "Atlus",
    plot: "Una historia que sitúa al protagonista y a sus amigos en un viaje iniciado por una cadena de asesinatos en serie. Explore el encuentro con espíritus afines, los sentimientos de pertenencia e incluso la confrontación de los lados más oscuros de uno mismo.",
    review: `Espectacular juego en todos los aspectos si se tiene en cuenta que ya cuenta con unos cuantos años. La historia, que es el apartado que más se destaca, nos va a dejar un gran mensaje de autoaceptación. El cast de personajes está muy bien logrado y es memorable. Los aspectos sociales afectan al combate y esto nos da un motivo extra para ver las historias de los personajes secundarios. El combate es un muy buen combate por turnos, lo único malo es que puede llegar a convertirse repetitivo teniendo en cuenta la larga duración del juego. Las dungeons cuenta cada una con una temática diferente pero no se diferencian mecánicamente lo cual es un poco decepcionante. En conjunto un gran juego que destaca por su historia haciendo que le perdonemos sus años y lo juguemos de todas formas. Tenemos que tener la fuerza para enfrentarnos a nosotros mismo y aceptar quienes somos. `,
    genres: ["RPG", "JRPG"],
    favourite: true,
    score: 9,
  },
  {
    id: 26,
    name: "Persona 5",
    author: "Atlus",
    plot: "¡Ponte la máscara y únete a los Phantom Thieves mientras organizan grandes atracos, se infiltran en las mentes de los corruptos y les hacen cambiar sus costumbres!",
    review: `¡El poder de rebelarse contra la realidad! Combate por turnos espectacular, es una clara mejora respecto al 4. También mejora respecto a las dungeons (llamados palacios en el juego). Una temática interesante que nos lleva junto al cast de personajes en una travesía a rebelarnos contra una realidad injusta. En general un gran juego, pero, comparado tanto con el 3 y el 4, la historia la siento un poco más floja. De todas formas, muy recomendable y tal vez el mejor lugar para empezar con la serie. `,
    genres: ["RPG", "JRPG"],
    favourite: false,
    score: 8,
  },
  {
    id: 27,
    name: "Persona 3 Reload",
    author: "Atlus",
    plot: "Ponte en la piel de un estudiante transferido arrojado a un destino inesperado al entrar en la hora oculta entre un día y el siguiente. Despierta un poder increíble y persigue los misterios de la Hora Oscura, lucha por tus amigos y deja una huella en sus recuerdos para siempre.",
    review: `La experiencia definitiva de la serie. La combinación perfecta entre un combate y gráficos más modernos, junto con la increíble historia de Persona 3. Antes de jugarlo el persona 4 era mi favorito, pero este lo supera fácilmente. La historia tiene un tono mucho más serio respecto al 4 y el 5 y personalmente eso lo hace 1000 veces mejor. El combate toma ideas del 5 para darle un nuevo giro y se cambia un poco el Tártaro (la dungeon del juego) para no hacerlo tan monótono.  Los personajes son memorables y se sienten como personas reales que tienen sus propios problemas más allá del conflicto principal. La muerte es inevitable pero la marca que dejamos en las personas a nuestro alrededor perdura aun después de nuestro final. Debemos buscar nuestro propósito y aceptar el cambio. `,
    genres: ["RPG", "JRPG"],
    favourite: true,
    score: 10,
  },
  {
    id: 28,
    name: "The Red String Club",
    author: "Deconstructeam",
    plot: "The Red Strings Club es una experiencia narrativa ciberpunk sobre el destino y la felicidad que presenta el uso extensivo de cerámica, servicio de bar y suplantación de personas por teléfono para acabar con una conspiración corporativa.",
    review: `Un buen juego para pasar un buen rato. La historia es interesante pero es de corta duración y no cuenta con mucho gameplay. De todas formas debería volver a jugarlo para probar diferentes opciones que se presentan`,
    genres: ["Aventura", "Indie"],
    favourite: false,
    score: 6,
  },
  {
    id: 29,
    name: "Slay the Spire",
    author: "Mega Crit",
    plot: "Fusionamos juegos de cartas y roguelikes para crear el mejor creador de mazos para un jugador que pudimos. ¡Crea una baraja única, encuentra criaturas extrañas, descubre reliquias de inmenso poder y mata a Spire!",
    review: `Un buen juego peor no es mi estilo. Fué entretenido jugarlo pero luego de un rato se me hizo aburrido y repetitivo`,
    genres: ["Roguelike", "Estrategia", "Indie"],
    favourite: false,
    score: 6,
  },
  {
    id: 30,
    name: "Stardew Valley",
    author: "ConcernedApe",
    plot: "Has heredado la antigua granja de tu abuelo en Stardew Valley. Armado con herramientas usadas y algunas monedas, te dispones a comenzar tu nueva vida. ¿Podrás aprender a vivir de la tierra y convertir estos campos cubiertos de maleza en un hogar próspero?",
    review: `Un juego tranquilo y relajante. Uno puede tryhardear hasta el punto que quiera, puede planear cada día para optimizarlo lo máximo posible o puede jugar de forma tranquila. Yo elijo la primera. Combina aspectos sociales, combate y simulación para dar con una combinación perfecta. Es de los pocos juegos que hice al 100% y eso tendría que ser muestra de su calidad. Es un lugar seguro donde distraerse de nuestros problemas, aunque sea por un rato.  El hecho de que este juego lo desarrollara una sola persona es digno de reconocimiento y una clara muestra de dedicación.  PD: Sebastian best boy y nadie me va a contradecir.`,
    genres: ["Indie", "RPG", "Simulación", "Casual"],
    favourite: true,
    score: 10,
  },
  {
    id: 31,
    name: "Synthetik: Legion Rising",
    author: "Flow Fire Games",
    plot: "SYNTHETIK es un implacable juego de disparos táctico rogue-lite donde la libertad y la experimentación son clave. Lucha en un mundo invadido por la Legión de las Máquinas y sus dioses. Experimenta el siguiente nivel en el juego de armas y sumérgete en opciones de construcción y actualizaciones de Android incomparables. ¿Podrás derrotar al Corazón de Armageddon?",
    review: `Un agradable juego para pasar el rato, principalmente si es con amigos. Como dato creo que nunca pude matar al boss final pero eso es más muestra de mi incompetencia que otra cosa.`,
    genres: ["Acción", "Indie"],
    favourite: false,
    score: 6,
  },
  {
    id: 32,
    name: "Transistor",
    author: "Supergiant Games",
    plot: "Descubre el mundo de Transistor, un juego de rol de acción con temática de ciencia ficción de los creadores de Bastion.",
    review: `Un lindo juego tanto en gameplay como en apartado visual. En lo personal no me causa grandes pasiones`,
    genres: ["Acción", "RPG", "Indie"],
    favourite: false,
    score: 6,
  },
  {
    id: 33,
    name: "Valkyria Chronicles 4",
    author: "Sega",
    plot: "¡Un continente envuelto en las amargas llamas de la guerra! El comandante Claude Wallace y sus amigos de la infancia se propusieron luchar en una guerra desesperada, pero tormentas de nieve escalofriantes, oleadas de soldados imperiales y los poderes divinos de la Valkyria se interponen entre ellos y la victoria.",
    review: `Cuenta con buen combate por turnos y enfrentamientos variados y entretenidos. La progresión no se siente mucho, aunque cuenta con una. La historia es entretenida y se desarrolla a un ritmo correcto. Cada batalla es un puzle a resolver y esta en nuestras manos decidir cómo. `,
    genres: ["Acción", "RPG", "Estrategia"],
    favourite: false,
    score: 8,
  },
  {
    id: 34,
    name: "The Witcher 3",
    author: "CD Projekt Red",
    plot: "Eres Geralt de Rivia, cazador de monstruos. En un continente devastado por la guerra e infestado de criaturas, tu misión es encontrar a Ciri, la niña de la profecía, un arma viviente que puede alterar el mundo tal y como lo conocemos.",
    review: `Witcher 3 es el juego perfecto en muchos sentidos. El gamplay cumple su función y contamos con distintas maneras de prepararnos y encarar los enfrentamientos. Lo que realmente destaca del juego es su inccreible historia, con personajes que se sienten reales. Podemos tomar decisiones que tienen un impacto real y duradero en la historia y nos van a hacer dudar si realmente elegimos de forma correcta. El mundo esta genial y ayuda a colocarnos mejor en el lugar de Geralt en esta aventura. Sus DLCs podrían ser juegos por si solos y nos presentan grandes historias que expanden en los vivido en las misiones principales. Tenemos decenas de horas perfectamente pudiendo llegar a las centenas si nos adentramos en las misiones secundarias, muchas de las cuales son de igual calidad, o mejor incluso, que las misiones principales. No hay excusa para no jugar este juego.`,
    genres: ["Aventura", "RPG"],
    favourite: true,
    score: 10,
  },
  {
    id: 35,
    name: "Xcom 2",
    author: "Firaxis Games",
    plot: "Los alienígenas dominan la tierra y prometen un futuro brillante para la humanidad mientras ocultan sus siniestros planes. Ponte en la piel del líder de una guerrilla y, con todo en tu contra, prende la llama de la resistencia mundial para acabar con la amenaza alienígena y salvar a la raza humana de la extinción.",
    review: `Una prueba total a la paciencia. Buen juego con combate por turnos y excelente progresión. A medida que uno va consiguiendo mejore equipo se van desbloqueando mayores desafíos. De todas formas, el juego puede ser duro de a momentos, perder un soldado de alto nivel en medio de una partida puede ser devastador. Recomendado solo si quieres ponerte a prueba. Ese 10% de posibilidad de embocar el disparo nunca sale y el 90% siempre se falla, suerte.`,
    genres: ["Estrategia"],
    favourite: false,
    score: 7,
  },
  {
    id: 36,
    name: "Yakuza 0",
    author: "Ryu Ga Gotoku Studio",
    plot: "Lucha en Tokio y Osaka con el protagonista Kazuma Kiryu y el habitual de la serie Goro Majima. Juega como Kazuma Kiryu y descubre cómo se encuentra en un mundo de problemas cuando un simple cobro de deudas sale mal y su objetivo termina asesinado. Luego, ponte en los zapatos de punta plateada de Goro Majima y explora su vida 'normal' como propietario de un club de cabaret.",
    review: `Los Yakuza son muy particulares y uno se da cuenta enseguida. Cuentan con una historia bastante serie que nos lleva por toda una serie de problemas que debemos superar junto a los protagonistas. A su vez, tenemos también  una misión secundaria en la que debemos defender a Miracle Johnson (Aka Michael Jackson) mientras baila. Cuenta con una mezcla interesante de seriedad y ‘goofiness’ que lo hacen único. Un combate rápido y divertido con los diferentes combos posibles, además de contar con muchas habilidades para ir desbloqueando. Excelente juego que se sale de la norma si no conocías esta serie como era mi caso antes de jugarlo.`,
    genres: ["Aventura", "RPG", "Acción"],
    favourite: false,
    score: 8,
  },
  {
    id: 37,
    name: "Darkest Dungeon",
    author: "Red Hook Studios",
    plot: "Darkest Dungeon es un desafiante juego de rol gótico roguelike por turnos sobre el estrés psicológico de la aventura. Recluta, entrena y lidera un equipo de héroes imperfectos contra horrores inimaginables, estrés, enfermedades y la oscuridad cada vez más invasiva. ¿Podrás mantener unidos a tus héroes cuando se pierda toda esperanza?",
    review: `Un juego desafiante, pero, acá viene la opinión controversial, justo. A pesar de que el resultado de casi todo depende del azar, tu misión como jugador es hacer todo lo posible por reducir los efectos de este al mínimo. Esto se hace mejorando a los personajes, eligiendo las composiciones apropiadas para cada zona, usando diferentes trinckets, etc. Se cuenta con una variedad de opciones respecto a como jugar (personajes y habilidades). Enemigos variados que representan un peligro verdadero y nos hacen plantearnos si realmente vale la pena arriesgarlo todo por un poco más de loot. En todo caso, a no ser que juegues en la máxima dificultad donde hay un límite de tiempo, siempre es posible recuperarse y volver a empezar. Una prueba a la paciencia y perseverancia. `,
    genres: ["Estrategia", "RPG", "Indie"],
    favourite: true,
    score: 9,
  },
  {
    id: 38,
    name: "Battle for Wesnoth",
    author: "The Battle for Wesnoth Project",
    plot: "La Batalla for Wesnoth es un juego de estrategia basado en turnos de código abierto con un tema de alta fantasía. Explore todos los rincones de Irdya y tome parte de un sinnúmero de aventuras en diecisiete campañas para un solo jugador y docenas de mapas multijugador.",
    review: ``,
    genres: ["Estrategia", "Free-to-play", "Indie"],
    favourite: false,
    score: 6,
  },
  {
    id: 39,
    name: "Divinity: Original Sin - Enhanced Edition",
    author: "Larian Studios",
    plot: "Divinity: Original Sin es un juego que te brinda mucha libertad y muchas mecánicas de juego para usar o abusar. La historia épica del juego puede llevarte hacia tu objetivo final, pero cómo llegar allí depende totalmente de ti.",
    review: ``,
    genres: ["Aventura", "RPG", "Indie", "Estrategia"],
    favourite: false,
    score: 6,
  },
  {
    id: 40,
    name: "FTL: Faster Than Light",
    author: "Subset Games",
    plot: "Este simulador de exploración espacial te permite vivir una gran aventura con tu nave y su tripulación. Descubre una galaxia que se genera aleatoriamente y en la que te encontrarás tanto momentos de gloria como amargas derrotas.",
    review: ``,
    genres: ["Simulación", "Estrategia", "Indie"],
    favourite: false,
    score: 5,
  },
  {
    id: 41,
    name: "Graveyard Keeper",
    author: "Lazy Bear Games",
    plot: "Los creadores de Punch Club nos traen Graveyard Keeper, el simulador de gestión de cementerios medievales más impreciso de la historia.",
    review: ``,
    genres: ["Aventura", "RPG", "Indie", "Simulación"],
    favourite: false,
    score: 6,
  },
  {
    id: 42,
    name: "Stronghold Crusader HD",
    author: "FireFly Studios",
    plot: "La muy esprada secuela del super ventas Stronghold, Stronghold Crusader HD te sumerge en batallas históricas y en asedios de castillos de las Cruzadas contra diabólicos oponentes de la IA, nuevas unidades, 4 campañas históricas y cerca de 100 misiones escaramuza únicas.",
    review: ``,
    genres: ["Estrategia", "Simulación"],
    favourite: false,
    score: 7,
  },
  {
    id: 43,
    name: "Tales of Berseria",
    author: "Bandai Namco",
    plot: "Los jugadores emprenden un viaje de autodescubrimiento adoptando el rol de Velvet, una joven cuya personalidad, antaño dulce, ha sido sustituida por una ira y un odio exacerbados producto de una traumática experiencia ocurrida tres años antes de los eventos de Tales of Berseria.",
    review: ``,
    genres: ["Acción", "RPG"],
    favourite: false,
    score: 6,
  },
  {
    id: 44,
    name: "This War of Mine",
    author: "11 bit studios",
    plot: "En This War of Mine encarnarás a un grupo de civiles que tratan de sobrevivir en una ciudad asediada por la guerra: no tendrás suficientes medicinas ni comida, y estarás bajo el peligro constante de francotiradores y otros civiles. Vive la guerra desde un ángulo totalmente nuevo.",
    review: ``,
    genres: ["Aventura", "Indie", "Simulación"],
    favourite: false,
    score: 7,
  },
  {
    id: 45,
    name: "BioShock",
    author: "2K",
    plot: "BioShock es un shooter distinto a todos los que has jugado antes, lleno de armas y tácticas nunca vistas. Tendrás un completo arsenal a tu disposición: desde sencillos revólveres a lanzagranadas y lanzadores de productos químicos, pero también estarás obligado a modificar tu ADN para crear un arma mucho más mortífera: tú. Al inyectarte plásmidos conseguirás superpoderes: lanza descargas eléctricas al agua para electrocutar múltiples enemigos, o congélalos en un bloque de hielo para hacerlos pedazos con un golpe de llave inglesa. Ningún encuentro se juega de la misma manera, ni dos jugadores jugarán igual.",
    review: ``,
    genres: ["Acción", "RPG"],
    favourite: true,
    score: 8,
  },
  {
    id: 46,
    name: "BioShock Infinite",
    author: "2K",
    plot: "Indebted to the wrong people, with his life on the line, veteran of the U.S. Cavalry and now hired gun, Booker DeWitt has only one opportunity to wipe his slate clean. He must rescue Elizabeth, a mysterious girl imprisoned since childhood and locked up in the flying city of Columbia.",
    review: ``,
    genres: ["Acción"],
    favourite: false,
    score: 7,
  },
  {
    id: 47,
    name: "The Binding of Isaac: Rebirth",
    author: "Nicalis, Inc",
    plot: "Cuando la madre de Isaac comienza a escuchar la voz de Dios exigiendo que se haga un sacrificio para probar su fe, Isaac escapa al sótano enfrentándose a hordas de enemigos trastornados, hermanos y hermanas perdidos, sus miedos y, finalmente, a su madre.",
    review: ``,
    genres: ["Acción", "Roguelike", "Indie"],
    favourite: false,
    score: 7,
  },
  {
    id: 48,
    name: "DRAGON QUEST XI S",
    author: "Square Enix",
    plot: "El joven inicia un viaje a través de un mundo desconocido para desentrañar los misterios de su pasado... pero le espera una bienvenida todo menos cálida. Tras revelarse su identidad ante el rey, señalan al héroe como el 'Engendro Oscuro' y un implacable ejército intentará darle caza. Huyendo de sus perseguidores, el chico reúne una banda de atrevidos aventureros que creen que él es en verdad el Luminario renacido. El héroe y sus nuevos compañeros se embarcarán en una misión que los llevará a atravesar varios continentes y vastos océanos mientras descubren más detalles sobre la amenaza que se cierne sobre el mundo.",
    review: ``,
    genres: ["Aventura", "RPG", "JRPG"],
    favourite: true,
    score: 10,
  },
  {
    id: 49,
    name: "Age of Empires II: Definitive Edition",
    author: "Forgotten Empires",
    plot: "El clásico AoE de toda la vida con algunas mejoras gráficas, jugabilidad y nuevo contenido",
    review: ``,
    genres: ["Estrategia"],
    favourite: false,
    score: 7,
  },
  {
    id: 50,
    name: "AI War 2",
    author: "Arcen Games",
    plot: "La inteligencia artificial más tortuosa y aclamada en los juegos de estrategia está mejor que nunca. Un gran híbrido de estrategia/RTS que invierte muchas convenciones de ambos géneros. Toma territorio sin llamar la atención, construye tu imperio con cuidado y adáptate a un campo de batalla galáctico en constante evolución.",
    review: ``,
    genres: ["Estrategia", "Indie", "Simulación"],
    favourite: false,
    score: 6,
  },
  {
    id: 51,
    name: "Cities: Skylines",
    author: "Colossal Order, Paradox Interactive",
    plot: "Introduce nuevos elementos a la mecánica de juego para plasmar la emoción y las complicaciones de mantener una ciudad de verdad, ampliando al mismo tiempo algunos de los temas ya conocidos de la experiencia del desarrollo urbanístico.",
    review: ``,
    genres: ["Simulación", "Estrategia"],
    favourite: false,
    score: 4,
  },
  {
    id: 52,
    name: "Crusader Kings II",
    author: "Paradox Interactive",
    plot: "Explora uno de los periodos decisivos de la historia en una experiencia creada por los maestros de la gran estrategia.",
    review: ``,
    genres: ["Estrategia", "RPG", "Simulación", "Free-to-play"],
    favourite: false,
    score: 6,
  },
  {
    id: 53,
    name: "Crusader Kings III",
    author: "Paradox Interactive",
    plot: "Ama, lucha, planea y reclama la grandeza. Determina el legado de tu casa nobiliaria en la gran estrategia en expansión de Crusader Kings III. La muerte solo es el comienzo mientras lideras el linaje de tu dinastía en esta completa simulación realista de la Edad Media.",
    review: ``,
    genres: ["Simulación", "RPG", "Estrategia"],
    favourite: false,
    score: 7,
  },
  {
    id: 54,
    name: "Democracy 3",
    author: "Positech Games",
    plot: "¿Alguna vez has querido ser presidente o primer ministro? ¿Estás convencido de que podrías gobernar mejor el país? Admitámoslo, es difícil que lo hagas peor que nuestros actuales dirigentes políticos. Delincuencia, desempleo, deuda nacional, terrorismo, cambio climático… ¿Tienes la solución para los problemas a los que se enfrentan los países occidentales industrializados? Esta es tu oportunidad de averiguarlo",
    review: ``,
    genres: ["Indie", "Estrategia", "Simulación"],
    favourite: false,
    score: 5,
  },
  {
    id: 55,
    name: "ENDLESS™ Legend",
    author: "Amplitude Studios",
    plot: "Endless Legend es un juego de estrategia y fantasía 4x basado en turnos de los creadores de Endless Space y Dungeon of the Endless. Controla cada aspecto de tu civilización en tu pugna por salvar tu hogar, Auriga. ¡Crea tu propia leyenda!",
    review: ``,
    genres: ["Estrategia", "RPG"],
    favourite: false,
    score: 8,
  },
  {
    id: 56,
    name: "ENDLESS™ Space - Definitive Edition",
    author: "Amplitude Studios",
    plot: "Endless Space es un juego de estrategia 4X basado en turnos que cubre la época de la colonización espacial en el universo de los Eternos. Puedes controlar todos los aspectos de tu civilización en tu lucha por el dominio galáctico.",
    review: ``,
    genres: ["Estrategia"],
    favourite: false,
    score: 6,
  },
  {
    id: 57,
    name: "ENDLESS™ Space 2",
    author: "Amplitude Studios",
    plot: "Endless Space 2 es un juego estratégico de ciencia ficción espacial que incluye la fórmula “solo un turno más” y se ambienta en el misterioso universo Endless. Como líder de tu civilización, ¿impondrás tu visión y levantarás el imperio estelar más poderoso",
    review: ``,
    genres: ["Estrategia"],
    favourite: false,
    score: 7,
  },
  {
    id: 58,
    name: "Europa Universalis IV",
    author: "Paradox Interactive",
    plot: "Europa Universalis IV te permite controlar una nación a lo largo de cuatro siglos dramáticos. Gobierna tu territorio y domina el mundo con una libertad, una profundidad y una precisión histórica sin precedentes. Reescribe la historia del mundo y construye un imperio para la posteridad.",
    review: ``,
    genres: ["Estrategia"],
    favourite: true,
    score: 9,
  },
  {
    id: 59,
    name: "Frostpunk",
    author: "11 bit studios",
    plot: "Frostpunk es el primer juego de supervivencia de una sociedad. Como dirigente de la última ciudad del mundo, tu deber será el de lidiar tanto con los ciudadanos como con la infraestructura.",
    review: ``,
    genres: ["Simulación", "Estrategia"],
    favourite: false,
    score: 6,
  },
  {
    id: 60,
    name: "Galactic Civilizations III",
    author: "Stardock Entertainment",
    plot: "Construir una civilización que soportará la prueba del tiempo en el juego de estrategia basado en el espacio más grande nunca! Elige entre docenas de razas únicas y hazte un nombre a través de la galaxia a través de la diplomacia, el espionaje, los avances tecnológicos y mucho más.",
    review: ``,
    genres: ["Estrategia"],
    favourite: false,
    score: 6,
  },
  {
    id: 61,
    name: "Rise of Industry",
    author: "Dapper Penguin Studios",
    plot: "Demuestra tus habilidades empresariales en el primer título de la serie ROI mientras creas y optimizas líneas de producción. Como industrial del siglo XX, haz crecer tu imperio y adáptate a un entorno empresarial cambiante que podría lanzarte hacia la cima o provocar una caída.",
    review: ``,
    genres: ["Simulación", "Estrategia", "Indie"],
    favourite: false,
    score: 5,
  },
  {
    id: 62,
    name: "Sid Meier's Civilization® VI",
    author: "Firaxis Games",
    plot: "Civilization VI es la nueva entrega de la galardonada franquicia Civilization. Expande tu imperio, haz avanzar tu cultura y enfréntate a los mejores líderes de la historia. ¿Podrá tu civilización superar la prueba del tiempo?",
    review: ``,
    genres: ["Estrategia"],
    favourite: true,
    score: 8,
  },
  {
    id: 63,
    name: "Stellaris",
    author: "Paradox Interactive",
    plot: "Explora una galaxia repleta de maravillas con este juego de ciencia ficción y gran estrategia de Paradox Development Studio. Interactúa con distintas especies alienígenas, descubre nuevos mundos y amplía el dominio de tu imperio. Cada nueva aventura ofrece posibilidades casi infinitas",
    review: ``,
    genres: ["Simulación", "Estrategia"],
    favourite: true,
    score: 10,
  },
  {
    id: 64,
    name: "Surviving Mars",
    author: "Paradox Interactive",
    plot: "Surviving Mars es un constructor de ciudades de ciencia ficción que trata de colonizar Marte y sobrevivir al intento. Elige una agencia espacial para obtener recursos y apoyo financiero antes de decidir la ubicación de tu colonia. Construye cúpulas e infraestructuras, investiga nuevas posibilidades y utiliza drones para desbloquear maneras más elaboradas de modelar y ampliar tu asentamiento. Cultiva tus propios alimentos, extrae minerales o relájate en el bar después de una larga jornada de trabajo. Pero lo más importante es mantener con vida a tus colonos, una tarea harto compleja en este nuevo y extraño planeta.",
    review: ``,
    genres: ["Simulación", "Estrategia"],
    favourite: false,
    score: 5,
  },
  {
    id: 65,
    name: "Total War: Empire – Definitive Edition",
    author: "Creative Assembly",
    plot: "Domina los mares, toma el control de la tierra, forja una nueva nación y conquista el globo.",
    review: ``,
    genres: ["Estrategia"],
    favourite: false,
    score: 5,
  },
  {
    id: 66,
    name: "Total War: ATTILA",
    author: "Creative Assembly",
    plot: "En un ambiente cada vez más oscuro, con hambre, enfermedad y guerra, un nuevo poder se está alzando en las grandes estepas de Oriente. Con un millón de jinetes a sus espaldas, el gran rey guerrero se acerca, y sus miras están puestas en Roma...",
    review: ``,
    genres: ["Estrategia"],
    favourite: false,
    score: 7,
  },
  {
    id: 67,
    name: "Total War: Medieval II",
    author: "Creative Assembly",
    plot: "Abarcando la época más turbulenta de la historia occidental, tu búsqueda de territorio y poder te llevará por Europa, África, Oriente Medio e incluso a las costas del Nuevo Mundo.",
    review: ``,
    genres: ["Estrategia"],
    favourite: true,
    score: 9,
  },
  {
    id: 68,
    name: "Total War: Napoleon",
    author: "Creative Assembly",
    plot: "Atrévete con la Campaña de la guerra de la Independencia, basada en el intenso conflicto que asoló la península ibérica entre 1811 y 1814. Escoge una de las tres naciones en guerra, Francia, Gran Bretaña o España, y dirige tu campaña por un mapa independiente con 32 nuevas regiones controlables.",
    review: ``,
    genres: ["Estrategia"],
    favourite: false,
    score: 8,
  },
  {
    id: 69,
    name: "Total War: SHOGUN 2",
    author: "Creative Assembly",
    plot: "En la época más oscura de Japón, una interminable guerra deja el país dividido. Estamos en la mitad del siglo XVI en el Japón feudal. El país, una vez liderado por un gobierno unido, ahora está divido en muchos clanes guerreros. Diez caudillos legendarios luchan por la supremacía mientras conspiraciones y conflictos abaten el imperio. Sólo uno de ellos podrá salir triunfante para ganarse el corazón de una nación como el nuevo shogun... los demás morirán bajo su espada.",
    review: ``,
    genres: ["Estrategia"],
    favourite: true,
    score: 10,
  },
  {
    id: 70,
    name: "Total War: Warhammer",
    author: "Creative Assembly",
    plot: "Total War: WARHAMMER es un juego fantástico de estrategia de proporciones épicas y combina una adictiva campaña de construcción de imperios por turnos con colosales y brutales batallas en tiempo real. Todo ello en el vívido e increíble mundo de Warhammer Fantasy Battles.",
    review: ``,
    genres: ["Estrategia"],
    favourite: false,
    score: 7,
  },
  {
    id: 71,
    name: "Total War: Warhammer II",
    author: "Creative Assembly",
    plot: "Total War™: WARHAMMER® II es un juego de estrategia de proporciones épicas. Elige de entre cuatro exclusivas facciones y decide cómo librar la guerra: lanzando una campaña de conquista para salvar este enorme y fantástico mundo o destruirlo.",
    review: ``,
    genres: ["Estrategia"],
    favourite: false,
    score: 8,
  },
  {
    id: 72,
    name: "Tropico 6",
    author: "Kalypso Media",
    plot: "¡El Presidente ha vuelto! Demuestra una vez más tu valía como temible dictador u hombre de estado pacifista en la isla de Tropico y erige el futuro de tu nación durante cuatro eras emblemáticas.",
    review: ``,
    genres: ["Simulación", "Estrategia"],
    favourite: false,
    score: 7,
  },
  {
    id: 73,
    name: "Tropico 5",
    author: "Kalypso Media",
    plot: "Vuelve a la remota isla nación de Trópico en la nueva entrega de la famosa y aclamada saga de 'simulación de una dictadura'. Expande el reinado de tu dinastía desde el periodo colonial hasta más allá del siglo XXI y enfréntate a nuevos retos.",
    review: ``,
    genres: ["Simulación", "Estrategia"],
    favourite: false,
    score: 8,
  },
  {
    id: 74,
    name: "Victoria 3",
    author: "Paradox Interactive",
    plot: "Paradox Development Studio te invita a formar tu sociedad ideal en el tumulto del siglo XIX, con todas sus emociones y transformaciones. Equilibra los intereses contrapuestos de tu sociedad y hazte un hueco en Victoria 3, uno de los juegos más esperados de la historia de Paradox.",
    review: ``,
    genres: ["Simulación", "Estrategia"],
    favourite: false,
    score: 6,
  },
  {
    id: 75,
    name: "Victoria 2",
    author: "Paradox Interactive",
    plot: "Dirige cuidadosamente a tu nación desde la época de la monarquía absoluta de principios del siglo XIX, a través de la expansión y colonización, para convertirte finalmente en una verdadera potencia mundial en los albores del siglo XX.",
    review: ``,
    genres: ["Estrategia"],
    favourite: true,
    score: 8,
  },
  {
    id: 76,
    name: "TERA",
    author: "Bluehole Studio",
    plot: "Plot left the chat",
    review: `134 horas perdidas`,
    genres: ["Aventura", "RPG"],
    favourite: false,
    score: 3,
  },
  {
    id: 77,
    name: "War Thunder",
    author: "Gaijin Entertainment",
    plot: "War Thunder es un juego de combate MMO gratuito de vehículos militares usados en la Segunda Guerra Mundial y la guerra de Corea. Lucha en grandes batallas de tierra, mar y aire con jugadores internacionales en un entorno en continuo desarrollo.",
    review: `Decente juego online, nada que decir.`,
    genres: ["Acción", "Free-to-play", "Simulación"],
    favourite: false,
    score: 3,
  },
  {
    id: 78,
    name: "Warframe",
    author: "Digital Extremes",
    plot: "Despierta como un guerrero imparable y lucha junto a tus amigos en este juego de acción gratuito en línea y basado en historias.",
    review: `Juego decente que puede ser entretenido... Si no fuera un free to play online.`,
    genres: ["Acción", "RPG", "Free-to-play"],
    favourite: false,
    score: 4,
  },
  {
    id: 79,
    name: "Grand Theft Auto V",
    author: "Rockstar Games",
    plot: "Cuando un joven estafador callejero, un ladrón de bancos retirado y un psicópata aterrador se ven involucrados con lo peor y más desquiciado del mundo criminal, del gobierno de los EE. UU. y de la industria del espectáculo, tendrán que llevar a cabo una serie de peligrosos golpes para sobrevivir en una ciudad implacable en la que no pueden confiar en nadie. Y mucho menos los unos en los otros.",
    review: ``,
    genres: ["Aventura", "RPG", "Indie"],
    favourite: false,
    score: 7,
  },
  {
    id: 80,
    name: "Fall Guys",
    author: "Mediatonic",
    plot: "Fall Guys es un party royale gratis y multiplataforma donde los jugadores compiten en delirantes carreras de obstáculos formadas por rondas cada vez más emocionantes hasta que una sola persona se alza con la victoria.",
    review: ``,
    genres: ["Acción", "Casual", "Indie"],
    favourite: false,
    score: 6,
  },
  {
    id: 81,
    name: "Sea of Thieves",
    author: "Rare",
    plot: "Sea of Thieves es un exitoso juego de aventuras piratas que ofrece la experiencia pirata por excelencia de saquear tesoros perdidos, batallas intensas, vencer monstruos marinos y más. Sumérgete en esta edición revisada del juego, que incluye acceso a medios digitales de bonificación.",
    review: ``,
    genres: ["Aventura", "Acción"],
    favourite: false,
    score: 7,
  },
  {
    id: 82,
    name: "Alan wake 2",
    author: "Remedy",
    plot: "Llega Saga Anderson para investigar asesinatos ritualistas en un pequeño pueblo. Alan Wake escribe una oscura historia para dar forma a la realidad que lo rodea. Estos dos héroes están conectados de algún modo. ¿Podrán convertirse en los héroes que han de ser?",
    review: ``,
    genres: ["Terror", "Acción"],
    favourite: true,
    score: 10,
  },
  {
    id: 83,
    name: "Alan wake",
    author: "Remedy",
    plot: "Una oscura presencia acecha a la pequeña localidad de Bright Falls, empujando a Alan Wake al borde de la locura en su lucha por desentrañar el enigma y salvar a su esposa.",
    review: ``,
    genres: ["Acción"],
    favourite: false,
    score: 8,
  },
  {
    id: 84,
    name: "The Elder Scrolls V: Skyrim",
    author: "Bethesda Game Studios",
    plot: "La historia se centra en los esfuerzos del personaje, Dovahkiin (Sangre de dragón), para derrotar a Alduin, un dragón o «dovah» que, según la profecía, destruirá el mundo. La trama está fechada doscientos años después de los sucesos de Oblivion y tiene lugar en la provincia ficticia de Skyrim.",
    review: ``,
    genres: ["RPG", "Aventura"],
    favourite: false,
    score: 7,
  },
  {
    id: 85,
    name: "Warhammer 40,000: Dawn of War II",
    author: "Relic Entertainment",
    plot: "Estamos en el cuadragésimo primer milenio, en el Sub-Sector Aurelia: un cúmulo de planetas en un confín de la galaxia, donde una batalla de proporciones épicas está a punto de comenzar. Antiguas razas se enfrentarán en los planetas de este sector espacial en un todo por el todo.",
    review: ``,
    genres: ["Estrategia"],
    favourite: false,
    score: 8,
  },
];

export default completedGames;
